// pnpm exec tsx src/cli/validate-reasons.ts [--root <path>]... [--revalidate] [--list] [--census]
//                                           [--live | --tier <name>]... [--issues]
//
// The #1033 gate over recorded reasons. Two passes:
//
//   • STRUCTURAL (always, no commands run) — every reason block is well-formed: it declares whether
//     it is empirical or decisional, carries a MEASURED/TRIED/ASSUMED provenance tag with a date,
//     and — if empirical — carries the command that would falsify it. Fast enough to run in CI and
//     locked by src/recorded-reasons.test.ts so `pnpm verify` enforces it.
//   • --revalidate (runs each empirical falsifier) — a falsifier that now EXITS 0 means the blocker
//     it describes is gone while the text still asserts it. That is a failing row, not a note.
//     Decisional reasons are excluded from this pass entirely; they await a human, not a command.
//
// Also reports subsystem drift: commits landing after the reason's date on the paths it declares in
// TOUCHES: plus the paths its FALSIFIER: names that exist in this checkout (#1246). Advisory — it is
// a prompt to re-read, not a verdict.
//
// `--census` lists the claim-shaped prose lines that are NOT inside any reason block; the count is
// printed on every run. Untriaged, not malformed — advisory, and a deliberate lower bound (#1246).
//
// `--issues` folds the open GitHub issues' bodies and comments in as extra surfaces, because
// collectReasons reads files and a blocker recorded in an issue is otherwise gated by nothing. Their
// blocks are held to the same structure; their falsifiers are NOT executed — an issue body is
// attacker-writable input, so running its commands would turn this gate into a remote-execution
// surface. To get a claim re-tested, mirror it into the repo (#920/#921's blocks mirror
// src/scan/sfc-coverage.ts). Needs an authenticated `gh`; it fails loud rather than reporting zero.
//
// A live-tier falsifier names its target as a `<placeholder>` because the target is stood up outside
// the repo. Bind each one in the environment on the run that has the tier — `<crapi-gateway>` reads
// HARVEY_FALSIFIER_CRAPI_GATEWAY — e.g.
//   HARVEY_FALSIFIER_SUPERREDHAT_CLONE=/clones/superredhat pnpm validate-reasons --revalidate --tier secbench
// An unbound placeholder is reported UNVERIFIABLE and the command is not run (#1072).

import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CLAIM_BASELINE } from "../unstructured-claims-baseline.js";
import { parityExemptionReasons } from "../scan/calibration.js";
import {
  DEFAULT_ROOTS,
  KNOWN_FALSIFIER_TIERS,
  claimCensusByFile,
  claimCounts,
  attributeClaim,
  claimDrift,
  claimTotal,
  censusScope,
  collectSources,
  issueSources,
  parseRecordedReasons,
  placeholderEnvVar,
  reasonKind,
  revalidateReasons,
  subsystemDrift,
  untriagedClaims,
  validateRecordedReason,
  watchedPaths,
  type FalsifierResult,
  type FetchedIssue,
  type ParsedReason,
  type SourceText,
} from "../recorded-reasons.js";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const FALSIFIER_TIMEOUT_MS = 120_000;

function renderBaseline(claims: { file: string; text: string }[]): string {
  const byFile = new Map<string, string[]>();
  for (const c of claims) byFile.set(c.file, [...(byFile.get(c.file) ?? []), c.text]);
  const rows = [...byFile.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([file, texts]) => `  ${JSON.stringify(file)}: [\n${texts.map((t) => `    ${JSON.stringify(t)},`).join("\n")}\n  ],`)
    .join("\n");
  return `// GENERATED by \`pnpm validate-reasons --update-baseline\` (#1318). Do not hand-edit.
//
// The per-file ceiling on claim-shaped prose lines living OUTSIDE any REASON block —
// "cannot", "impossible", "no way to", "unable to" and friends, which nothing re-tests because
// only reason BLOCKS are re-tested. The ratchet lets this fall, never rise.
//
// Each claim is recorded VERBATIM rather than as a count, for two reasons. A breach can then name
// the lines that are actually new instead of reprinting every claim in the breaching file (#1318's
// "otherwise the fix is a guessing game"). And raising a number here becomes a reviewable act with
// something to review: the diff shows the new standing claims, not a total going up. Prefer writing
// the block over bumping the file.
//
// Since #1347 this covers prose (\`.md\`/\`.txt\`) whole and COMMENT LINES of \`.ts\`/\`.yml\`/\`.sql\`.
// This file is excluded from its own census — it quotes every claim in the repo verbatim.

export const CLAIM_BASELINE: Record<string, string[]> = {
${rows}
};
`;
}

function flagValues(flag: string): string[] {
  return process.argv.flatMap((arg, i) => {
    const next = process.argv[i + 1];
    return arg === flag && next ? [next] : [];
  });
}

function runFalsifier(command: string): FalsifierResult {
  const r = spawnSync("sh", ["-c", command], { cwd: REPO_ROOT, encoding: "utf8", timeout: FALSIFIER_TIMEOUT_MS });
  return { code: r.status, output: `${r.stdout ?? ""}${r.stderr ?? ""}` };
}

// End-of-day, not start: a reason recorded on day D is presumed to account for everything that
// landed up to and including D, so only later commits are news. A bare `--since=<date>` is also not
// what it looks like — git resolves it against now and skips same-day commits — so the time is
// explicit here rather than implied.
function commitsSince(paths: string[], since: string): string[] {
  const r = spawnSync("git", ["log", `--since=${since} 23:59:59`, "--format=%h", "--", ...paths], { cwd: REPO_ROOT, encoding: "utf8" });
  return (r.stdout ?? "").split("\n").filter(Boolean);
}

// #1401 — where a breaching claim line came from. `git blame --porcelain` is used for its stable
// first line (`<sha> <orig-line> <final-line>`); the subject comes from a second, cheap lookup so a
// porcelain header parser is not needed. Both degrade to `undefined`, which attributeClaim renders
// as a stated "provenance unavailable" rather than a guess.
function blameLine(file: string, line: number): { sha: string; subject: string } | undefined {
  const b = spawnSync("git", ["blame", "-L", `${line},${line}`, "--porcelain", "--", file], { cwd: REPO_ROOT, encoding: "utf8" });
  const sha = b.status === 0 ? (b.stdout ?? "").split(" ")[0] : undefined;
  if (!sha || /^0+$/.test(sha)) return undefined;
  const s = spawnSync("git", ["log", "-1", "--format=%h %s", sha], { cwd: REPO_ROOT, encoding: "utf8" });
  return { sha, subject: (s.stdout ?? "").trim() };
}

/** Full shas of the commits this branch adds to its base, or undefined when the range is unknowable. */
function branchCommits(): Set<string> | undefined {
  for (const base of ["origin/main", "main"]) {
    const mb = spawnSync("git", ["merge-base", "HEAD", base], { cwd: REPO_ROOT, encoding: "utf8" });
    if (mb.status !== 0) continue;
    const list = spawnSync("git", ["rev-list", `${(mb.stdout ?? "").trim()}..HEAD`], { cwd: REPO_ROOT, encoding: "utf8" });
    if (list.status === 0) return new Set((list.stdout ?? "").split("\n").filter(Boolean));
  }
  return undefined;
}

const inRepo = (path: string): boolean => existsSync(resolve(REPO_ROOT, path));
const recordedInIssue = (r: ParsedReason): boolean => r.file.startsWith("issue #");

// Closed issues are out of scope BY DECISION: a blocker on a closed issue no longer steers work, and
// the population is unbounded. Said here rather than left silent — an unstated limit reads as
// coverage (#1246).
function fetchOpenIssues(): SourceText[] {
  const r = spawnSync("gh", ["issue", "list", "--state", "open", "--limit", "300", "--json", "number,body,comments"], { cwd: REPO_ROOT, encoding: "utf8" });
  if (r.status !== 0) {
    console.error(`✗ --issues: \`gh issue list\` failed (exit ${r.status ?? "signal"}) — it needs an authenticated gh. Reporting zero issue-recorded claims here would be the silent pass this gate exists to prevent.\n${(r.stderr ?? "").trim()}`);
    process.exit(1);
  }
  return issueSources(JSON.parse(r.stdout) as FetchedIssue[]);
}

const roots = flagValues("--root");
const sources = collectSources(roots.length > 0 ? roots : DEFAULT_ROOTS, REPO_ROOT);
const fileReasons = sources.flatMap(({ file, text }) => parseRecordedReasons(text, file));

const issues = process.argv.includes("--issues") ? fetchOpenIssues() : [];
const issueReasons = issues.flatMap(({ file, text }) => parseRecordedReasons(text, file, true));

// #1454 — a parity exemption is a recorded reason held as DATA, which the file walk above never
// reads. Folding it in here is what puts its falsifier under --revalidate: the structural half is also
// enforced at the calibration gate (validateParityExemptions), but a claim that is only ever checked
// for SHAPE is the half-gate this issue is about.
//
// Skipped under --root, on the ratchet's precedent below: --root narrows the run to a caller-chosen
// surface, and a reason that is not in that surface would otherwise ride along and change every
// count the narrowed run reports.
const exemptionReasons = roots.length > 0 ? [] : parityExemptionReasons();

const reasons: ParsedReason[] = [...fileReasons, ...issueReasons, ...exemptionReasons];
const empirical = reasons.filter((r) => reasonKind(r) === "empirical");
const decisional = reasons.filter((r) => reasonKind(r) === "decisional");

console.log(`Recorded reasons (#1033): ${reasons.length} — ${empirical.length} empirical, ${decisional.length} decisional`);
console.log(
  roots.length > 0
    ? "  parity exemptions (#1454) not folded in — --root narrowed this run to a caller-chosen surface. Run without --root to hold them."
    : `  including ${exemptionReasons.length} parity exemption(s) held as data in src/scan/calibration.ts, outside the file walk's reach (#1454)`,
);
if (process.argv.includes("--issues")) console.log(`  including ${issueReasons.length} recorded in ${issues.length} open-issue bodies/comments (closed issues out of scope by decision, #1246)`);

if (process.argv.includes("--list")) {
  for (const r of reasons) console.log(`  ${r.file}:${r.line}  [${r.fields.KIND ?? "?"}] ${r.fields.REASON?.slice(0, 100) ?? ""}`);
}

let failed = false;

const malformed = reasons.map((r) => ({ r, errors: validateRecordedReason(r, inRepo) })).filter((x) => x.errors.length > 0);
if (malformed.length > 0) {
  failed = true;
  console.error(`\n✗ ${malformed.length} malformed reason block(s):`);
  for (const { r, errors } of malformed) {
    console.error(`  ${r.file}:${r.line} — ${r.fields.REASON?.slice(0, 90) ?? "(no claim)"}`);
    for (const e of errors) console.error(`      • ${e}`);
  }
} else {
  console.log("✓ every reason block is well-formed (kind declared, provenance dated, empirical reasons carry a falsifier)");
}

for (const row of subsystemDrift(reasons, commitsSince, inRepo)) {
  console.log(`\nℹ SUBSYSTEM MOVED  ${row.file}:${row.line}\n    ${row.claim.slice(0, 120)}\n    ${row.detail}`);
}

// The complement of the drift rows above, and the reason they are trustworthy: a reason with no
// watchable path produces no drift row for the same reason a clean repo does. Counted so the two
// cannot be confused (#1246).
const unwatched = empirical.filter((r) => watchedPaths(r, inRepo).length === 0);
console.log(`\nSubsystem drift watches ${empirical.length - unwatched.length}/${empirical.length} empirical reason(s) — the rest name no path that exists here, so silence from them is absence of evidence:`);
for (const r of unwatched) console.log(`  ${r.file}:${r.line} — add TOUCHES: <paths> to put this claim's subsystem under watch`);

// Claim-shaped lines outside any block: untriaged, not malformed. Advisory and a lower bound.
const prose = untriagedClaims([...sources, ...issues], reasons);
const byRoot = new Map<string, number>();
for (const c of prose) {
  const key = c.file.startsWith("issue #") ? "open issues" : (c.file.split("/")[0] as string);
  byRoot.set(key, (byRoot.get(key) ?? 0) + 1);
}
const breakdown = [...byRoot].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([k, n]) => `${k} ${n}`).join(", ");
console.log(`\nUntriaged claim-shaped lines (advisory, LOWER BOUND — a fixed vocabulary): ${prose.length}${prose.length > 0 ? ` — ${breakdown}` : ""}`);
console.log("  Each is a standing claim outside any REASON block, so nothing re-tests it. --census lists them.");

// What this pass READ, not just what it found — a scope boundary nobody states reads as coverage.
// The ratchet below inherits this boundary exactly, so it is printed on every run (#1347).
const scoped = (kind: string) => sources.filter((s) => censusScope(s.file) === kind).length;
console.log(`  CENSUSED WHOLE: ${scoped("prose")} .md/.txt file(s) under ${(roots.length > 0 ? roots : DEFAULT_ROOTS).join(", ")}${issues.length > 0 ? `, plus ${issues.length} open-issue surface(s)` : ""}.`);
console.log(`  CENSUSED COMMENTS ONLY: ${scoped("comments")} .ts/.yml/.sql file(s) — comment lines are read, code lines are NOT. Measured 2026-07-28: that drops 270 claim-shaped code lines, which are error-message strings, not-assessed details and test titles, i.e. the vocabulary firing on ordinary code prose.`);
console.log(`  NOT CENSUSED: ${scoped("none")} file(s) — the generated baseline itself, which records every claim verbatim and would otherwise match the whole repo against itself.`);
console.log("  The vocabulary is standing-IMPOSSIBILITY plus the unverified register. It does not reach a POSITIVE over-claim: #1304's `Verified live` (src/detectors/bundle-stats.ts:21) belongs to a different function and is invisible here. Measured 2026-07-28 — reaching it needs bare `verified`, which is 663 lines under DEFAULT_ROOTS, nearly all of them correct.");
if (process.argv.includes("--census")) {
  for (const c of prose) console.log(`  ${c.file}:${c.line}  ${c.text.slice(0, 140)}`);
}

// #1318 — the ratchet. Repo files only: an open issue's claims are not in anyone's diff and would
// fail this gate for tracker activity no PR caused.
const repoProse = prose.filter((c) => !c.file.startsWith("issue #"));
const census = claimCensusByFile(repoProse);
const baselineCounts = claimCounts(CLAIM_BASELINE);
const drift = claimDrift(CLAIM_BASELINE, repoProse);
const branchShas = drift.length > 0 ? branchCommits() : undefined;
const inherited = { authored: 0, arrived: 0, unknown: 0 };

// The baseline describes DEFAULT_ROOTS. Scored against a caller-narrowed --root it would compare
// two different populations, so it is skipped — and said out loud, because a silently skipped gate
// is the thing this whole file is against.
if (roots.length > 0) {
  console.log(`\nRatchet (#1318): not scored — --root narrowed the census to ${roots.join(", ")}, and the committed baseline describes the default roots. Run without --root to score it.`);
} else if (process.argv.includes("--update-baseline")) {
  writeFileSync(resolve(REPO_ROOT, "src/unstructured-claims-baseline.ts"), renderBaseline(repoProse));
  console.log(`\n✓ baseline rewritten: ${claimTotal(census)} claim line(s) across ${Object.keys(census).length} file(s). Commit it — a raised number needs a human to see it, and the diff now shows the claims themselves.`);
} else {
  // The baseline total is printed whether or not the gate fires. #1318's rule: the output must name
  // the number so it cannot be quietly ignored the way the advisory census was for months.
  console.log(`\nRatchet (#1318/#1399/#1685): ${claimTotal(census)} claim line(s) in repo files against a committed baseline of ${claimTotal(baselineCounts)}. The recorded SET may shrink, never gain a member — a reword is a new member, and a member that is GONE has to be pruned in the diff, not left behind.`);
  for (const d of drift) {
    failed = true;
    // Only the lines the baseline does not account for. Printing all of them is the guessing game
    // #1318's third criterion names: on a file with a baseline of 18, a breach printed nineteen
    // lines with nothing marking the new one.
    console.error(`\n✗ CLAIM RATCHET  ${d.file} — ${d.baseline} → ${d.now}`);
    if (d.added.length > 0) console.error(`    ${d.added.length} line(s) not in the committed baseline for this file (${d.now - d.added.length} carried over, not shown):`);
    for (const claim of d.added) {
      console.error(`      NEW  ${d.file}:${claim.line}  ${claim.text.slice(0, 120)}`);
      // #1401 — say where it came from. Repo-wide scoring means a breaching line can be in a file
      // this branch never opened, and "your PR broke the ratchet" sends the author hunting in their
      // own diff. INHERITED rows are still the author's to baseline; they are just not their defect.
      const origin = attributeClaim(claim, blameLine, branchShas);
      if (!origin.known) inherited.unknown += 1;
      else if (origin.authoredHere) inherited.authored += 1;
      else inherited.arrived += 1;
      console.error(
        origin.known
          ? `           ↳ ${origin.authoredHere ? "AUTHORED on this branch" : "INHERITED — already on the base branch"} by ${origin.subject}`
          : `           ↳ provenance unavailable: ${origin.why}`,
      );
    }
    // #1399 — a REWORD is one added line and one dropped line, and printing only the added half is
    // what let it read as an ordinary new claim. Pairing them is the whole point of the verbatim
    // baseline: the reviewer sees what the claim USED to say next to what it says now.
    if (d.dropped.length > 0) {
      // #1685 — a DEAD baseline row is a breach in its own right, not a footnote to an added one.
      // Left unfailed it sat in the baseline forever, inflating the very backlog number this gate
      // prints. Pruning it has to be an act someone performs in a diff, the way test-only-exports
      // makes a self-healed row fail rather than dropping it silently.
      console.error(
        d.added.length > 0
          ? `    ${d.dropped.length} baseline line(s) for this file are no longer present. If one pairs with a NEW row above, that claim was REWORDED — read the two together and check the new text is not a stronger claim:`
          : `    ${d.dropped.length} baseline line(s) for this file are no longer present and nothing replaced them. The claim was retired — prune the row so the recorded count falls deliberately (#1685):`,
      );
      for (const text of d.dropped) console.error(`      WAS  ${text.slice(0, 120)}`);
    }
  }
  if (drift.some((d) => d.added.length > 0)) {
    console.error(`\n  ${inherited.authored} row(s) AUTHORED on this branch, ${inherited.arrived} INHERITED from the base branch, ${inherited.unknown} unattributable.`);
    if (inherited.arrived > 0) console.error(`  An INHERITED row is not a defect in your diff — it reached the base branch unbaselined. Baseline it and say so; do not go looking for it in your own changes (#1401).`);
    console.error(`\n  Write the new claim as a REASON:/KIND:/PROVENANCE:/FALSIFIER: block (docs/design/recorded-reasons.md) so --revalidate re-tests it,`);
    console.error(`  or run \`pnpm validate-reasons --update-baseline\` and commit the raised number for a human to review.`);
  }
  if (drift.some((d) => d.dropped.length > 0)) {
    console.error(`\n  For the DEAD rows: \`pnpm validate-reasons --update-baseline\` prunes them and the diff shows the recorded set shrinking, which is the direction this ratchet is for (#1685).`);
  }
}

if (process.argv.includes("--revalidate")) {
  // --live enables every registered tier; --tier <name> (repeatable) enables specific ones. An
  // unknown --tier is refused loudly rather than silently enabling nothing.
  const requestedTiers = flagValues("--tier");
  const unknownTiers = requestedTiers.filter((t) => !KNOWN_FALSIFIER_TIERS.has(t));
  if (unknownTiers.length > 0) {
    console.error(`✗ unknown --tier: ${unknownTiers.join(", ")} — known tiers: ${[...KNOWN_FALSIFIER_TIERS].join(", ")}`);
    process.exit(1);
  }
  const availableTiers = process.argv.includes("--live") ? new Set(KNOWN_FALSIFIER_TIERS) : new Set(requestedTiers);

  // An issue body is attacker-writable: anyone who can comment can author a FALSIFIER:, so running
  // one would make this gate a remote-execution surface — a scheduled `--issues --revalidate` would
  // execute it with the repo checked out. They are held to the structure above and reported here
  // instead; the way to get a claim re-tested is to mirror the block into the repo (#1246).
  for (const r of empirical.filter(recordedInIssue)) {
    console.log(`\nℹ NOT RE-TESTED  ${r.file}:${r.line}\n    ${r.fields.REASON?.slice(0, 120) ?? ""}\n    recorded outside the repo — its FALSIFIER is not executed, because an issue body is input anyone with comment access can write. Mirror this block into the file it constrains to put it under \`--revalidate\`.`);
  }

  const rows = revalidateReasons(empirical.filter((r) => !recordedInIssue(r)), runFalsifier, availableTiers, (placeholder) => process.env[placeholderEnvVar(placeholder)]);
  const skippedLive = rows.filter((row) => row.status === "SKIPPED-LIVE");
  const broken = rows.filter((row) => row.status === "STALE" || row.status === "UNVERIFIABLE");
  const ran = rows.length - skippedLive.length;
  console.log(`\nRe-validated ${ran} empirical falsifier(s); ${skippedLive.length} live-only skipped; ${decisional.length} decisional reason(s) excluded by kind.`);
  for (const row of skippedLive) {
    console.log(`\nℹ SKIPPED-LIVE  ${row.file}:${row.line}\n    ${row.claim.slice(0, 120)}\n    ${row.detail}`);
  }
  for (const row of broken) {
    failed = true;
    console.error(`\n✗ ${row.status}  ${row.file}:${row.line}\n    ${row.claim.slice(0, 120)}\n    ${row.detail}`);
  }
  if (broken.length === 0 && ran > 0) console.log("✓ every empirical falsifier run still exits non-zero — no reason has outlived its truth");
}

process.exit(failed ? 1 : 0);
