import ts from "typescript";
import type { Finding } from "../findings.js";
import { mechanicalFinding } from "../scan/common.js";
import { leadingDirective, loc, parse, type SourceInput } from "./common.js";

export const M5_HARDCODED_ENDPOINT_TAXONOMY = "M5 — Hardcoded deployment endpoint";
export const M5_HARDCODED_IDENTIFIER_TAXONOMY = "M5 — Hardcoded provider identifier";

const SOURCE_EXTENSION = /\.(?:[cm]?[jt]s|[jt]sx)$/i;
const NON_PRODUCT_SEGMENT = /^(?:\.next|__fixtures__|__tests__|build|coverage|dist|docs?|examples?|fixtures?|generated|mocks?|node_modules|out|samples?|test(?:s|data)?|vendor)$/i;
const NON_PRODUCT_FILE = /(?:^|\.)(?:generated|min|mock|spec|stories|test)\.[cm]?[jt]sx?$/i;
const GENERATED_MARKER = /(?:^|\n)\s*(?:\/\/|\/\*)\s*(?:@generated|generated by|code generated|do not edit\b)/i;

const ENDPOINT_LABEL = /^(?:api[_-]?url|base[_-]?url|destination|endpoint|host|origin|service[_-]?url|target|upstream|url|webhook[_-]?url)$/i;
const STRONG_ENDPOINT_LABEL = /^(?:api[_-]?url|base[_-]?url|destination|endpoint|service[_-]?url|upstream|webhook[_-]?url)$/i;
const IDENTIFIER_LABEL = /(?:^|[_-])(?:account|organisation|organization|org|project|provider|subscription|tenant|workspace)(?:[_-]?id)?$/i;
const TENANT_SENSITIVE_LABEL = /(?:^|[_-])(?:customer|member|organisation|organization|org|owner|tenant|user|workspace)(?:[_-]?id)?$/i;
const SECRET_LABEL = /(?:api[_-]?key|authorization|bearer|cookie|credential|jwt|password|private[_-]?key|secret|session|signature|signing|token)/i;
const CONFIG_CONTAINER = /(?:client|config|deployment|environment|options|provider|settings)/i;
const CONFIG_PATH = /(?:^|\/)(?:config|configuration|deploy|deployment|environment|infra|infrastructure|providers?|settings)(?:[/.]|$)/i;

const REQUEST_CALL = /(?:^|\.)(?:delete|fetch|get|head|patch|post|put|request)$/i;
const ROUTE_CALL = /(?:^|\.)(?:mount|proxy|redirect|rewrite|route|use)$/i;
const CLIENT_CALL = /(?:client|connector|gateway|provider|sdk|service|transport)/i;
const CLIENT_SOURCE_PATH = /(?:^|\/)(?:app|client|components?|pages?|ui)(?:\/|$)/i;

const CANONICAL_PUBLIC_HOSTS = new Set([
  "api.github.com",
  "api.openai.com",
  "api.stripe.com",
  "api.twilio.com",
  "api.sendgrid.com",
  "graph.microsoft.com",
  "login.microsoftonline.com",
  "s3.amazonaws.com",
  "storage.googleapis.com",
  "www.googleapis.com",
]);

const EXAMPLE_HOST = /(?:^|\.)(?:example\.(?:com|net|org)|example|invalid)$/i;
const LOOPBACK_HOST = /^(?:0\.0\.0\.0|127(?:\.\d{1,3}){3}|\[?::1\]?|localhost)$/i;
const DEV_HOST = /(?:^|[.-])(?:dev|development|fixture|local|mock|sandbox|test)(?:[.-]|$)/i;
const ENVIRONMENT_HOST = /(?:^|[.-])(?:prod|production|qa|preview|stage|staging)(?:[.-]|$)/i;
const PRIVATE_NETWORK_HOST = /^(?:10\.\d{1,3}(?:\.\d{1,3}){2}|172\.(?:1[6-9]|2\d|3[01])(?:\.\d{1,3}){2}|192\.168(?:\.\d{1,3}){2})$/;
const PROVIDER_TENANT_HOST = /(?:\.supabase\.co|\.firebaseio\.com|\.cloudfront\.net|\.azurewebsites\.net|\.vercel\.app|\.netlify\.app|\.run\.app)$/i;
const AWS_GATEWAY_HOST = /^[a-z0-9-]+\.execute-api\.[a-z0-9-]+\.amazonaws\.com$/i;
const SECRET_QUERY_KEY = /(?:api[_-]?key|authorization|credential|jwt|password|secret|signature|token)/i;

const PREFIXED_IDENTIFIER = /^(?:acc(?:ount)?|acct|org|prj|project|provider|sub(?:scription)?|tenant|workspace|ws)[_-][a-z0-9][a-z0-9_-]{5,}$/i;
const PATH_IDENTIFIER = /^(?:accounts?|organisations?|organizations?|projects?|providers?|subscriptions?|tenants?|workspaces?)\/[a-z0-9][a-z0-9._/-]{5,}$/i;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const AWS_ACCOUNT = /^\d{12}$/;
const PROJECT_SLUG = /^[a-z][a-z0-9-]{5,29}$/i;

type DeploymentValueKind = "endpoint" | "identifier";
type ConsumerKind = "client construction" | "configuration" | "request" | "routing";

interface ConsumerContext {
  kind: ConsumerKind;
  label?: string;
  node: ts.Node;
}

export const M5_HARDCODED_DEPLOYMENT_METADATA = Object.freeze({
  id: "m5-hardcoded-deployment",
  module: "M5" as const,
  implementation: Object.freeze({
    file: "src/detectors/m5-hardcoded-deployment.ts",
    exportName: "detectM5HardcodedDeploymentFindings",
  }),
  findingIds: Object.freeze(["M5-HARDCODED-ENDPOINT-*", "M5-HARDCODED-IDENTIFIER-*"]),
  taxonomies: Object.freeze([M5_HARDCODED_ENDPOINT_TAXONOMY, M5_HARDCODED_IDENTIFIER_TAXONOMY]),
  precisionTier: "review" as const,
  applicableFiles: "Tracked JavaScript/TypeScript application source after non-product and generated paths are excluded",
  examinedUnit: "One applicable source path parsed as a TypeScript AST; only literal values in configuration, client-construction, request, or routing consumers are classified",
  prerequisites: Object.freeze(["shared source inventory", "shared TypeScript AST cache"]),
  ownershipExclusions: "Credentials, tokens, signing material, and tenant-sensitive client/request exposure are M1-owned and never emitted as M5",
  fallback: "Dynamic/computed values and unsupported or ambiguous consumers make no defect claim; an empty applicable population must be recorded as NotAssessed by the live registry",
  providerLifecycle: "source-only; provider credentials, live state, and lifecycle APIs are never consulted",
});

function normalizedPath(path: string): string {
  return path.replaceAll("\\", "/");
}

export function isM5HardcodedDeploymentSource(file: SourceInput): boolean {
  const path = normalizedPath(file.path);
  if (!SOURCE_EXTENSION.test(path) || NON_PRODUCT_FILE.test(path) || GENERATED_MARKER.test(file.text)) return false;
  return !path.split("/").slice(0, -1).some((segment) => NON_PRODUCT_SEGMENT.test(segment));
}

function propertyLabel(node: ts.StringLiteralLike): string | undefined {
  const parent = node.parent;
  if (!ts.isPropertyAssignment(parent) || parent.initializer !== node) return undefined;
  const name = parent.name;
  if (ts.isIdentifier(name) || ts.isStringLiteralLike(name) || ts.isNumericLiteral(name)) return name.text;
  return undefined;
}

function variableContainer(node: ts.Node): ts.VariableDeclaration | undefined {
  for (let current: ts.Node | undefined = node.parent; current; current = current.parent) {
    if (ts.isVariableDeclaration(current)) return current;
    if (ts.isStatement(current)) break;
  }
  return undefined;
}

function variableName(node: ts.VariableDeclaration | undefined): string | undefined {
  return node && ts.isIdentifier(node.name) ? node.name.text : undefined;
}

function callName(node: ts.CallExpression | ts.NewExpression, sf: ts.SourceFile): string {
  return node.expression.getText(sf).replace(/\s+/g, " ");
}

function supportedCall(node: ts.Node, sf: ts.SourceFile): ConsumerContext | undefined {
  for (let current: ts.Node | undefined = node.parent; current; current = current.parent) {
    if (ts.isCallExpression(current) || ts.isNewExpression(current)) {
      const name = callName(current, sf);
      if (ROUTE_CALL.test(name)) return { kind: "routing", node: current };
      if (REQUEST_CALL.test(name)) return { kind: "request", node: current };
      if (CLIENT_CALL.test(name) || (ts.isCallExpression(current) && /(?:^|\.)create$/i.test(name))) {
        return { kind: "client construction", node: current };
      }
      return undefined;
    }
    if (ts.isStatement(current)) return undefined;
  }
  return undefined;
}

function configContext(node: ts.Node, path: string, label: string | undefined): ConsumerContext | undefined {
  const declaration = variableContainer(node);
  const container = variableName(declaration);
  if (declaration && container && CONFIG_CONTAINER.test(container)) {
    return { kind: "configuration", label, node: declaration };
  }
  if (CONFIG_PATH.test(normalizedPath(path))) {
    const property = node.parent;
    return { kind: "configuration", label, node: ts.isPropertyAssignment(property) ? property : node };
  }
  return undefined;
}

function endpointUrl(value: string): URL | undefined {
  if (!/^https?:\/\//i.test(value)) return undefined;
  try {
    return new URL(value);
  } catch {
    return undefined;
  }
}

function isM1OwnedUrl(url: URL): boolean {
  if (url.username.length > 0 || url.password.length > 0) return true;
  return [...url.searchParams.keys()].some((key) => SECRET_QUERY_KEY.test(key));
}

function isDeploymentEndpoint(value: string): boolean {
  const url = endpointUrl(value);
  if (!url || isM1OwnedUrl(url)) return false;
  const host = url.hostname.toLowerCase();
  if (LOOPBACK_HOST.test(host) || EXAMPLE_HOST.test(host) || DEV_HOST.test(host)) return false;
  if (host.endsWith(".localhost") || host.endsWith(".local") || host.endsWith(".test")) return false;
  if (CANONICAL_PUBLIC_HOSTS.has(host)) return false;
  return ENVIRONMENT_HOST.test(host)
    || PRIVATE_NETWORK_HOST.test(host)
    || PROVIDER_TENANT_HOST.test(host)
    || AWS_GATEWAY_HOST.test(host)
    || /\.(?:corp|internal)$/i.test(host);
}

function isIdentifier(value: string, label: string | undefined): boolean {
  if (!label || !IDENTIFIER_LABEL.test(label) || SECRET_LABEL.test(label)) return false;
  if (PREFIXED_IDENTIFIER.test(value) || PATH_IDENTIFIER.test(value) || UUID.test(value)) return true;
  if (/account/i.test(label) && AWS_ACCOUNT.test(value)) return true;
  return /project/i.test(label)
    && PROJECT_SLUG.test(value)
    && (/\d/.test(value) || /(?:^|-)(?:prod|production|stage|staging)(?:-|$)/i.test(value));
}

function isClientSource(path: string, sf: ts.SourceFile): boolean {
  return leadingDirective(sf) === "use client" || CLIENT_SOURCE_PATH.test(normalizedPath(path));
}

function classifyContext(
  node: ts.StringLiteralLike,
  kind: DeploymentValueKind,
  path: string,
  sf: ts.SourceFile,
): ConsumerContext | undefined {
  const label = propertyLabel(node);
  if (label && SECRET_LABEL.test(label)) return undefined;
  const call = supportedCall(node, sf);
  if (kind === "identifier" && label && TENANT_SENSITIVE_LABEL.test(label)
    && (call?.kind === "request" || isClientSource(path, sf))) return undefined;

  if (call) {
    if (kind === "endpoint") return { ...call, label };
    if (label && IDENTIFIER_LABEL.test(label)) return { ...call, label };
  }

  const config = configContext(node, path, label);
  if (!config) return undefined;
  if (kind === "endpoint" && label && (STRONG_ENDPOINT_LABEL.test(label) || ENDPOINT_LABEL.test(label))) return config;
  if (kind === "identifier" && label && IDENTIFIER_LABEL.test(label)) return config;
  return undefined;
}

function compactConsumer(context: ConsumerContext, sf: ts.SourceFile): string {
  if (ts.isCallExpression(context.node)) return `${context.node.expression.getText(sf)}(…)`;
  if (ts.isNewExpression(context.node)) return `new ${context.node.expression.getText(sf)}(…)`;
  if (ts.isVariableDeclaration(context.node)) return `${context.node.name.getText(sf)} configuration`;
  if (ts.isPropertyAssignment(context.node)) return `${context.node.name.getText(sf)}: …`;
  return context.node.kind === ts.SyntaxKind.StringLiteral ? "literal consumer" : context.kind;
}

function safeValue(value: string, kind: DeploymentValueKind): string {
  if (kind === "endpoint") {
    const url = endpointUrl(value);
    if (!url) return value.slice(0, 100);
    return `${url.origin}${url.pathname}${url.search.length > 0 ? "?…" : ""}`.slice(0, 120);
  }
  if (value.length <= 9) return value;
  return `${value.slice(0, 4)}…${value.slice(-4)}`;
}

function upperSnake(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
}

function expectedSeam(context: ConsumerContext, value: string, kind: DeploymentValueKind): string {
  if (context.label) return upperSnake(context.label);
  if (kind === "endpoint") {
    const hostLabel = endpointUrl(value)?.hostname.split(".")[0];
    if (hostLabel) return `${upperSnake(hostLabel)}_BASE_URL`;
  }
  return kind === "endpoint" ? "SERVICE_BASE_URL" : "PROVIDER_RESOURCE_ID";
}

function findingFor(
  node: ts.StringLiteralLike,
  kind: DeploymentValueKind,
  context: ConsumerContext,
  path: string,
  sf: ts.SourceFile,
): Finding {
  const value = node.text;
  const displayed = safeValue(value, kind);
  const seam = expectedSeam(context, value, kind);
  const endpoint = kind === "endpoint";
  const idStem = endpoint ? "ENDPOINT" : "IDENTIFIER";
  const subject = endpoint ? "deployment endpoint" : "provider identifier";
  return mechanicalFinding({
    id: `M5-HARDCODED-${idStem}-${path.replace(/[^a-zA-Z0-9]+/g, "-")}-${node.getStart(sf)}`,
    title: `${path} — ${subject} is coupled to one environment`,
    severity: "Medium",
    category: "Maintainability",
    taxonomy: endpoint ? M5_HARDCODED_ENDPOINT_TAXONOMY : M5_HARDCODED_IDENTIFIER_TAXONOMY,
    location: loc(path, sf, node),
    evidence: `Literal value \`${displayed}\` is consumed by ${context.kind} node \`${compactConsumer(context, sf)}\`. Expected seam: validated env/config key \`${seam}\`.`,
    impact: "Deployments, tenant copies, or provider projects can silently keep talking to the environment embedded in source.",
    fix: `Move this value behind the validated runtime configuration seam \`${seam}\` and inject it into the same consumer.`,
    precisionTier: "review",
  });
}

interface M5HardcodedDeploymentOptions {
  enabled?: boolean;
}

/**
 * Source-only M5 classifier. It intentionally does not resolve dynamic values or consult provider
 * credentials/live state; the live registry owns applicability and NotAssessed accounting.
 */
export function detectM5HardcodedDeploymentFindings(
  files: readonly SourceInput[],
  options: M5HardcodedDeploymentOptions = {},
): Finding[] {
  if (options.enabled === false) return [];
  const findings: Finding[] = [];
  for (const file of files) {
    if (!isM5HardcodedDeploymentSource(file)) continue;
    const sf = parse(file.path, file.text);
    const visit = (node: ts.Node): void => {
      if (ts.isStringLiteralLike(node)) {
        const label = propertyLabel(node);
        if (!SECRET_LABEL.test(label ?? "")) {
          const kind = isDeploymentEndpoint(node.text)
            ? "endpoint"
            : isIdentifier(node.text, label) ? "identifier" : undefined;
          if (kind) {
            const context = classifyContext(node, kind, file.path, sf);
            if (context) findings.push(findingFor(node, kind, context, file.path, sf));
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(sf);
  }
  return findings;
}
