CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA private;
CREATE SCHEMA pgtenant;
CREATE SCHEMA unselected;
GRANT USAGE ON SCHEMA public, private, pgtenant TO anon, authenticated;
CREATE TABLE public.contacts (email text);
INSERT INTO public.contacts VALUES ('synthetic@example.invalid');
GRANT SELECT ON public.contacts TO anon;
CREATE TABLE private.patient (ssn text, nickname text);
INSERT INTO private.patient VALUES ('synthetic-ssn', 'synthetic');
GRANT SELECT (nickname) ON private.patient TO anon;
CREATE TABLE private.patient_open (ssn text, nickname text);
INSERT INTO private.patient_open VALUES ('synthetic-ssn', 'synthetic');
GRANT SELECT (ssn) ON private.patient_open TO anon;
CREATE TABLE private.patient_rls (ssn text);
INSERT INTO private.patient_rls VALUES ('synthetic-ssn');
GRANT SELECT ON private.patient_rls TO anon, authenticated;
ALTER TABLE private.patient_rls ENABLE ROW LEVEL SECURITY;
CREATE TABLE private.patient_conditional (ssn text, tenant text);
INSERT INTO private.patient_conditional VALUES ('synthetic-a', 'a'), ('synthetic-b', 'b');
GRANT SELECT ON private.patient_conditional TO anon, authenticated;
ALTER TABLE private.patient_conditional ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_read ON private.patient_conditional FOR SELECT TO anon, authenticated USING (tenant = current_setting('fixture.tenant', true));
CREATE VIEW private.patient_view AS SELECT ssn FROM private.patient;
GRANT SELECT ON private.patient_view TO anon;
CREATE TABLE private.encrypted_patient (ssn bytea);
INSERT INTO private.encrypted_patient VALUES (decode('aabbccdd', 'hex'));
GRANT SELECT ON private.encrypted_patient TO anon;
CREATE TABLE pgtenant.customer (ssn text);
INSERT INTO pgtenant.customer VALUES ('synthetic-ssn');
GRANT SELECT ON pgtenant.customer TO anon;
CREATE TABLE unselected.contact (email text);
