// Batch B11 — crypto-API misuse & JWT-verify options (#71, roadmap `docs/design/corpus-roadmap-to-100.md`
// §3c). Extends the EXISTING per-batch rule file src/scan/rules/semgrep/crypto.yml — no new scanner.
// Tiering per the locked preamble: only exact-API / unambiguous-literal sinks are `high` (free
// count) — the no-IV createCipher/createDecipher API, crypto.pseudoRandomBytes(), a 2-arg
// jwt.verify() with no algorithms allowlist, an explicit `ignoreExpiration: true`, and a `ws://`
// WebSocket URL. The absence-of-X / heuristic sinks (GCM decipher with no authTagLength, an AEAD
// decipher returning update() with no final(), an unverified client-side jwtDecode() render sink, a
// hardcoded HMAC key literal) stay `review`. Two adjacencies were kept from double-firing:
// harvey-jwt-decode-render matches only the `jwtDecode()`/`jwt_decode()` client package (the
// server-side jwt.decode() stays with B6's harvey-jwt-decode-noverify), and harvey-hmac-hardcoded-key
// fires on the createHmac literal-key SINK (the gitleaks JWT_SIGNING_SECRET rule catches the secret's
// declaration). See GROUND-TRUTH.md §B11.

import type { CorpusEntry } from "./types.js";

export const b11CryptoEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-CIPHER-NO-IV", kind: "positive", cls: "createCipher/createDecipher (implicit IV)", location: "cipher-noiv.js", match: ["crypto-createcipher", "createcipher"], expectedTier: "high", note: "crypto.createCipher('aes-256-ctr', secret) in lib/cipher-noiv.js — the legacy API derives key+IV from the passphrase (weak KDF, fixed IV per passphrase). harvey-crypto-createcipher (exact-API name; createCipheriv is a different identifier) → high." },
  { id: "P-PSEUDORANDOM-BYTES", kind: "positive", cls: "crypto.pseudoRandomBytes() for a token", location: "pseudorandom.js", match: ["crypto-pseudorandombytes", "pseudorandombytes"], expectedTier: "high", note: "crypto.pseudoRandomBytes(16) minting a reset token in lib/pseudorandom.js — a non-CSPRNG alias, predictable. harvey-crypto-pseudorandombytes (exact-API name; randomBytes is a different identifier) → high." },
  { id: "P-JWT-VERIFY-NOALG", kind: "positive", cls: "jwt.verify() with no algorithms allowlist", location: "jwt-verify-noalg.js", match: ["jwt-verify-noalg"], expectedTier: "high", note: "jwt.verify(token, PUBLIC_KEY) (2-arg, no options) in lib/jwt-verify-noalg.js — RS256/HS256 algorithm-confusion bypass. harvey-jwt-verify-noalg matches the exact 2-arg form; a 3-arg verify with options does not → high." },
  { id: "P-JWT-IGNORE-EXP", kind: "positive", cls: "jwt.verify(..., { ignoreExpiration: true })", location: "jwt-ignore-exp.js", match: ["jwt-ignore-exp"], expectedTier: "high", note: "jwt.verify(t, KEY, { algorithms:['HS256'], ignoreExpiration: true }) in lib/jwt-ignore-exp.js — expired tokens honoured forever. harvey-jwt-ignore-exp (explicit literal `ignoreExpiration: true`) → high." },
  { id: "P-INSECURE-WS-URL", kind: "positive", cls: "Insecure ws:// WebSocket URL", location: "ws-client.js", match: ["insecure-ws-url"], expectedTier: "high", note: "new WebSocket('ws://feed.internal.example.com/stream') in lib/ws-client.js — plaintext transport. harvey-insecure-ws-url (URL metavariable anchored to ^ws://; wss:// does not match) → high." },

  // #595 (SuperRedHat F-09) — the sign-side companion of harvey-jwt-verify-noalg: a session token
  // minted with no expiry. jwt.sign(claims, secret) (2-arg, no options) or a 3-arg inline-options
  // literal with no expiresIn key.
  { id: "P-JWT-SIGN-NOEXPIRY", kind: "positive", cls: "jwt.sign() with no expiresIn (token never expires)", location: "jwt-signing.ts", match: ["jwt-sign-noexpiry"], expectedTier: "review", note: "#595 F-09: lib/jwt-signing.ts signSession() calls jwt.sign(claims, JWT_SECRET) with no options object, so no expiresIn — the token never expires and can't be revoked by time. harvey-jwt-sign-noexpiry (2-arg form, or a 3-arg inline options literal lacking expiresIn via pattern-not; a variable options arg is not flagged) → review. Distinct facet of F-09 from the verify-side harvey-jwt-verify-noalg." },
  { id: "N-JWT-SIGN-EXPIRY", kind: "negative", cls: "jwt.sign() WITH expiresIn", location: "jwt-signing-safe.ts", match: ["jwt-sign-noexpiry"], note: "#595: lib/jwt-signing-safe.ts calls jwt.sign(claims, secret, { expiresIn: '15m' }) — harvey-jwt-sign-noexpiry's pattern-not excludes the inline options literal carrying expiresIn, so it is cleared. Regression guard: the rule fires only on the missing-expiry case." },

  { id: "P-GCM-NO-TAGLEN", kind: "positive", cls: "AES-GCM decipher with no authTagLength", location: "gcm-notag.js", match: ["gcm-no-authtaglength"], expectedTier: "review", note: "crypto.createDecipheriv('aes-256-gcm', key, iv) (3-arg, no options) in lib/gcm-notag.js — auth-tag length not pinned. harvey-gcm-no-authtaglength matches the 3-arg GCM decipher; the 4-arg options form does not. Heuristic (default 16 is often fine) → review." },
  { id: "P-AEAD-NO-FINAL", kind: "positive", cls: "AEAD decipher with no .final() tag check", location: "aead-nofinal.js", match: ["aead-decipher-no-final"], expectedTier: "review", note: "an aes-256-gcm decipher that `return decipher.update(...)` with no decipher.final() in lib/aead-nofinal.js — the tag is never verified. harvey-aead-decipher-no-final (returns update() directly, GCM/CCM/ChaCha20-Poly1305/OCB algo). Heuristic → review." },
  { id: "P-JWT-DECODE-RENDER", kind: "positive", cls: "Unverified client jwtDecode() render/authz sink", location: "components/RoleBadge.jsx", match: ["jwt-decode-render"], expectedTier: "review", note: "const { role } = jwtDecode(token) driving an admin render in components/RoleBadge.jsx — forgeable, no signature check. harvey-jwt-decode-render matches jwtDecode()/jwt_decode() (the client `jwt-decode` package), adjacent to B6's harvey-jwt-decode-noverify (server jwt.decode()). Heuristic → review." },
  { id: "P-HMAC-HARDCODED-KEY", kind: "positive", cls: "Hardcoded key literal to createHmac", location: "sign.js", match: ["hmac-hardcoded-key"], expectedTier: "review", note: "crypto.createHmac('sha256', 's3cr3t-…') in lib/sign.js — a committed literal MAC key, forgeable. harvey-hmac-hardcoded-key gates on a string-literal key arg (a process.env key does not match). Could be a public/test constant → review." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-CIPHER-IV-OK", kind: "negative", cls: "createCipheriv with a random IV", location: "cipher-iv.js", note: "createCipheriv('aes-256-ctr', key, crypto.randomBytes(16)) in lib/cipher-iv.js — the correct IV-taking API. harvey-crypto-createcipher matches only createCipher/createDecipher (no trailing 'iv'); the aes-256-ctr algorithm is not weak, so harvey-weak-cipher stays silent too — cleared." },
  { id: "N-RANDOMBYTES-OK", kind: "negative", cls: "crypto.randomBytes for a token", location: "randombytes.js", note: "crypto.randomBytes(16).toString('hex') in lib/randombytes.js — the CSPRNG. harvey-crypto-pseudorandombytes matches only the pseudoRandomBytes alias — cleared." },
  { id: "N-JWT-VERIFY-ALGS", kind: "negative", cls: "jwt.verify with a pinned algorithms allowlist", location: "jwt-verify-checked.js", note: "jwt.verify(t, KEY, { algorithms:['HS256'], issuer:'harvey' }) in lib/jwt-verify-checked.js — the safe counterpart for BOTH JWT-verify-option classes. harvey-jwt-verify-noalg fires only on the 2-arg form; harvey-jwt-ignore-exp needs `ignoreExpiration: true` (absent) — both cleared." },
  { id: "N-WSS-SECURE", kind: "negative", cls: "wss:// (TLS) WebSocket URL", location: "ws-secure.js", note: "new WebSocket('wss://feed.internal.example.com/stream') in lib/ws-secure.js. harvey-insecure-ws-url is anchored to ^ws://; the extra 's' of wss:// does not match — cleared." },
  { id: "N-GCM-TAGLEN-OK", kind: "negative", cls: "GCM decipher with authTagLength + final()", location: "gcm-tag.js", note: "createDecipheriv('aes-256-gcm', key, iv, { authTagLength: 16 }) then setAuthTag + .final() in lib/gcm-tag.js — the safe counterpart for BOTH AEAD classes. harvey-gcm-no-authtaglength fires only on the 3-arg form; harvey-aead-decipher-no-final fires only when update() is returned with no final() — both cleared." },
  { id: "N-JWTDECODE-SERVER", kind: "negative", cls: "Role from a server-verified session prop", location: "RoleBadgeSafe.jsx", note: "session.role (a signature-verified server session prop), no jwtDecode() call, in components/RoleBadgeSafe.jsx. harvey-jwt-decode-render has no jwtDecode()/jwt_decode() to match — cleared." },
  { id: "N-HMAC-KEY-ENV", kind: "negative", cls: "createHmac keyed from the environment", location: "sign-env.js", note: "crypto.createHmac('sha256', process.env.HMAC_SIGNING_KEY) in lib/sign-env.js. harvey-hmac-hardcoded-key's key regex matches a string literal only, not a process.env read — cleared." },
];
