// Batch B12 — Next-config & client-surface misconfig (#71, roadmap `docs/design/corpus-roadmap-to-100.md`
// §3d). Detection is split three ways: three exact config-object Semgrep rules and two review-tier
// server rules EXTEND src/scan/rules/semgrep/headers.yml; four client-surface rules EXTEND
// src/scan/rules/semgrep/xss.yml; and the one class Semgrep can't express — a sensitive file
// physically served from public/ — is a new filesystem check (checkPublicDirSensitive in
// src/scan/semgrep.ts, wired into runMechanicalScan). Tiering per the locked preamble: only the
// exact config-parse / unambiguous-literal sinks are `high` (free count) — the wildcard
// remotePatterns hostname, productionBrowserSourceMaps:true, the '*' Server-Actions origin, an
// excessive createSignedUrl TTL, a '*' postMessage targetOrigin, and a sensitive file in public/.
// The heuristic / absence-of-X sinks (auth token in Web Storage, a CDN script with no SRI, an ISR
// revalidate with no secret, CRLF into a response header, a 'message' listener with no origin
// check) stay `review`. All fixtures are inert source files. See GROUND-TRUTH.md §B12.
//
// P-SIGNED-URL-TTL is the numeric-literal-TTL lens (createSignedUrl expiry), distinct from B9's
// P-SIGNED-URL-TOKEN-SRC (a committed signed-URL token, a gitleaks value match) — different file,
// different mechanism, no double-fire.

import type { CorpusEntry } from "./types.js";

export const b12NextconfigEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-IMG-REMOTEPATTERNS-WILD", kind: "positive", cls: "next/image remotePatterns wildcard hostname (SSRF)", location: "config-variants/insecure.config.js", match: ["img-remotepatterns-wild"], expectedTier: "high", note: "images.remotePatterns [{ hostname: '**' }] in config-variants/insecure.config.js — the optimizer becomes an open image proxy / SSRF fetcher. Semgrep harvey-img-remotepatterns-wild (all-asterisks hostname literal inside a remotePatterns element; an explicit host or '*.example.com' does not match) → high." },
  { id: "P-PROD-SOURCEMAPS", kind: "positive", cls: "productionBrowserSourceMaps ships readable source", location: "config-variants/insecure.config.js", match: ["prod-sourcemaps"], expectedTier: "high", note: "productionBrowserSourceMaps: true in config-variants/insecure.config.js ships original client source to every browser. Semgrep harvey-prod-sourcemaps (exact literal `true`; false/absent does not match) → high." },
  { id: "P-SERVERACTIONS-ORIGIN-WILD", kind: "positive", cls: "Server Actions allowedOrigins ['*'] (CSRF)", location: "config-variants/insecure.config.js", match: ["serveractions-origin-wild"], expectedTier: "high", note: "experimental.serverActions.allowedOrigins ['*'] in config-variants/insecure.config.js disables the Server-Actions origin allowlist. Semgrep harvey-serveractions-origin-wild (bare '*' array element; an explicit host list does not match) → high." },
  { id: "P-PUBLIC-DIR-SENSITIVE", kind: "positive", cls: "Sensitive/dev file served from public/", location: "public/backup.sql", match: ["sensitive file in public"], expectedTier: "high", note: "public/backup.sql (and public/.env.production) are served verbatim at the site root. checkPublicDirSensitive (filesystem walk of public/, src/scan/semgrep.ts — a presence fact no Semgrep AST rule can express) → high. Benign assets (favicon, fonts, robots.txt) don't match." },
  { id: "P-SIGNED-URL-TTL", kind: "positive", cls: "createSignedUrl excessive expiry (numeric literal)", location: "lib/signed-url-ttl.js", match: ["signed-url-ttl"], expectedTier: "high", note: "createSignedUrl(path, 31536000) (1 year) in lib/signed-url-ttl.js — effectively a permanent public link. Semgrep harvey-signed-url-ttl (metavariable-comparison: literal TTL > 7 days; a short TTL like 300 does not match) → high. Distinct from B9's P-SIGNED-URL-TOKEN-SRC (committed token)." },
  { id: "P-POSTMESSAGE-WILDCARD", kind: "positive", cls: "postMessage(data, '*') leaks cross-origin", location: "components/PostMessageWild.jsx", match: ["postmessage-wildcard", "postmessage to any origin"], expectedTier: "high", note: "window.parent.postMessage(session, '*') in components/PostMessageWild.jsx — the session payload goes to any framing site. Semgrep harvey-postmessage-wildcard (literal '*' targetOrigin; an explicit origin does not match) → high. #996 RE-TIERED the grading, not the detection: the '*' is exact but the DATA's sensitivity is a semantic judgment (this fixture broadcasts a session — the genuinely-bad case — but the common real shape is benign player/embed plumbing, and the rule cannot tell them apart), so the finding is still high tier (this entry keeps proving detection) and routes to the free report's NON-GRADING informational section via harveyTaxonomy; the paid LLM pass makes the sensitivity call. Grading routing pinned in src/quick-scan.test.ts." },

  { id: "P-TOKEN-IN-WEBSTORAGE", kind: "positive", cls: "Auth token in Web Storage (XSS-readable)", location: "lib/webstorage-token.js", match: ["token-in-webstorage"], expectedTier: "review", note: "localStorage.setItem('authToken', token) in lib/webstorage-token.js — readable by any injected script. Semgrep harvey-token-in-webstorage (key name-gated on auth/access/refresh/id/jwt/bearer/session token; 'csrfToken' is excluded). Heuristic → review." },
  { id: "P-MISSING-SRI", kind: "positive", cls: "Third-party CDN <script> without SRI", location: "components/CdnScript.jsx", match: ["missing-sri"], expectedTier: "review", note: "<script src='https://cdn.example.com/...'> with no integrity attribute in components/CdnScript.jsx. Semgrep harvey-missing-sri (external http(s) src, no integrity; a first-party/relative src or one with integrity does not match). Heuristic → review." },
  { id: "P-ISR-REVALIDATE-NOSECRET", kind: "positive", cls: "On-demand ISR revalidate with no secret", location: "pages/api/isr-rebuild.js", match: ["isr-revalidate-nosecret"], expectedTier: "review", note: "res.revalidate(req.query.path) with no secret gate in pages/api/isr-rebuild.js — anyone can force cache rebuilds. Semgrep harvey-isr-revalidate-nosecret (handler doesn't compare req.query.secret; a secret-gated handler is excluded). Heuristic → review. (File named isr-rebuild*.js, not *revalidate*.js, so its path doesn't collide with the base corpus's validate.js location.)" },
  { id: "P-CRLF-HEADER-INJ", kind: "positive", cls: "CRLF header injection via untrusted setHeader value", location: "pages/api/download.js", match: ["crlf-header-injection"], expectedTier: "review", note: "res.setHeader('Content-Disposition', `...${req.query.name}`) in pages/api/download.js — CR/LF in the value injects headers / splits the response. Semgrep harvey-crlf-header-injection (taint req.query → res.setHeader value; a .replace CR/LF strip is the sanitizer). Heuristic → review." },
  { id: "P-CRLF-MULTIHOP", kind: "positive", cls: "CRLF header injection via multi-hop req.headers source", location: "pages/api/crlf-multihop.js", match: ["crlf-header-injection"], expectedTier: "review", note: "#988: const raw = req.headers.referer; const dest = String(raw); res.setHeader('X-Redirect-From', dest) in pages/api/crlf-multihop.js — a multi-hop source through dotted req.headers access, the shape the old rule missed (0% on BenchProctor). harvey-crlf-header-injection now sources req.params / dotted req.headers.$H / bare req.body → review." },
  { id: "P-CRLF-SEARCHPARAMS", kind: "positive", cls: "CRLF header injection via an App Router searchParams value", location: "ar-crlf-search/route", match: ["harvey-crlf-header-injection"], expectedTier: "review", expectedSeverity: "Medium", note: "#1224: app/api/ar-crlf-search/route.ts puts `new URL(request.url).searchParams.get('name')` straight into a Content-Disposition header. The rule modelled req.query/body/params/headers but neither searchParams nor the JSON body. #1224 judgment: adopt the canonical block wholesale — every attacker-controlled STRING is in class for this sink, so there was nothing to weigh. It also NARROWED the rule, whose free `$REQ.` metavariable had made `upstream.headers.etag` a source: a recall and a precision gain in one change. → review." },
  { id: "P-POSTMESSAGE-NO-ORIGIN", kind: "positive", cls: "'message' listener with no origin validation", location: "components/MessageListener.jsx", match: ["postmessage-no-origin"], expectedTier: "review", note: "window.addEventListener('message', e => setTheme(e.data.theme)) with no e.origin check in components/MessageListener.jsx. Semgrep harvey-postmessage-no-origin (callback has no .origin reference; an origin-checked callback is excluded). Heuristic → review." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-IMG-REMOTEPATTERNS-OK", kind: "negative", cls: "remotePatterns pinned to an explicit host", location: "config-variants/hardened.config.js", match: ["img-remotepatterns-wild"], note: "images.remotePatterns [{ hostname: 'images.example.com' }] in config-variants/hardened.config.js — an explicit host, not an all-asterisks wildcard. harvey-img-remotepatterns-wild's hostname regex (^['\"]?\\*+['\"]?$) doesn't match — cleared." },
  { id: "N-PROD-SOURCEMAPS-OFF", kind: "negative", cls: "productionBrowserSourceMaps false", location: "config-variants/hardened.config.js", match: ["prod-sourcemaps"], note: "productionBrowserSourceMaps: false in config-variants/hardened.config.js (also the absent-key default). harvey-prod-sourcemaps matches only the literal `true` — cleared." },
  { id: "N-SERVERACTIONS-ORIGIN-OK", kind: "negative", cls: "Server Actions allowedOrigins explicit hosts", location: "config-variants/hardened.config.js", match: ["serveractions-origin-wild"], note: "allowedOrigins ['app.example.com','admin.example.com'] in config-variants/hardened.config.js — no bare '*' element for harvey-serveractions-origin-wild to match — cleared." },
  { id: "N-PUBLIC-DIR-BENIGN", kind: "negative", cls: "Only benign assets under public/", location: "public/favicon.ico", note: "public/favicon.ico, public/fonts/inter.woff2, public/robots.txt are benign web assets. checkPublicDirSensitive's sensitive-name patterns don't match any of them — no finding at this location, cleared." },
  { id: "N-SIGNED-URL-TTL-OK", kind: "negative", cls: "createSignedUrl short TTL", location: "lib/signed-url-ttl-ok.js", note: "createSignedUrl(path, 300) (5 min) in lib/signed-url-ttl-ok.js. harvey-signed-url-ttl fires only when the literal TTL exceeds a week (metavariable-comparison $N > 604800) — cleared." },
  { id: "N-POSTMESSAGE-ORIGIN-OK", kind: "negative", cls: "postMessage pinned to an explicit origin", location: "components/PostMessageOrigin.jsx", note: "window.parent.postMessage(session, 'https://app.example.com') in components/PostMessageOrigin.jsx. harvey-postmessage-wildcard matches only the literal '*' targetOrigin — cleared." },
  { id: "N-WEBSTORAGE-CSRF", kind: "negative", cls: "CSRF token in Web Storage (readable by design)", location: "lib/webstorage-csrf.js", note: "localStorage.setItem('csrfToken', csrfToken) in lib/webstorage-csrf.js — a CSRF token is JS-readable by design. harvey-token-in-webstorage's name regex excludes 'csrf'-prefixed keys — cleared." },
  { id: "N-SRI-PRESENT", kind: "negative", cls: "CDN <script> pinned with SRI + crossOrigin", location: "components/CdnScriptSri.jsx", note: "<script src='https://cdn.example.com/...' integrity='sha384-…' crossOrigin='anonymous'> in components/CdnScriptSri.jsx. harvey-missing-sri excludes any <script> carrying an integrity attribute — cleared." },
  { id: "N-ISR-REVALIDATE-SECRET", kind: "negative", cls: "ISR revalidate gated by a secret token", location: "pages/api/isr-rebuild-secret.js", note: "handler compares req.query.secret against process.env.REVALIDATE_SECRET before revalidating, in pages/api/isr-rebuild-secret.js. harvey-isr-revalidate-nosecret's pattern-not-inside excludes any handler that checks req.query.secret — cleared." },
  { id: "N-CRLF-SANITIZED", kind: "negative", cls: "CRLF stripped before the header is set", location: "pages/api/download-safe.js", note: "req.query.name.replace(/[\\r\\n\"]/g,'') before res.setHeader, in pages/api/download-safe.js. harvey-crlf-header-injection treats the CR/LF strip as a sanitizer — the tainted value never reaches the sink — cleared." },
  { id: "N-POSTMESSAGE-NO-ORIGIN-OK", kind: "negative", cls: "'message' listener validates event.origin", location: "components/MessageListenerOrigin.jsx", note: "the listener checks e.origin against an allowlisted host before trusting e.data, in components/MessageListenerOrigin.jsx. harvey-postmessage-no-origin excludes any callback that references .origin — cleared." },
];
