// Batch B13 (#71) — Supabase static-config/edge + injection-sink breadth (roadmap
// `docs/design/corpus-roadmap-to-100.md` §3e). Detection is split three ways:
//   - ONE new static scanner, `checkMigrationRlsStatic` (src/scan/supabase-static.ts, wired into
//     runMechanicalScan): parses committed supabase/migrations/*.sql for a `create table public.X`
//     that never gets `enable row level security` anywhere — the static path for P-RLS-DISABLED,
//     which was connected-tier only. HIGH (the honesty-flag class, roadmap §5): it fires ONLY on
//     audit_logs and stays silent on service_state (RLS enabled + zero policies, deny-all by
//     design) and on documents (RLS enabled in a LATER migration file) — both verified negatives.
//   - a small static config check, `checkEdgeFunctionVerifyJwt` (same module): parses
//     supabase/config.toml for `[functions.X] verify_jwt = false`. Review.
//   - the rest EXTEND src/scan/rules/semgrep/injection.yml: two ERROR+HIGH structural rules
//     (spawn/execFile shell:true; pg Pool ssl:false to a pooler host), one ERROR+HIGH client rule
//     (auth.admin.* in a "use client" Component), and six WARNING+MEDIUM injection-sink heuristics.
//
// Adjacency (kept from double-firing): P-SPAWN-SHELL is spawn/execFile{shell:true}, disjoint from
// harvey-command-injection (exec/execSync); P-AUTH-ADMIN-CLIENT keys off the auth.admin call, not the
// SERVICE_ROLE_KEY env literal harvey-service-role-in-client (base.yml) matches, and its fixture never
// writes that literal. P-RLS-MISSING-STATIC is the static counterpart of the existing connected
// P-RLS-DISABLED (base.entries.ts, audit_logs); both coexist (one high/static, one connected/N/A).
//
// See GROUND-TRUTH.md §B13. Dropped: none — all 12 §3e rows landed.

import type { CorpusEntry } from "./types.js";

export const b13SupaEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-RLS-MISSING-STATIC", kind: "positive", cls: "public table never gets ENABLE RLS (read statically from migrations)", location: "20260708000001_schema.sql", match: ["audit_logs"], expectedTier: "high", note: "create table public.audit_logs (migrations/…0001_schema.sql:35) has no matching `enable row level security` anywhere in supabase/migrations/. checkMigrationRlsStatic (src/scan/supabase-static.ts) aggregates enables across ALL migration files, so it clears documents (enabled in the LATER …0002_rls.sql) and service_state (RLS on, zero policies) — audit_logs is the only table left with RLS off → high. Static path for the connected-tier P-RLS-DISABLED." },
  { id: "P-PG-SSL-DISABLED", kind: "positive", cls: "pg Pool ssl:false to a Supabase pooler host", location: "lib/pg-ssl-disabled.js", match: ["harvey-pg-ssl-disabled"], expectedTier: "high", note: "new Pool({ connectionString: '…@aws-0-us-east-1.pooler.supabase.com…', ssl: false }) in lib/pg-ssl-disabled.js. Semgrep harvey-pg-ssl-disabled (ssl:false in a Pool literal AND a pooler.supabase.com host via pattern-regex) → high. Negative uses ssl:{rejectUnauthorized:true}." },
  { id: "P-AUTH-ADMIN-CLIENT", kind: "positive", cls: "auth.admin.* reachable from a Client Component", location: "components/AdminUsersClient.jsx", match: ["auth-admin-in-client"], expectedTier: "high", note: "'use client' + supabaseAdmin.auth.admin.listUsers() in components/AdminUsersClient.jsx. Semgrep harvey-auth-admin-in-client ($C.auth.admin.$M(...) inside a \"use client\" module) → high. Broader than harvey-service-role-in-client (base.yml, SERVICE_ROLE_KEY env literal); the fixture never writes that literal, so no double-fire." },
  { id: "P-SPAWN-SHELL", kind: "positive", cls: "spawn/execFile with { shell: true }", location: "pages/api/thumbnail.js", match: ["spawn-shell-true"], expectedTier: "high", note: "spawn('convert', [req.query.file, …], { shell: true }) in pages/api/thumbnail.js — shell:true re-parses the argv array through /bin/sh. Semgrep harvey-spawn-shell-true → high. Disjoint from harvey-command-injection (exec/execSync); the argv-array negative (execFile, no shell) clears." },

  { id: "P-EDGEFN-VERIFY-JWT-OFF", kind: "positive", cls: "Edge Function verify_jwt=false", location: "supabase/config.toml", match: ["verify_jwt", "admin-refund", "verifyjwt"], expectedTier: "review", note: "[functions.admin-refund] verify_jwt = false in supabase/config.toml — the endpoint is callable with no valid JWT. checkEdgeFunctionVerifyJwt (src/scan/supabase-static.ts) → review. The [functions.user-profile] verify_jwt = true negative in the same file is cleared (the check matches only `= false` under a [functions.X] table)." },
  { id: "P-SELECT-STAR-PII", kind: "positive", cls: "select('*') spread into an API response", location: "pages/api/customers.js", match: ["select-star-pii"], expectedTier: "review", note: "supabase.from('customers').select('*') returned via res.json(data) in pages/api/customers.js. Semgrep harvey-select-star-pii (taint select('*') → res.json/NextResponse.json) → review. Distinct from harvey-server-client-leak (auth.yml, a JSX-spread sink). Negative projects an explicit column list." },
  { id: "P-CRON-NO-SECRET", kind: "positive", cls: "service-role cron endpoint with no caller secret", location: "pages/api/cron/rollup.js", match: ["cron-no-secret"], expectedTier: "review", note: "pages/api/cron/rollup.js calls supabaseAdmin.from(...) in a handler with no preflight guard. Semgrep harvey-cron-no-secret (supabaseAdmin DB call, pattern-not-inside a handler carrying an `if` guard) → review. The CRON_SECRET-checked negative (rollup-secure.js) is excluded." },
  { id: "P-DYNAMIC-REQUIRE", kind: "positive", cls: "require() with a request-tainted arg", location: "pages/api/plugin.js", match: ["dynamic-require"], expectedTier: "review", note: "require(req.query.module) in pages/api/plugin.js. Semgrep harvey-dynamic-require (taint req.* → require) → review. The fixed-string require negative (lib/fixed-require.js) is untainted, cleared." },
  { id: "P-DYNAMIC-DISPATCH", kind: "positive", cls: "obj[userInput]() dynamic method dispatch", location: "pages/api/dispatch.js", match: ["dynamic-dispatch"], expectedTier: "review", note: "actions[req.body.action](req.body.payload) in pages/api/dispatch.js. Semgrep harvey-dynamic-dispatch (taint req.* → computed-member call $OBJ[$IDX](...)) → review. The allowlist-checked negative (dispatch-safe.js) clears — no tainted key reaches the computed call." },
  { id: "P-CLIENT-URL-DYNAMIC-DISPATCH", kind: "positive", cls: "Client URL parameter selects a computed method", location: "client-url-source/dynamic-dispatch-client.ts", match: ["harvey-dynamic-dispatch"], expectedTier: "review", expectedSeverity: "Medium", note: "#1708: a receiver-bound useSearchParams value selects actions[key](). harvey-dynamic-dispatch keeps its existing id and Medium/review band because the same arbitrary-property dispatch risk applies on both sides of the boundary." },
  { id: "P-TEMPLATE-AUTOESCAPE-OFF", kind: "positive", cls: "template engine autoescape off", location: "lib/render-template.js", match: ["template-autoescape-off"], expectedTier: "review", note: "Handlebars.compile(tpl, { noEscape: true }) in lib/render-template.js — autoescaping off makes every interpolation an XSS sink. Semgrep harvey-template-autoescape-off → review. The default-escaping negative (render-template-safe.js) has no noEscape option, cleared." },
  { id: "P-HTML-TEMPLATE-LITERAL", kind: "positive", cls: "HTML template literal into res.send", location: "pages/api/greet.js", match: ["html-template-literal"], expectedTier: "review", note: "res.send(`<h1>Hello ${req.query.name}</h1>`) in pages/api/greet.js — reflected XSS. Semgrep harvey-html-template-literal (taint req.* → res.send of a template literal) → review. The plain-JSON negative (greet-safe.js) has no res.send template-literal sink, cleared." },
  { id: "P-INCOMPLETE-SANITIZE", kind: "positive", cls: "non-global .replace() used as a sanitizer", location: "lib/sanitize-bad.js", match: ["incomplete-sanitize"], expectedTier: "review", note: "s.replace('<','').replace('>','') in lib/sanitize-bad.js — a string-literal needle replaces only the first match. Semgrep harvey-incomplete-sanitize (string-literal needle via metavariable-regex) → review. The /g-regex negative (sanitize-ok.js) has a regex needle, not a string, cleared." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-RLS-DENY-ALL-STATIC", kind: "negative", cls: "service-only table, RLS enabled + zero policies (deny-all)", location: "20260708000001_schema.sql", match: ["service_state"], note: "public.service_state (created in …0001_schema.sql) gets `enable row level security` in …0002_rls.sql with zero policies — deny-all by design, not RLS-off. checkMigrationRlsStatic sees the ENABLE and stays silent — no finding mentions service_state. Contrast P-RLS-MISSING-STATIC (audit_logs)." },
  { id: "N-RLS-ENABLED-LATER", kind: "negative", cls: "table whose RLS is enabled in a later migration file", location: "20260708000001_schema.sql", match: ["documents"], note: "public.documents (created in …0001_schema.sql) gets `enable row level security` in the LATER …0002_rls.sql. checkMigrationRlsStatic aggregates enables across all migration files, so documents is cleared — the honesty-flag's cross-file negative." },
  { id: "N-PG-SSL-OK", kind: "negative", cls: "pg Pool to a pooler host with TLS verification on", location: "lib/pg-ssl-ok.js", match: ["pg-ssl-disabled"], note: "new Pool({ …pooler.supabase.com…, ssl: { rejectUnauthorized: true } }) in lib/pg-ssl-ok.js. harvey-pg-ssl-disabled matches only `ssl: false` — cleared." },
  { id: "N-AUTH-ADMIN-SERVER", kind: "negative", cls: "auth.admin.* in a server-only module", location: "lib/admin-users-server.js", match: ["auth-admin-in-client"], note: "the same supabaseAdmin.auth.admin.listUsers() in lib/admin-users-server.js, a server-only module with no \"use client\". harvey-auth-admin-in-client fires only inside a Client Component — cleared." },
  { id: "N-AUTH-ADMIN-ANON-CLIENT", kind: "negative", cls: "auth.admin.* called on the anon client in a Client Component", location: "contexts/AuthContext.jsx", match: ["auth-admin-in-client"], note: "'use client' + supabase.auth.admin.deleteUser() in contexts/AuthContext.jsx, where `supabase` (utils/supabase.js) is the anon/publishable-key client, not service-role — a broken no-op call at runtime, not a key exposure. harvey-auth-admin-in-client now requires the client identifier to read as admin/service-role (/admin|service/i); \"supabase\" doesn't match — cleared (#164)." },
  { id: "N-SPAWN-NOSHELL", kind: "negative", cls: "execFile with an argv array, no shell", location: "pages/api/thumbnail-safe.js", match: ["spawn-shell-true"], note: "execFile('convert', [req.query.file, …], cb) in pages/api/thumbnail-safe.js — argv array, no shell option. harvey-spawn-shell-true requires shell:true — cleared." },
  { id: "N-EDGEFN-VERIFY-JWT-ON", kind: "negative", cls: "Edge Function verify_jwt=true", location: "supabase/config.toml", match: ["user-profile"], note: "[functions.user-profile] verify_jwt = true in supabase/config.toml. checkEdgeFunctionVerifyJwt matches only `verify_jwt = false` under a [functions.X] table — cleared. (Matched by function name so the admin-refund positive at the same location doesn't attribute here.)" },
  { id: "N-SELECT-EXPLICIT", kind: "negative", cls: "explicit column projection into an API response", location: "pages/api/customers-safe.js", match: ["select-star-pii"], note: "supabase.from('customers').select('id,name,email') → res.json in pages/api/customers-safe.js. harvey-select-star-pii requires a select('*') source — cleared." },
  { id: "N-CRON-SECRET", kind: "negative", cls: "cron endpoint gated by a CRON_SECRET check", location: "pages/api/cron/rollup-secure.js", match: ["cron-no-secret"], note: "pages/api/cron/rollup-secure.js checks Authorization against CRON_SECRET (an `if` guard) before the supabaseAdmin call. harvey-cron-no-secret's pattern-not-inside excludes a handler carrying a guard block — cleared." },
  { id: "N-REQUIRE-FIXED", kind: "negative", cls: "require() of a fixed string literal", location: "lib/fixed-require.js", match: ["dynamic-require"], note: "require('./helper') in lib/fixed-require.js — no request taint. harvey-dynamic-require needs a tainted argument — cleared." },
  { id: "N-DISPATCH-ALLOWLIST", kind: "negative", cls: "dispatch checked against an allowlist", location: "pages/api/dispatch-safe.js", match: ["dynamic-dispatch"], note: "pages/api/dispatch-safe.js checks the action name against an explicit allowlist and dispatches a fixed reference — no tainted key reaches a computed call. harvey-dynamic-dispatch is cleared." },
  { id: "N-CLIENT-URL-DISPATCH-ALLOWLIST", kind: "negative", cls: "Client URL dispatch resolved through an explicit allowlist", location: "client-url-source/dynamic-dispatch-client-safe.ts", note: "#1708: a real client URL source is accepted only for preview/download and then mapped to a fixed function reference. This is the client-side twin of N-DISPATCH-ALLOWLIST and must stay clear after the source widening." },
  { id: "N-CLIENT-URL-DISPATCH-MAP-GET", kind: "negative", cls: "A configuration Map.get() is not a client URL dispatch source", location: "client-url-source/dynamic-dispatch-map-get-negative.ts", note: "#1708: a plain Map.get() value reaches actions[key](), with no request, URL or DOM source in the module. It pairs the newly widened dynamic-dispatch sink with the receiver-binding invariant so a bare $SP.get(...) source cannot reappear." },
  { id: "N-TEMPLATE-ESCAPED", kind: "negative", cls: "template engine with default escaping", location: "lib/render-template-safe.js", match: ["template-autoescape-off"], note: "Handlebars.compile(tpl) in lib/render-template-safe.js — no noEscape option, HTML escaping stays on. harvey-template-autoescape-off is cleared." },
  { id: "N-HTML-PLAINTEXT", kind: "negative", cls: "request value returned as plain JSON, not HTML", location: "pages/api/greet-safe.js", match: ["html-template-literal"], note: "res.json({ name: req.query.name }) in pages/api/greet-safe.js — no res.send HTML template literal. harvey-html-template-literal is cleared." },
  { id: "N-SANITIZE-GLOBAL", kind: "negative", cls: "global-regex .replace() sanitizer", location: "lib/sanitize-ok.js", match: ["incomplete-sanitize"], note: "s.replace(/</g,'').replace(/>/g,'') in lib/sanitize-ok.js — a /g regex needle strips every match. harvey-incomplete-sanitize's metavariable-regex requires a quoted string needle — cleared." },

  // #565 — Vite/no-code (Lovable/Bolt/v0) M1 shapes: a service-role key inlined via import.meta.env.
  // VITE_*, a browser LLM client (dangerouslyAllowBrowser), and an RLS-off table read from a root
  // schema.sql (checkMigrationRlsStatic broadened past supabase/migrations-only).
  { id: "P-VITE-SERVICE-ROLE-CLIENT", kind: "positive", cls: "service-role key via import.meta.env.VITE_* in client code", location: "src/lib/supabaseServiceClient.ts", match: ["vite-service-role"], expectedTier: "high", note: "#565: src/lib/supabaseServiceClient.ts passes import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY to createClient — Vite inlines every VITE_-prefixed var into the browser bundle, so the service-role key ships to every visitor (full RLS bypass). Semgrep harvey-vite-service-role-in-client (import.meta.env.$K with $K matching VITE_*SERVICE_ROLE*) → high (Critical). The Vite counterpart of harvey-service-role-in-client (process.env + 'use client'). nocode-rescue #1." },
  { id: "P-DANGEROUSLY-ALLOW-BROWSER", kind: "positive", cls: "browser LLM client (dangerouslyAllowBrowser: true)", location: "src/lib/openaiBrowser.ts", match: ["dangerously-allow-browser"], expectedTier: "high", note: "#565: src/lib/openaiBrowser.ts constructs new OpenAI({ …, dangerouslyAllowBrowser: true }) with the key from import.meta.env.VITE_OPENAI_API_KEY — the SDK requires that flag to run client-side precisely because it exposes the key to every visitor. Semgrep harvey-dangerously-allow-browser → high. nocode-rescue #2 (browser LLM key in the bundle)." },
  { id: "P-RLS-MISSING-ROOT-SCHEMA", kind: "positive", cls: "public table with RLS off, read from a root schema.sql (no-code export)", location: "schema.sql", match: ["nocode_tickets"], expectedTier: "high", note: "#565: schema.sql (a Table-Editor/no-code export commits its schema as a single root schema.sql, not supabase/migrations/*.sql) creates public.nocode_tickets with no `enable row level security` anywhere — auto-exposed via PostgREST. checkMigrationRlsStatic was migrations-only (returned [] with no supabase/migrations); #565 broadened it to also read a root schema.sql → high (Critical). nocode-rescue #3." },

  // --- NEGATIVES (#565) ---
  { id: "N-VITE-ANON-CLIENT", kind: "negative", cls: "anon/publishable key via import.meta.env.VITE_* (intended)", location: "src/lib/supabaseAnonClient.ts", match: ["vite-service-role"], note: "#565: src/lib/supabaseAnonClient.ts reads import.meta.env.VITE_SUPABASE_ANON_KEY — the anon/publishable key is DESIGNED to ship to the browser (RLS-protected), so this is the correct Vite shape. harvey-vite-service-role-in-client is scoped by metavariable-regex to a SERVICE_ROLE/SERVICE_KEY name; the anon key name doesn't match — cleared." },
  { id: "N-OPENAI-SERVER", kind: "negative", cls: "server-side LLM client, no dangerouslyAllowBrowser", location: "src/lib/openaiServer.ts", match: ["dangerously-allow-browser"], note: "#565: src/lib/openaiServer.ts constructs new OpenAI({ apiKey: process.env.OPENAI_API_KEY }) with no dangerouslyAllowBrowser flag — the key stays server-only. harvey-dangerously-allow-browser matches only the `dangerouslyAllowBrowser: true` literal — cleared." },
  { id: "N-RLS-ENABLED-ROOT-SCHEMA", kind: "negative", cls: "root-schema table that DOES enable RLS", location: "schema.sql", match: ["nocode_safe"], note: "#565: schema.sql also creates public.nocode_safe WITH `alter table public.nocode_safe enable row level security`. checkMigrationRlsStatic aggregates enables across every source it reads (migrations + root schema.sql), so this is cleared — proving the root-schema pass distinguishes RLS-off from RLS-on, not just 'any table in schema.sql'." },

  // #611 Gap B — the schema qualifier is optional: a no-code export writes bare `create table X`
  // (public is implicit). CREATE_TABLE/ENABLE_RLS required a literal `public.`, so a bare table was
  // read but never enumerated. Broadened to an optional-schema capture that keeps public-schema
  // tables (bare or `public.`-qualified) and drops explicit non-public schemas.
  { id: "P-RLS-BARE-CREATE-TABLE", kind: "positive", cls: "unqualified public table with RLS off (no-code bare `create table X`)", location: "schema.sql", match: ["workspaces"], expectedTier: "high", note: "#611 Gap B: schema.sql creates `workspaces` UNQUALIFIED (public is the implicit schema) with no `enable row level security` anywhere — auto-exposed via PostgREST. Before #611 CREATE_TABLE required a literal `public.`, so the bare table was read but never enumerated. checkMigrationRlsStatic → high (Critical). nocode-rescue before/schema.sql." },
  { id: "N-RLS-BARE-ENABLED", kind: "negative", cls: "unqualified table that DOES enable RLS (bare alter)", location: "schema.sql", match: ["members"], note: "#611 Gap B: schema.sql creates bare `members` and enables RLS with an equally bare `alter table members enable row level security`. The symmetric ENABLE_RLS broadening captures the bare enable, so members is cleared — proving the bare-name pass distinguishes RLS-off from RLS-on." },
  { id: "N-RLS-NONPUBLIC-SCHEMA", kind: "negative", cls: "explicit non-public schema table (not PostgREST-exposed)", location: "schema.sql", match: ["internal_audit"], note: "#611 Gap B: schema.sql creates `private.internal_audit` with no RLS. An explicit non-public schema is NOT exposed via PostgREST, so it must not be flagged RLS-off. The optional-schema capture reads the `private` qualifier and drops it from the public enumeration — cleared even though it never enables RLS." },

  // #1323 — #565 broadened only checkMigrationRlsStatic to read a root schema.sql. Six sibling
  // checks read SQL through readMigrations(), which stayed supabase/migrations-only, so all six
  // returned [] on the no-code export shape. The fixture above could not expose that: it planted
  // only `create table` / `enable row level security`, the two statements the ONE broadened reader
  // consumes. MEASURED 2026-07-30 by replaying targets/calibration/supabase/migrations/** (24
  // files, 1180 lines) as a single root schema.sql: policy-semantics 11 -> 0, RLS-initplan 7 -> 0,
  // definer-authz 2 -> 0, definer-anon-grant 1 -> 0, dynamic-SQL-injection 1 -> 0, storage-buckets
  // 3 -> 2. These six positives (one per check, each with the near-miss that must stay silent) are
  // what makes reverting readMigrations() fail the gate instead of passing it quietly.
  { id: "P-POLICY-PERMISSIVE-ROOT-SCHEMA", kind: "positive", cls: "permissive USING(true) policy read from a root schema.sql", location: "schema.sql", match: ["nocode_invoices_read"], expectedTier: "review", expectedSeverity: "High", note: "#1323: schema.sql's `create policy nocode_invoices_read … for select to authenticated using (true)` puts RLS ON the table and then lets every authenticated caller read every tenant's rows — the shape that reads as protected in a config dashboard. checkMigrationPolicySemantics (via readMigrations) → review, High. Scored on the policy name rather than the table, because the same table carries the two negatives below." },
  { id: "N-POLICY-TENANT-SCOPED-ROOT-SCHEMA", kind: "negative", cls: "tenant-scoped policy in a root schema.sql", location: "schema.sql", match: ["nocode_invoices_write"], note: "#1323: the same table's INSERT policy binds tenant_id to the caller's JWT claim and hoists the call as `(select auth.jwt())`. It must clear BOTH the semantic reviewer and the initplan perf check — otherwise the root-schema pass is flagging any policy it finds rather than a permissive one." },
  { id: "P-RLS-INITPLAN-ROOT-SCHEMA", kind: "positive", cls: "bare auth.uid() in a policy read from a root schema.sql", location: "schema.sql", match: ["nocode_invoices_own"], expectedTier: "review", note: "#1323: `nocode_invoices_own` is correctly tenant- AND owner-scoped, so the semantic reviewer clears it; its auth.uid() is BARE, so Postgres re-evaluates it once per row. checkMigrationRlsInitplanStatic → review. Deliberately a single-check probe: the scoping is what keeps this policy from also drawing a semantics finding. Severity left unasserted — this row is graded Perf, not on the security band." },
  { id: "P-SECDEF-NOAUTH-ROOT-SCHEMA", kind: "positive", cls: "SECURITY DEFINER privileged write, no caller check, in a root schema.sql", location: "schema.sql", match: ["nocode_set_role"], expectedTier: "review", expectedSeverity: "High", note: "#1323: `public.nocode_set_role(target_user_id, new_role)` is SECURITY DEFINER and updates profiles.role with no auth.uid()/auth.jwt() anywhere in the body — any caller who reaches it promotes anyone. checkMigrationDefinerAuthz → review, High. The trailing `(` in the match key keeps it off the `_checked` negative below, whose name contains this one as a prefix." },
  { id: "N-SECDEF-AUTHCHECK-ROOT-SCHEMA", kind: "negative", cls: "SECURITY DEFINER write gated on the caller, in a root schema.sql", location: "schema.sql", match: ["nocode_promote_guarded"], note: "#1323: the identical privileged write, preceded by `if not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then raise exception`. needsAuthzReview asks only whether the body references the caller at all, so this must be cleared — proving the check reads bodies rather than flagging every DEFINER function in schema.sql." },
  { id: "P-PLPGSQL-SQLI-ROOT-SCHEMA", kind: "positive", cls: "plpgsql EXECUTE concatenating a parameter, in a root schema.sql", location: "schema.sql", match: ["nocode_search_invoices"], expectedTier: "review", expectedSeverity: "Critical", note: "#1323: `public.nocode_search_invoices(p_filter)` splices p_filter into the EXECUTE query string with `|| p_filter ||` and no quote_literal — CWE-89, and DEFINER, so the injected query runs as the owner past RLS. checkMigrationDynamicSqlInjection → review, Critical." },
  { id: "N-PLPGSQL-SQLI-SAFE-ROOT-SCHEMA", kind: "negative", cls: "plpgsql EXECUTE binding its parameter through USING, in a root schema.sql", location: "schema.sql", match: ["nocode_bound_invoice_query"], note: "#1323: the same dynamic query with `… like $1' using p_filter` — the parameter is BOUND, never spliced into SQL text. executeQueryStrings scopes the concat check to the text before `using`, so this must stay silent." },
  { id: "P-SECDEF-ANON-GRANT-ROOT-SCHEMA", kind: "positive", cls: "SECURITY DEFINER reader granted to anon, in a root schema.sql", location: "schema.sql", match: ["nocode_all_invoices"], expectedTier: "review", expectedSeverity: "High", note: "#1323: `public.nocode_all_invoices()` is SECURITY DEFINER, returns setof the invoices table with no caller check, and is explicitly `grant execute … to anon` — anyone holding the anon key dumps every tenant. checkMigrationDefinerAnonGrant → review, High." },
  { id: "P-STORAGE-BUCKET-PUBLIC-ROOT-SCHEMA", kind: "positive", cls: "public storage bucket declared in a root schema.sql", location: "schema.sql", match: ["nocode-attachments"], expectedTier: "review", expectedSeverity: "High", note: "#1323: `insert into storage.buckets (id, name, public) values ('nocode-attachments', …, true)` — Supabase serves every object in a public bucket unauthenticated, and storage.objects RLS does not apply to that path. checkMigrationStorageBuckets → review, High." },
  { id: "P-STORAGE-ANON-READ-ROOT-SCHEMA", kind: "positive", cls: "anon SELECT policy on storage.objects, read from a root schema.sql", location: "schema.sql", match: ["nocode_attachments_anon_read"], expectedTier: "review", expectedSeverity: "High", note: "#1323: checkMigrationStorageBuckets has TWO halves and they read different loaders — the bucket-insert half goes through readRlsSqlSources (already broadened by #565), the storage.objects-policy half through readMigrations. Only the second went dark on a root schema.sql, so a fixture covering the bucket alone would have reported the whole check as guarded. `nocode_attachments_anon_read` grants anon SELECT with a clause that never names the caller → review, High." },
  { id: "N-STORAGE-ANON-OWNER-SCOPED-ROOT-SCHEMA", kind: "negative", cls: "anon storage.objects policy scoped to the caller, in a root schema.sql", location: "schema.sql", match: ["nocode_private_owner_read"], note: "#1323: the same shape with `and owner = auth.uid()`. A clause that names the caller is the semantic reviewer's business; this rule owns only the read policy with no caller reference whatsoever, so it must stay silent." },
  { id: "N-STORAGE-BUCKET-PRIVATE-ROOT-SCHEMA", kind: "negative", cls: "private storage bucket declared in a root schema.sql", location: "schema.sql", match: ["nocode-private"], note: "#1323: the sibling insert with `public` false. The check reads the `public` column out of the column list and the value tuple, so a private bucket must stay silent — otherwise it is flagging the insert statement, not the exposure." },

  // #602 (cipherx CX-11/CX-12) — migration-SQL static passes for plpgsql dynamic-SQL injection and
  // SECURITY DEFINER data-dumping functions explicitly granted to anon. Both fell to the semantic tier:
  // Harvey's SQLi coverage was JS/semgrep-only and the definer pass flagged only privileged WRITES.
  { id: "P-PLPGSQL-SQLI-CONCAT", kind: "positive", cls: "plpgsql EXECUTE concatenates a parameter into dynamic SQL (CWE-89)", location: "search_tickets_unsafe", match: ["plpgsql-sqli"], expectedTier: "review", note: "#602 CX-12: public.search_tickets_unsafe(p_query) does `return query execute 'select … ilike ' || p_query` — the parameter is spliced into the query string with no quote_literal/quote_ident. It is SECURITY DEFINER, so the injected query runs as the owner, bypassing RLS. checkMigrationDynamicSqlInjection scopes the concat check to the EXECUTE query string (before any USING), → review (Critical severity)." },
  { id: "N-PLPGSQL-SQLI-PARAMETERIZED", kind: "negative", cls: "safe parameterized EXECUTE (bound $1 via USING)", location: "search_tickets_safe", match: ["plpgsql-sqli"], note: "#602: public.search_tickets_safe uses `execute 'select … ilike $1' using '%' || p_query || '%'` — the `|| p_query ||` builds the USING VALUE (bound), not the SQL text, and lands after `using`, so the query-string-scoped check does not flag it. Proves the SQLi pass distinguishes concatenation into SQL text from a bound parameter value." },
  { id: "N-PLPGSQL-SQLI-QUOTED", kind: "negative", cls: "safe dynamic SQL escaped with quote_literal()", location: "search_tickets_quoted", match: ["plpgsql-sqli"], note: "#602: public.search_tickets_quoted uses `execute 'select … = ' || quote_literal(p_query)` — the parameter is wrapped in quote_literal(), the safe escaper, so the concat-of-param check clears it. Proves the pass recognizes the quote_literal/quote_ident escape hatch." },
  { id: "P-DEFINER-ANON-DUMP", kind: "positive", cls: "SECURITY DEFINER data reader granted to anon with no caller check", location: "get_user_by_email", match: ["definer-anon-grant"], expectedTier: "review", note: "#602 CX-11: public.get_user_by_email(p_email) is SECURITY DEFINER, returns setof rows, has no auth.uid()/auth.jwt() caller check, and is EXPLICITLY `grant execute … to anon` — an unauthenticated caller can dump any user row across tenants. checkMigrationDefinerAuthz flags only privileged WRITES, so this data-dumping reader fell through; checkMigrationDefinerAnonGrant surfaces the explicit-anon-grant signal → review (High)." },
  { id: "N-DEFINER-ANON-CALLER-CHECK", kind: "negative", cls: "definer reader granted to anon but checks its caller (auth.uid())", location: "get_my_tickets", match: ["definer-anon-grant"], note: "#602: public.get_my_tickets() is granted to anon but its body checks auth.uid()/auth.jwt() before returning rows (self-scoping) — legitimately anon-callable. checkMigrationDefinerAnonGrant keys on the MISSING caller check, so this is cleared. Proves the rule doesn't fire on the anon grant alone." },
  { id: "N-DEFINER-AUTHENTICATED-GRANT", kind: "negative", cls: "definer reader granted only to authenticated (not anon/public)", location: "list_my_org_tickets", match: ["definer-anon-grant"], note: "#602: public.list_my_org_tickets() is a SECURITY DEFINER reader granted to AUTHENTICATED, not anon/public — a user-facing RPC granted to signed-in users is normal. The rule is scoped to anon/public grants, so it stays silent. Proves the anon-grant signal is scoped to the unauthenticated role." },

  // #588 — static open-signup / no-email-confirmation config read from supabase/config.toml at the
  // source tier (the free-tier twin of the connected-tier checkAuthConfig mailer_autoconfirm check).
  // Both positives are the committed calibration config.toml; the safe-value negative (enable_signup=
  // false / enable_confirmations=true) and the section-scoping negative ([auth.sms] ignored) are
  // proven in src/scan/supabase-static.test.ts against a separate config fixture (a same-file negative
  // can't carry the opposite value for the same key that the positive already sets).
  { id: "P-OPEN-SIGNUP-STATIC", kind: "positive", cls: "open self-registration enabled ([auth] enable_signup=true)", location: "supabase/config.toml", match: ["open signup"], expectedTier: "review", note: "#588: supabase/config.toml [auth] enable_signup = true — anyone can self-register an account with no invite. checkOpenSignupConfig (src/scan/supabase-static.ts) reads it only under the top-level [auth] table (the [auth.sms] sibling is ignored). Source-tier sibling of the connected-tier checkAuthConfig. harvey/SB-OPEN-SIGNUP → review (Low)." },
  { id: "P-EMAIL-CONFIRM-OFF-STATIC", kind: "positive", cls: "email confirmation disabled ([auth.email] enable_confirmations=false)", location: "supabase/config.toml", match: ["email confirmation"], expectedTier: "review", note: "#588: supabase/config.toml [auth.email] enable_confirmations = false — accounts authenticate without proving ownership of the email address (the static twin of the live mailer_autoconfirm=true check). checkOpenSignupConfig reads enable_confirmations only under [auth.email], so the [auth.sms] enable_confirmations=false sibling is not flagged. SB-EMAIL-CONFIRM-OFF → review (Medium)." },

  // #1425 — protect-then-UNPROTECT, the sequence P-RLS-MISSING-STATIC above is structurally blind
  // to. That entry is cleared by an `enable row level security` ANYWHERE in the file set, which is
  // what makes it robust against a schema split across migrations and is exactly what made a later
  // `disable row level security` invisible: MEASURED 2026-07-28, appending that statement to a
  // calibration migration whose readership was proven by a control finding in the same file
  // produced ZERO findings, because src/scan/supabase-static.ts carried no disable pattern at all.
  //
  // A FALSE NEGATIVE is the hard direction to guard — nothing reports that a rule stopped firing
  // except a fixture scored against an answer key — so these three rows are the lock, and the
  // fixture is built so that each of its three files goes RED if it is not read: 20260728000003
  // decides the positive, 20260728000004 decides the negative, and 20260728000002 (which decides
  // neither, since SB-RLS-DISABLED-STATIC does not require having seen the create) carries the
  // scope control below.
  { id: "P-RLS-DISABLE-NOT-REVERTED", kind: "positive", cls: "public table protected in one migration and un-protected by a later one", location: "20260728000003_rls_disable_hotfix.sql", match: ["billing_exports"], expectedTier: "high", expectedSeverity: "Critical", note: "#1425: public.billing_exports is created in 20260728000002 WITH `enable row level security` and a correct tenant-scoped policy, then 20260728000003 issues `alter table public.billing_exports disable row level security` and nothing reverts it — the hotfix-never-put-back shape. The table is auto-exposed via PostgREST and its policy is inert (Postgres does not consult policies while row security is off), so the schema reads as protected and behaves as public. checkMigrationRlsStatic now resolves row-security state in apply order and reports the table whose LAST statement is a disable → SB-RLS-DISABLED-STATIC-billing_exports, high (Critical). Free-count like its sibling: unlike policy semantics this needs no reasoning about intent, only the order of two exact DDL statements. Located at the DISABLE site, not the create site — the create is not the defect." },
  { id: "N-RLS-DISABLE-REVERTED", kind: "negative", cls: "RLS disabled and re-enabled by a later migration — final state protected", location: "20260728000003_rls_disable_hotfix.sql", match: ["import_staging"], note: "#1425: public.import_staging takes a byte-identical `disable row level security` in the SAME hotfix migration as the billing_exports plant — same verb, same file, same table shape — and 20260728000004 re-enables it. It must stay out of the free count, because the discriminator is the table's FINAL row-security state across the file set, never the presence of a disable statement: a rule matching `disable row level security` textually would flag every backfill migration that correctly puts protection back, which is the false-positive flood that would make the class ignorable (briefs/fp-rules.txt). This entry is also 20260728000004's readership proof — if that file were skipped, import_staging would resolve to disabled and this row would FAIL as a free-count false positive rather than going quietly clean." },
  { id: "P-RLS-DISABLE-SCOPE-CONTROL", kind: "positive", cls: "known-caught control proving the #1425 setup migration is read", location: "20260728000002_rls_disable_tables.sql", match: ["export_audit"], expectedTier: "high", expectedSeverity: "Critical", note: "#1425 scope control, per the corpus rule that a fixture the scanner never read reports zero findings exactly like one it scanned and missed. The other two #1425 entries cannot cover this file: the positive is decided by the disable in 20260728000003, the negative by the re-enable in 20260728000004, and SB-RLS-DISABLED-STATIC deliberately does not require having seen the `create table` — so both would still score correctly if 20260728000002 were skipped entirely. public.export_audit is created there and gets row security in no file, so the ORIGINAL check must fire: SB-RLS-STATIC-export_audit, high (Critical). If this row misses, the two entries beside it prove nothing." },
];
