// Batch B13 (#71) — Supabase static-config/edge + injection-sink breadth (roadmap
// `docs/design/corpus-roadmap-to-100.md` §3e). Detection is split three ways:
//   - ONE new static scanner, `checkMigrationRlsStatic` (src/scan/supabase-static.ts, wired into
//     runMechanicalScan): parses committed supabase/migrations/*.sql for a `create table public.X`
//     that never gets `enable row level security` anywhere — the static path for P-RLS-DISABLED,
//     which was connected-tier only. HIGH (the honesty-flag class, roadmap §5): it fires ONLY on
//     audit_logs and stays silent on service_state (RLS enabled + zero policies, deny-all by
//     design) and on documents (RLS enabled in a LATER migration file) — both verified negatives.
//   - a small static config check, `checkEdgeFunctionVerifyJwt` (same module): parses
//     supabase/config.toml for `[functions.X] verify_jwt = false`. Review.
//   - the rest EXTEND src/scan/rules/semgrep/injection.yml: two ERROR+HIGH structural rules
//     (spawn/execFile shell:true; pg Pool ssl:false to a pooler host), one ERROR+HIGH client rule
//     (auth.admin.* in a "use client" Component), and six WARNING+MEDIUM injection-sink heuristics.
//
// Adjacency (kept from double-firing): P-SPAWN-SHELL is spawn/execFile{shell:true}, disjoint from
// harvey-command-injection (exec/execSync); P-AUTH-ADMIN-CLIENT keys off the auth.admin call, not the
// SERVICE_ROLE_KEY env literal harvey-service-role-in-client (base.yml) matches, and its fixture never
// writes that literal. P-RLS-MISSING-STATIC is the static counterpart of the existing connected
// P-RLS-DISABLED (base.entries.ts, audit_logs); both coexist (one high/static, one connected/N/A).
//
// See GROUND-TRUTH.md §B13. Dropped: none — all 12 §3e rows landed.

import type { CorpusEntry } from "./types.js";

export const b13SupaEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-RLS-MISSING-STATIC", kind: "positive", cls: "public table never gets ENABLE RLS (read statically from migrations)", location: "20260708000001_schema.sql", match: ["audit_logs"], expectedTier: "high", note: "create table public.audit_logs (migrations/…0001_schema.sql:35) has no matching `enable row level security` anywhere in supabase/migrations/. checkMigrationRlsStatic (src/scan/supabase-static.ts) aggregates enables across ALL migration files, so it clears documents (enabled in the LATER …0002_rls.sql) and service_state (RLS on, zero policies) — audit_logs is the only table left with RLS off → high. Static path for the connected-tier P-RLS-DISABLED." },
  { id: "P-PG-SSL-DISABLED", kind: "positive", cls: "pg Pool ssl:false to a Supabase pooler host", location: "lib/pg-ssl-disabled.js", match: ["pg-ssl-disabled"], expectedTier: "high", note: "new Pool({ connectionString: '…@aws-0-us-east-1.pooler.supabase.com…', ssl: false }) in lib/pg-ssl-disabled.js. Semgrep harvey-pg-ssl-disabled (ssl:false in a Pool literal AND a pooler.supabase.com host via pattern-regex) → high. Negative uses ssl:{rejectUnauthorized:true}." },
  { id: "P-AUTH-ADMIN-CLIENT", kind: "positive", cls: "auth.admin.* reachable from a Client Component", location: "components/AdminUsersClient.jsx", match: ["auth-admin-in-client"], expectedTier: "high", note: "'use client' + supabaseAdmin.auth.admin.listUsers() in components/AdminUsersClient.jsx. Semgrep harvey-auth-admin-in-client ($C.auth.admin.$M(...) inside a \"use client\" module) → high. Broader than harvey-service-role-in-client (base.yml, SERVICE_ROLE_KEY env literal); the fixture never writes that literal, so no double-fire." },
  { id: "P-SPAWN-SHELL", kind: "positive", cls: "spawn/execFile with { shell: true }", location: "pages/api/thumbnail.js", match: ["spawn-shell-true"], expectedTier: "high", note: "spawn('convert', [req.query.file, …], { shell: true }) in pages/api/thumbnail.js — shell:true re-parses the argv array through /bin/sh. Semgrep harvey-spawn-shell-true → high. Disjoint from harvey-command-injection (exec/execSync); the argv-array negative (execFile, no shell) clears." },

  { id: "P-EDGEFN-VERIFY-JWT-OFF", kind: "positive", cls: "Edge Function verify_jwt=false", location: "supabase/config.toml", match: ["verify_jwt", "admin-refund", "verifyjwt"], expectedTier: "review", note: "[functions.admin-refund] verify_jwt = false in supabase/config.toml — the endpoint is callable with no valid JWT. checkEdgeFunctionVerifyJwt (src/scan/supabase-static.ts) → review. The [functions.user-profile] verify_jwt = true negative in the same file is cleared (the check matches only `= false` under a [functions.X] table)." },
  { id: "P-SELECT-STAR-PII", kind: "positive", cls: "select('*') spread into an API response", location: "pages/api/customers.js", match: ["select-star-pii"], expectedTier: "review", note: "supabase.from('customers').select('*') returned via res.json(data) in pages/api/customers.js. Semgrep harvey-select-star-pii (taint select('*') → res.json/NextResponse.json) → review. Distinct from harvey-server-client-leak (auth.yml, a JSX-spread sink). Negative projects an explicit column list." },
  { id: "P-CRON-NO-SECRET", kind: "positive", cls: "service-role cron endpoint with no caller secret", location: "pages/api/cron/rollup.js", match: ["cron-no-secret"], expectedTier: "review", note: "pages/api/cron/rollup.js calls supabaseAdmin.from(...) in a handler with no preflight guard. Semgrep harvey-cron-no-secret (supabaseAdmin DB call, pattern-not-inside a handler carrying an `if` guard) → review. The CRON_SECRET-checked negative (rollup-secure.js) is excluded." },
  { id: "P-DYNAMIC-REQUIRE", kind: "positive", cls: "require() with a request-tainted arg", location: "pages/api/plugin.js", match: ["dynamic-require"], expectedTier: "review", note: "require(req.query.module) in pages/api/plugin.js. Semgrep harvey-dynamic-require (taint req.* → require) → review. The fixed-string require negative (lib/fixed-require.js) is untainted, cleared." },
  { id: "P-DYNAMIC-DISPATCH", kind: "positive", cls: "obj[userInput]() dynamic method dispatch", location: "pages/api/dispatch.js", match: ["dynamic-dispatch"], expectedTier: "review", note: "actions[req.body.action](req.body.payload) in pages/api/dispatch.js. Semgrep harvey-dynamic-dispatch (taint req.* → computed-member call $OBJ[$IDX](...)) → review. The allowlist-checked negative (dispatch-safe.js) clears — no tainted key reaches the computed call." },
  { id: "P-TEMPLATE-AUTOESCAPE-OFF", kind: "positive", cls: "template engine autoescape off", location: "lib/render-template.js", match: ["template-autoescape-off"], expectedTier: "review", note: "Handlebars.compile(tpl, { noEscape: true }) in lib/render-template.js — autoescaping off makes every interpolation an XSS sink. Semgrep harvey-template-autoescape-off → review. The default-escaping negative (render-template-safe.js) has no noEscape option, cleared." },
  { id: "P-HTML-TEMPLATE-LITERAL", kind: "positive", cls: "HTML template literal into res.send", location: "pages/api/greet.js", match: ["html-template-literal"], expectedTier: "review", note: "res.send(`<h1>Hello ${req.query.name}</h1>`) in pages/api/greet.js — reflected XSS. Semgrep harvey-html-template-literal (taint req.* → res.send of a template literal) → review. The plain-JSON negative (greet-safe.js) has no res.send template-literal sink, cleared." },
  { id: "P-INCOMPLETE-SANITIZE", kind: "positive", cls: "non-global .replace() used as a sanitizer", location: "lib/sanitize-bad.js", match: ["incomplete-sanitize"], expectedTier: "review", note: "s.replace('<','').replace('>','') in lib/sanitize-bad.js — a string-literal needle replaces only the first match. Semgrep harvey-incomplete-sanitize (string-literal needle via metavariable-regex) → review. The /g-regex negative (sanitize-ok.js) has a regex needle, not a string, cleared." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-RLS-DENY-ALL-STATIC", kind: "negative", cls: "service-only table, RLS enabled + zero policies (deny-all)", location: "20260708000001_schema.sql", match: ["service_state"], note: "public.service_state (created in …0001_schema.sql) gets `enable row level security` in …0002_rls.sql with zero policies — deny-all by design, not RLS-off. checkMigrationRlsStatic sees the ENABLE and stays silent — no finding mentions service_state. Contrast P-RLS-MISSING-STATIC (audit_logs)." },
  { id: "N-RLS-ENABLED-LATER", kind: "negative", cls: "table whose RLS is enabled in a later migration file", location: "20260708000001_schema.sql", match: ["documents"], note: "public.documents (created in …0001_schema.sql) gets `enable row level security` in the LATER …0002_rls.sql. checkMigrationRlsStatic aggregates enables across all migration files, so documents is cleared — the honesty-flag's cross-file negative." },
  { id: "N-PG-SSL-OK", kind: "negative", cls: "pg Pool to a pooler host with TLS verification on", location: "lib/pg-ssl-ok.js", match: ["pg-ssl-disabled"], note: "new Pool({ …pooler.supabase.com…, ssl: { rejectUnauthorized: true } }) in lib/pg-ssl-ok.js. harvey-pg-ssl-disabled matches only `ssl: false` — cleared." },
  { id: "N-AUTH-ADMIN-SERVER", kind: "negative", cls: "auth.admin.* in a server-only module", location: "lib/admin-users-server.js", match: ["auth-admin-in-client"], note: "the same supabaseAdmin.auth.admin.listUsers() in lib/admin-users-server.js, a server-only module with no \"use client\". harvey-auth-admin-in-client fires only inside a Client Component — cleared." },
  { id: "N-AUTH-ADMIN-ANON-CLIENT", kind: "negative", cls: "auth.admin.* called on the anon client in a Client Component", location: "contexts/AuthContext.jsx", match: ["auth-admin-in-client"], note: "'use client' + supabase.auth.admin.deleteUser() in contexts/AuthContext.jsx, where `supabase` (utils/supabase.js) is the anon/publishable-key client, not service-role — a broken no-op call at runtime, not a key exposure. harvey-auth-admin-in-client now requires the client identifier to read as admin/service-role (/admin|service/i); \"supabase\" doesn't match — cleared (#164)." },
  { id: "N-SPAWN-NOSHELL", kind: "negative", cls: "execFile with an argv array, no shell", location: "pages/api/thumbnail-safe.js", match: ["spawn-shell-true"], note: "execFile('convert', [req.query.file, …], cb) in pages/api/thumbnail-safe.js — argv array, no shell option. harvey-spawn-shell-true requires shell:true — cleared." },
  { id: "N-EDGEFN-VERIFY-JWT-ON", kind: "negative", cls: "Edge Function verify_jwt=true", location: "supabase/config.toml", match: ["user-profile"], note: "[functions.user-profile] verify_jwt = true in supabase/config.toml. checkEdgeFunctionVerifyJwt matches only `verify_jwt = false` under a [functions.X] table — cleared. (Matched by function name so the admin-refund positive at the same location doesn't attribute here.)" },
  { id: "N-SELECT-EXPLICIT", kind: "negative", cls: "explicit column projection into an API response", location: "pages/api/customers-safe.js", match: ["select-star-pii"], note: "supabase.from('customers').select('id,name,email') → res.json in pages/api/customers-safe.js. harvey-select-star-pii requires a select('*') source — cleared." },
  { id: "N-CRON-SECRET", kind: "negative", cls: "cron endpoint gated by a CRON_SECRET check", location: "pages/api/cron/rollup-secure.js", match: ["cron-no-secret"], note: "pages/api/cron/rollup-secure.js checks Authorization against CRON_SECRET (an `if` guard) before the supabaseAdmin call. harvey-cron-no-secret's pattern-not-inside excludes a handler carrying a guard block — cleared." },
  { id: "N-REQUIRE-FIXED", kind: "negative", cls: "require() of a fixed string literal", location: "lib/fixed-require.js", match: ["dynamic-require"], note: "require('./helper') in lib/fixed-require.js — no request taint. harvey-dynamic-require needs a tainted argument — cleared." },
  { id: "N-DISPATCH-ALLOWLIST", kind: "negative", cls: "dispatch checked against an allowlist", location: "pages/api/dispatch-safe.js", match: ["dynamic-dispatch"], note: "pages/api/dispatch-safe.js checks the action name against an explicit allowlist and dispatches a fixed reference — no tainted key reaches a computed call. harvey-dynamic-dispatch is cleared." },
  { id: "N-TEMPLATE-ESCAPED", kind: "negative", cls: "template engine with default escaping", location: "lib/render-template-safe.js", match: ["template-autoescape-off"], note: "Handlebars.compile(tpl) in lib/render-template-safe.js — no noEscape option, HTML escaping stays on. harvey-template-autoescape-off is cleared." },
  { id: "N-HTML-PLAINTEXT", kind: "negative", cls: "request value returned as plain JSON, not HTML", location: "pages/api/greet-safe.js", match: ["html-template-literal"], note: "res.json({ name: req.query.name }) in pages/api/greet-safe.js — no res.send HTML template literal. harvey-html-template-literal is cleared." },
  { id: "N-SANITIZE-GLOBAL", kind: "negative", cls: "global-regex .replace() sanitizer", location: "lib/sanitize-ok.js", match: ["incomplete-sanitize"], note: "s.replace(/</g,'').replace(/>/g,'') in lib/sanitize-ok.js — a /g regex needle strips every match. harvey-incomplete-sanitize's metavariable-regex requires a quoted string needle — cleared." },

  // #565 — Vite/no-code (Lovable/Bolt/v0) M1 shapes: a service-role key inlined via import.meta.env.
  // VITE_*, a browser LLM client (dangerouslyAllowBrowser), and an RLS-off table read from a root
  // schema.sql (checkMigrationRlsStatic broadened past supabase/migrations-only).
  { id: "P-VITE-SERVICE-ROLE-CLIENT", kind: "positive", cls: "service-role key via import.meta.env.VITE_* in client code", location: "src/lib/supabaseServiceClient.ts", match: ["vite-service-role"], expectedTier: "high", note: "#565: src/lib/supabaseServiceClient.ts passes import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY to createClient — Vite inlines every VITE_-prefixed var into the browser bundle, so the service-role key ships to every visitor (full RLS bypass). Semgrep harvey-vite-service-role-in-client (import.meta.env.$K with $K matching VITE_*SERVICE_ROLE*) → high (Critical). The Vite counterpart of harvey-service-role-in-client (process.env + 'use client'). nocode-rescue #1." },
  { id: "P-DANGEROUSLY-ALLOW-BROWSER", kind: "positive", cls: "browser LLM client (dangerouslyAllowBrowser: true)", location: "src/lib/openaiBrowser.ts", match: ["dangerously-allow-browser"], expectedTier: "high", note: "#565: src/lib/openaiBrowser.ts constructs new OpenAI({ …, dangerouslyAllowBrowser: true }) with the key from import.meta.env.VITE_OPENAI_API_KEY — the SDK requires that flag to run client-side precisely because it exposes the key to every visitor. Semgrep harvey-dangerously-allow-browser → high. nocode-rescue #2 (browser LLM key in the bundle)." },
  { id: "P-RLS-MISSING-ROOT-SCHEMA", kind: "positive", cls: "public table with RLS off, read from a root schema.sql (no-code export)", location: "schema.sql", match: ["nocode_tickets"], expectedTier: "high", note: "#565: schema.sql (a Table-Editor/no-code export commits its schema as a single root schema.sql, not supabase/migrations/*.sql) creates public.nocode_tickets with no `enable row level security` anywhere — auto-exposed via PostgREST. checkMigrationRlsStatic was migrations-only (returned [] with no supabase/migrations); #565 broadened it to also read a root schema.sql → high (Critical). nocode-rescue #3." },

  // --- NEGATIVES (#565) ---
  { id: "N-VITE-ANON-CLIENT", kind: "negative", cls: "anon/publishable key via import.meta.env.VITE_* (intended)", location: "src/lib/supabaseAnonClient.ts", match: ["vite-service-role"], note: "#565: src/lib/supabaseAnonClient.ts reads import.meta.env.VITE_SUPABASE_ANON_KEY — the anon/publishable key is DESIGNED to ship to the browser (RLS-protected), so this is the correct Vite shape. harvey-vite-service-role-in-client is scoped by metavariable-regex to a SERVICE_ROLE/SERVICE_KEY name; the anon key name doesn't match — cleared." },
  { id: "N-OPENAI-SERVER", kind: "negative", cls: "server-side LLM client, no dangerouslyAllowBrowser", location: "src/lib/openaiServer.ts", match: ["dangerously-allow-browser"], note: "#565: src/lib/openaiServer.ts constructs new OpenAI({ apiKey: process.env.OPENAI_API_KEY }) with no dangerouslyAllowBrowser flag — the key stays server-only. harvey-dangerously-allow-browser matches only the `dangerouslyAllowBrowser: true` literal — cleared." },
  { id: "N-RLS-ENABLED-ROOT-SCHEMA", kind: "negative", cls: "root-schema table that DOES enable RLS", location: "schema.sql", match: ["nocode_safe"], note: "#565: schema.sql also creates public.nocode_safe WITH `alter table public.nocode_safe enable row level security`. checkMigrationRlsStatic aggregates enables across every source it reads (migrations + root schema.sql), so this is cleared — proving the root-schema pass distinguishes RLS-off from RLS-on, not just 'any table in schema.sql'." },
];
