// Batch B15 (#123, issues #131-#136) — Next.js/Supabase authz-shape classes seeded for the
// semantic/whole-program tier (roadmap `docs/design/corpus-roadmap-to-100.md` §4a). Every entry is
// `review` tier. Originally NONE had a matching mechanical rule; the #354 re-triage graduated TWO
// to a leftover-auth grep (still review, not free-count): P-MW-MATCHER-EXCLUDES-API (the matcher's
// api-lookahead is a textual fact) and P-DRAFTMODE-NO-SECRET (a shallow intra-file "enable with no
// secret gate" check). #433 graduated a THIRD: P-BOLA-BODY-OWNER is now caught by the bola-owner
// AST pass (src/scan/bola-owner.ts, runs in runMechanicalScan) — session-bound handler +
// service-rooted `.eq(<ownership col>, <request-rooted value>)` + no session-vs-client comparison
// is a dataflow fact, not identity reasoning. The remaining THREE (P-MW-SOLE-AUTHZ,
// P-HOST-HEADER-URL, P-CLIENT-RENDER-AUTHZ) stay LLM/paid-tier — they need table-sensitivity
// judgment, cross-function taint, or a server→client boundary a grep/AST can't do FP-safely, so the
// offline mechanical gate is expected to leave them uncaught (reviewMisses, non-fatal — see
// src/cli/validate-calibration.ts). The acceptance bar for THIS batch is precision, not recall:
// zero free-count (high-tier) false positives on the negatives. See GROUND-TRUTH.md §B15.

import type { CorpusEntry } from "./types.js";

export const b15NextjsAuthzEntries: CorpusEntry[] = [
  // #131 — object/function-level authz gap (BOLA/BFLA)
  { id: "P-BOLA-BODY-OWNER", kind: "positive", cls: "object/function-level authz gap: route trusts body.tenantId for the query (BOLA/BFLA)", location: "pages/api/billing/invoice.js", match: ["bola-body-owner"], expectedTier: "review", note: "#131/#433: pages/api/billing/invoice.js authenticates the caller but scopes the invoices query to req.body.tenantId — a client-supplied value — instead of the tenant id on the verified session. GRADUATED to a mechanical rule (#433): the bola-owner AST pass (src/scan/bola-owner.ts, in runMechanicalScan) proves the session binding, the service-rooted chain, the request-rooted .eq value, and the absence of a session-vs-client comparison — dataflow facts, not identity reasoning. Review, never free-count: the AST can't see a wrapper's gate. Discriminator vs the sibling: the .eq value's ROOT (req vs session); session-precedence keeps `const session = await getServerSession(req)` server-derived." },
  { id: "N-BOLA-SESSION-OWNER", kind: "negative", cls: "invoice query scoped to the session's tenant id, not a client-supplied field", location: "pages/api/billing/invoice-safe.js", match: ["bola-body-owner"], note: "#131/#433: pages/api/billing/invoice-safe.js scopes the query to session.user.tenantId — req.body.tenantId is never read. The #433 bola-owner pass stays fully silent here (measured, not trivial since #433): session is bound FROM req, so this pins the session-precedence rule that keeps a session-derived value out of the client set." },

  // #132 — middleware matcher regex silently excludes /api/*
  { id: "P-MW-MATCHER-EXCLUDES-API", kind: "positive", cls: "Next.js middleware matcher regex excludes /api/*, leaving API routes unprotected", location: "middleware.ts", match: ["mw-matcher-excludes-api"], expectedTier: "review", note: "#132/#354: middleware.ts's config.matcher (`/((?!api|_next/static|_next/image|favicon.ico).*)`) excludes every /api/* path from ever running the middleware, so pages/api/admin/dashboard.js is reachable with zero gate. GRADUATED to a mechanical rule (#354): leftover-auth's mw-matcher-excludes-api grep matches an exported config.matcher whose negative-lookahead lists an `api` token → review. Discriminator: the api-in-lookahead contradiction with middleware presented as the gate; FP shape: a self-guarded API surface, why it's review not free-count. The negative (matcher with no api exclusion) is cleared." },
  { id: "N-MW-MATCHER-INCLUDES-API", kind: "negative", cls: "middleware matcher has no /api exclusion", location: "lib/middleware-matcher-safe.ts", match: ["mw-matcher-excludes-api"], note: "#132: lib/middleware-matcher-safe.ts's config.matcher has no 'api' exclusion — /api/* still runs through the middleware auth check. Cleared trivially (no mechanical rule); recorded to complete the corpus pair." },

  // #133 — middleware is the sole authz layer, no defense in depth
  { id: "P-MW-SOLE-AUTHZ", kind: "positive", cls: "middleware is the sole authz layer — no defense-in-depth re-check in the route/data layer", location: "pages/api/admin/dashboard.js", match: ["mw-sole-authz"], expectedTier: "review", note: "#133: pages/api/admin/dashboard.js reads admin_metrics with no session/role check of its own, relying entirely on middleware.ts. It's a SELECT (not insert/update/delete), so the existing harvey-route-noauth mutation rule does not fire here — intentional, keeps this class isolated. Needs defense-in-depth/control-flow reasoning (roadmap §4a: middleware-sole-authz-layer, scan-gaps §2.1) — no mechanical rule. Expected to stay uncaught in the offline gate." },
  { id: "N-MW-DEFENSE-IN-DEPTH", kind: "negative", cls: "route re-checks session/role even though middleware also covers it", location: "pages/api/admin/dashboard-safe.js", match: ["mw-sole-authz"], note: "#133: pages/api/admin/dashboard-safe.js calls getServerSession() and checks the role before returning admin_metrics, in addition to whatever middleware.ts does. Cleared trivially (no mechanical rule); recorded to complete the corpus pair." },

  // #134 — draftMode().enable() reachable with no secret
  { id: "P-DRAFTMODE-NO-SECRET", kind: "positive", cls: "draftMode().enable() reachable with no secret/token check", location: "pages/api/preview/enable.js", match: ["draftmode-no-secret"], expectedTier: "review", note: "#134/#354: pages/api/preview/enable.js calls draftMode().enable() unconditionally — any caller can flip on preview mode. The entry's old \"needs control-flow reasoning\" note overstated it: the fixture is seven lines and the enable() is the first statement (the #264 mislabel pattern). GRADUATED to a mechanical rule (#354): leftover-auth's draftmode-no-secret grep matches a draftMode().enable() with no secret/token comparison (process.env.*SECRET / req.*.secret) anywhere in the file → review. Shallow intra-file: can't see a wrapper's gate, so review not free-count. The negative (secret checked before enable) is cleared." },
  { id: "N-DRAFTMODE-SECRET-CHECKED", kind: "negative", cls: "draftMode().enable() gated by a secret check", location: "pages/api/preview/enable-safe.js", match: ["draftmode-no-secret"], note: "#134: pages/api/preview/enable-safe.js validates req.query.secret against process.env.PREVIEW_SECRET before draftMode().enable() runs. Cleared trivially (no mechanical rule); recorded to complete the corpus pair." },

  // #135 — Host header trusted to build an absolute URL (reset-link poisoning)
  { id: "P-HOST-HEADER-URL", kind: "positive", cls: "Host header trusted to build an absolute URL (reset-link poisoning)", location: "lib/reset-link.js", match: ["host-header-url"], expectedTier: "review", note: "#135: lib/reset-link.js builds the password-reset link from headers().get('host') — an attacker-controlled value — so a spoofed Host redirects the real reset token to the attacker's domain. Needs taint-from-Host-into-URL reasoning — roadmap §4a: host-header-trusted-in-url-construction, no mechanical rule. Expected to stay uncaught in the offline gate." },
  { id: "N-HOST-HEADER-FIXED-ORIGIN", kind: "negative", cls: "reset link built from a fixed allowlisted origin, not the Host header", location: "lib/reset-link-safe.js", match: ["host-header-url"], note: "#135: lib/reset-link-safe.js builds the link from process.env.NEXT_PUBLIC_SITE_URL — headers()/Host is never read. Cleared trivially (no mechanical rule); recorded to complete the corpus pair." },

  // #136 — authz enforced only by a client-component conditional render
  { id: "P-CLIENT-RENDER-AUTHZ", kind: "positive", cls: "authz enforced only by a client-component conditional render; privileged data already shipped", location: "app/admin/page.tsx", match: ["client-render-authz"], expectedTier: "review", note: "#136: app/admin/page.tsx fetches the full admin_metrics dataset unconditionally and passes it to AdminDashboardClient.jsx, whose only gate is `if (!isAdmin) return null` — the data is already in the RSC payload regardless. Distinct from P-SERVER-CLIENT-LEAK (harvey-server-client-leak requires an exact `.select('*').eq(...)` + `{...$DATA}` spread shape; this fixture uses neither an .eq() chain nor a spread, so that rule stays silent). Needs control-flow reasoning (server-component-conditional-client-auth-gate, roadmap §4a) — no mechanical rule. Expected to stay uncaught in the offline gate." },
  { id: "N-SERVER-ROLE-CHECK", kind: "negative", cls: "role checked server-side before the privileged query/fetch runs", location: "app/admin/page-safe.tsx", match: ["client-render-authz"], note: "#136: app/admin/page-safe.tsx checks getServerSession()'s role and redirects BEFORE querying admin_metrics — a non-admin never causes the query to run and nothing reaches the client. Cleared trivially (no mechanical rule); recorded to complete the corpus pair." },
];
