// Batch B17 (#353) — two of the three never-covered dry-run planted bugs graduate to a mechanical
// rule at REVIEW tier: UPDATE-UNSCOPED (a raw UPDATE/DELETE string with no WHERE, leftover-auth
// grep) and COUNTER-RACE (a select→arithmetic→update read-modify-write on one table, the AST
// dataflow detector in src/scan/counter-race.ts). Both fire in runMechanicalScan, so they are
// scored by validate-calibration here; both stay review (a grep can't prove a whole-table write is
// unintended, and the AST can't see a DB-side lock/transaction), never free-count. The third bug
// WEBHOOK-REPLAY does NOT graduate — proving the absence of a replay guard needs whole-handler +
// callee reasoning a mechanical rule can't do FP-safely. As of #425 it is a corpus entry too, at
// the "none" tier (no mechanical rule by design): the single answer key now owns ALL three
// dry-run verdicts, and if a replay/nonce rule ever fires at webhook.js the gate flips it loud.
// See #353, #425, and GROUND-TRUTH.md.

import type { CorpusEntry } from "./types.js";

export const b17RaceUnscopedEntries: CorpusEntry[] = [
  { id: "P-UPDATE-UNSCOPED", kind: "positive", cls: "raw service-role UPDATE/DELETE with no WHERE clause (rewrites every tenant's rows)", location: "pages/api/profile/update.js", match: ["unscoped-write"], expectedTier: "review", note: "#353: pages/api/profile/update.js runs pool.query(\"UPDATE public.profiles SET role = $1\", [role]) on the raw service connection with no WHERE — one request rewrites role on every profile in every tenant. leftover-auth's unscoped-write grep (a raw-SQL UPDATE/DELETE string literal with no WHERE, passed to a .query()/.execute() sink in a route file) → review. Discriminator: the missing WHERE, a textual fact like USING(true) (#333). FP shape: a deliberate admin reset/backfill — why it's review, not free-count. The negative adds WHERE id = $2 and is cleared." },
  { id: "N-UPDATE-SCOPED", kind: "negative", cls: "same raw-pool UPDATE, scoped with WHERE id = $2", location: "pages/api/profile/update-safe.js", match: ["unscoped-write"], note: "#353: pages/api/profile/update-safe.js runs UPDATE public.profiles SET role = $1 WHERE id = $2 on the same pool — the WHERE clause scopes the write to the caller's own row. leftover-auth's unscoped-write re-checks the matched DML for a WHERE token and skips it — no finding. Cleared." },

  { id: "P-COUNTER-RACE", kind: "positive", cls: "non-atomic read-modify-write on a counter (lost-update race)", location: "pages/api/counter/increment.js", match: ["read-modify-write"], expectedTier: "review", note: "#353: pages/api/counter/increment.js selects counters.value into `current`, computes `next = (current?.value ?? 0) + 1`, then updates counters with `value: next` — two concurrent requests both read the old value and one increment is lost. detectCounterRaceFindings (src/scan/counter-race.ts) proves the dataflow (a .select() of a table whose value is written back via .update() after a +/- derivation on the same table) → review. Discriminator: the read→arithmetic→write dataflow, not mere table co-occurrence. FP shape (read-then-write of an UNRELATED fresh value) is cleared by the arithmetic-derived-from-read gate. Stays review: can't see a DB-side lock/transaction." },
  { id: "N-COUNTER-ATOMIC", kind: "negative", cls: "atomic increment via a server-side RPC (value = value + 1 in one statement)", location: "pages/api/counter/increment-safe.js", match: ["read-modify-write"], note: "#353: pages/api/counter/increment-safe.js calls admin.rpc(\"increment_counter\", …) — one server-side statement, no select-then-update read-modify-write pair for the detector to flag. Cleared (no select+update on the same table). Recorded to complete the corpus pair." },

  { id: "P-IDEMPOTENCY-KEY-RANDOM", kind: "positive", cls: "random-per-attempt provider idempotency key", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["random-per-attempt"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: crypto.randomUUID() creates a different Stripe key on every retry, so the same logical charge cannot deduplicate. The finding's evidence names the random-per-attempt classification and the retry-equality falsifier." },
  { id: "P-IDEMPOTENCY-KEY-CLOCK", kind: "positive", cls: "clock-derived provider idempotency key", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["clock-or-attempt-derived"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: Date.now() changes the key between attempts of one booking charge. The stable booking identifier does not rescue a volatile suffix." },
  { id: "P-IDEMPOTENCY-KEY-GLOBAL", kind: "positive", cls: "unsafe global constant provider idempotency key", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["unsafe-global-constant"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: the literal all-charges collides across unrelated charges; presence of a non-empty key is not operation identity." },
  { id: "P-IDEMPOTENCY-KEY-TENANT", kind: "positive", cls: "provider idempotency key omits available tenant scope", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["missing-tenant-scope"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: tenantId is available to the charge function but omitted from the key, so the same booking identifier in two tenants can collide." },
  { id: "P-IDEMPOTENCY-ROLE-OVERLAP", kind: "positive", cls: "tenant provenance is incorrectly reused as entity identity", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["missing-entity-scope", "distinct from tenant provenance"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: chargeWithTenantMisusedAsEntity has only tenantId in a canonical tuple. ProvenOperationKeyContract assigns each immutable origin one disjoint role, so the tenant origin cannot also satisfy the entity requirement." },
  { id: "P-IDEMPOTENCY-FRAMING", kind: "positive", cls: "raw tuple concatenation has no mechanically injective framing", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["collision-prone-key-framing", "separately encode every dynamic term"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: punctuation adjacency is not a proof of injectivity: raw tenant/entity values can shift boundaries. The detector accepts only required-primitive JSON arrays or per-term unshadowed encodeURIComponent framing." },
  { id: "P-IDEMPOTENCY-PROVIDER-DOMAIN-COLLISION", kind: "positive", cls: "different Stripe effects reuse one project-wide operation-key contract", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["cross-operation-key-collision", "ALL ADMITTED PROJECT FILES"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: paymentIntents.create and refunds.create share the same proven shared-effect contract. Proven contracts are accumulated project-wide within Stripe's collision domain rather than reset per function or file." },
  { id: "P-IDEMPOTENCY-LOGICAL-OPERATION-COLLISION", kind: "positive", cls: "different logical operations reuse one method and scoped operation-key contract", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["mechanically-unproven-logical-operation-collision", "depositWithSharedMethodContract", "balanceWithSharedMethodContract", "FALSIFIER:"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: deposit and balance both call paymentIntents.create with the same typed wallet tuple. Provider method equality is not proof that the business effects are one logical operation, so the review finding retains both lexical operation names and a shared-input key inequality falsifier." },
  { id: "P-IDEMPOTENCY-KEY-OPAQUE", kind: "positive", cls: "provider idempotency key semantics hidden behind an opaque helper", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["mechanically-unproven-key-helper"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: local source shows plausible inputs but not how makeProviderKey combines them. The review-tier finding states the local-expression scope and a concrete falsifier instead of claiming safety." },
  { id: "P-IDEMPOTENCY-UNRELATED-OPTION", kind: "positive", cls: "idempotency-looking metadata outside the provider key slot", location: "src/inngest/external-send-idempotency-malformed.ts", match: ["External send without a deterministic idempotency key"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: Stripe metadata.idempotencyNote is unrelated to the provider's idempotencyKey request option. Exact provider-slot extraction prevents the old token-presence false assurance." },
  { id: "N-IDEMPOTENCY-KEY-SCOPED", kind: "negative", cls: "retry-stable tenant/entity/operation key in Stripe and REST provider option shapes", location: "src/inngest/external-send-idempotency-scoped.ts", note: "#1925: both provider shapes combine immutable tenantId and bookingId with a stable operation discriminator. Identical logical retries reproduce one key while a changed tenant, booking, or operation changes it; payload hashing is not required." },
  { id: "N-IDEMPOTENCY-PROVEN-CONTRACT", kind: "negative", cls: "canonical and per-term-encoded contracts remain consistent across files and isolated across providers", location: "src/inngest/external-send-idempotency-scoped.ts", note: "#1925: canonical typed JSON contracts for the same Stripe effect agree across calibration files; the identical charge tuple is independently valid in Resend's separate provider domain; and encoded-receipt proves per-term unshadowed encodeURIComponent framing without raw-boundary ambiguity." },
  { id: "P-IDEMPOTENCY-PROVIDER-LATE-OVERRIDE", kind: "positive", cls: "later Stripe options spread replaces a scoped key with a random-per-attempt key", location: "src/inngest/external-send-idempotency-provider-override-malformed.ts", match: ["random-per-attempt"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: object spread evaluation is ordered. The later unsafeOverride replaces the earlier scoped idempotencyKey at runtime, so the detector must resolve the final provider slot rather than the first matching property." },
  { id: "N-IDEMPOTENCY-PROVIDER-LATE-EXPLICIT", kind: "negative", cls: "later explicit Stripe option replaces unsafe spread defaults with a scoped key", location: "src/inngest/external-send-idempotency-provider-override-safe.ts", note: "#1925: the final explicit idempotencyKey wins over the earlier unsafe defaults. Right-to-left provider-slot resolution must preserve this safe control." },
  { id: "P-IDEMPOTENCY-HEADERS-LATE-OVERRIDE", kind: "positive", cls: "later Headers spread replaces a scoped REST key with a clock-derived key", location: "src/inngest/external-send-idempotency-headers-override-malformed.ts", match: ["clock-or-attempt-derived"], expectedTier: "review", expectedSeverity: "Medium", note: "#1925: the later spread inside new Headers overwrites Idempotency-Key with Date.now(). A first-property scan would silently accept the ineffective scoped header." },
  { id: "N-IDEMPOTENCY-HEADERS-LATE-EXPLICIT", kind: "negative", cls: "later explicit Headers entry replaces unsafe defaults with a scoped REST key", location: "src/inngest/external-send-idempotency-headers-override-safe.ts", note: "#1925: the final explicit Idempotency-Key wins over the earlier spread. Nested Headers resolution must follow runtime overwrite order without flagging the fixed shape." },

  // #425: WEBHOOK-REPLAY joins the corpus at the "none" tier — no mechanical rule by design. This
  // is the single-key home for the "accepted gap" the dry-run scorecard used to assert by hand: it
  // is anchored at the planted handler (webhook.js) and matched on the class (replay/nonce), so the
  // gap holds while nothing of that class fires there, and the gate FAILS LOUD the moment a rule
  // does — the whole point of encoding the gap rather than trusting a comment. No negative sibling:
  // there is no rule to prove FP-safe, so there is nothing to pin a benign lookalike against.
  { id: "P-WEBHOOK-REPLAY-NO-RULE", kind: "positive", cls: "HMAC-verified webhook with no replay/nonce protection", location: "pages/api/webhook.js", match: ["replay", "nonce"], expectedTier: "none", neighbourTaxonomies: ["src.scan.rules.semgrep.harvey-missing-server-only", "src.scan.rules.semgrep.harvey-unchecked-mutation"], note: "#353/#425: pages/api/webhook.js verifies the HMAC signature but never checks a timestamp/nonce, so a captured signed request replays forever (GROUND-TRUTH row 5). SHARED FIXTURE (#1677): harvey-missing-server-only and harvey-unchecked-mutation already fire on pages/api/webhook.js for other classes (MEASURED 2026-07-31, scoreGraduationGuards over a live runMechanicalScan), so they are declared in neighbourTaxonomies and the graduation guard is every OTHER finding on the fixture — the `match` key no longer bounds it. MEASURED LLM-tier: proving a replay guard's ABSENCE is a whole-handler+callee negative — a rule flagging every HMAC webhook without a recognised nonce would FP on handlers that dedupe via an idempotency key, provider-side dedupe, or a DB unique constraint. So no mechanical rule by design: scored an intended gap statically, and if a replay/nonce finding ever fires at webhook.js this entry flips the gate loud, forcing a re-tier to review/high." },
];
