// Batch B2 — framework-CVE + supply-chain manifest hygiene (#71, spec
// docs/design/spec-71-security-corpus.md §"Batch 4 — Framework CVEs" + §"Batch 5 — Supply
// chain / manifest hygiene"). Registers detections that already existed in src/scan/dependencies.ts
// (checkNextVersionCVEs, parseOsvFindings) and src/scan/supply-chain.ts but were unrepresented in
// the corpus, plus one new deterministic manifest check (checkNonRegistryDependencies) and its
// typosquat fixture. The already-registered base-batch dep rows (P-NEXT-CVE-29927, P-NEXT-CVE-RSC,
// P-DEP-CVE, P-SLOPSQUAT, P-POSTINSTALL, N-DEV-DEP) are NOT duplicated here. See GROUND-TRUTH.md §B2.
//
// Tiering: only the two deterministic-syntactic checks are `high` (free count) — an exact CVE
// version-range match (WS-SSRF) and the unpinned-range check. The OSV-backed cache-poisoning
// cluster, the offline edit-distance typosquat, and the non-registry-source check stay `review`
// (a version match / edit-distance / git-source presence isn't proof of exploitability).

import type { CorpusEntry } from "./types.js";

export const b2DepsEntries: CorpusEntry[] = [
  // --- POSITIVES ---
  { id: "P-NEXT-CVE-WS-SSRF", kind: "positive", cls: "Framework CVE — WebSocket-upgrade SSRF", location: "next", manifest: "package.json", match: ["44578"], expectedTier: "high", expectedSeverity: "High", note: "next@^14.2.5 falls in the CVE-2026-44578 range (>=13.4.13 <15.5.16, GHSA-c4j6-fc7j-m34r, CVSS 8.6). checkNextVersionCVEs (src/scan/dependencies.ts) — high. Match on the CVE number to disambiguate from the 29927/RSC entries sharing location 'next'." },
  { id: "P-UNPINNED-DEP", kind: "positive", cls: "Unpinned dependency version range", location: "package.json", match: ["unpinned"], expectedTier: "high", note: "The target's ^-ranged deps (next, react, pg, zod, @supabase/supabase-js, react-dom) trip checkUnpinnedDependencies (src/scan/supply-chain.ts) — a deterministic syntactic fact, high precision. Spec drafted this 'review'; the implemented check is ~100%-precise (an unpinned range IS unpinned), so it lands high, guarded by N-DEP-PINNED." },
  { id: "P-NEXT-CVE-CACHE", kind: "positive", cls: "Framework CVE — cache poisoning (May-2026 batch)", location: "next@14.2.35", match: ["cache poisoning"], expectedTier: "review", note: "OSV-Scanner over the committed lockfile (next resolved to 14.2.35) matches the May-2026 cache-poisoning advisories (e.g. GHSA-wfc6-r584-vfw7). parseOsvFindings tiers every non-curated OSV hit review — a version match isn't proof of exploitability." },
  { id: "P-TYPOSQUAT", kind: "positive", cls: "Typosquat — edit-distance-1 dependency name", location: "package.json", match: ["one edit"], expectedTier: "review", note: "'expres' (a real, published npm package — so checkSlopsquat's registry HEAD stays silent) is Levenshtein-1 from 'express'; checkTyposquat (src/scan/supply-chain.ts) flags it at review (offline corpus match, not a live-registry confirmation)." },
  { id: "P-NONREGISTRY-DEP", kind: "positive", cls: "Non-registry dependency source (git/url/file)", location: "package.json", match: ["non-registry"], expectedTier: "review", note: "'left-pad' pinned to a git+https URL (a real npm name, so checkSlopsquat stays silent) trips the new checkNonRegistryDependencies (src/scan/supply-chain.ts) — review (a git source can be intentional; presence isn't proof of a problem)." },

  // #1213 — the transitive-copyleft class. Modelled on the ATC case the issue was filed from: no
  // manifest in that workspace declares `sharp`, yet its platform binaries are all over the
  // lockfile and three are LGPL-3.0-or-later. Both entries here exist ONLY in
  // targets/calibration/package-lock.json (real published versions and integrity hashes, DATA ONLY
  // — this target is never installed), so nothing about them is reachable from package.json. That
  // is the point: against the manifest-scoped candidate list this check used before #1213, neither
  // was ever a candidate, so the whole class scored silent.
  { id: "P-LICENSE-COPYLEFT-TRANSITIVE", kind: "positive", cls: "Copyleft license reached only through the resolved tree", location: "@img/sharp-libvips-linux-riscv64", manifest: "package.json", match: ["LGPL-3.0-or-later"], expectedTier: "high", expectedSeverity: "Medium", note: "@img/sharp-libvips-linux-riscv64@1.2.4 is LGPL-3.0-or-later (verified against the npm registry 2026-07-27) and is declared by NO manifest — it reaches the tree as an optionalDependency of the equally-transitive sharp@0.34.5. checkLicenseCompliance (src/scan/supply-chain.ts) classifies it high: the SPDX id is self-declared registry/lockfile data, deterministic. Answered from the lockfile's own `license` field, so it scores identically on the offline dry-run path and the live gate." },

  // #1231's transitive plant. checkKnownIoc read the root manifest's prod+dev names only, which
  // looks for the payload in the one place the delivery mechanism does not put it: the canonical
  // incident (event-stream, 2018) put flatmap-stream in the TREE, declared by nobody.
  { id: "P-KNOWN-IOC-TRANSITIVE", kind: "positive", cls: "Known-malicious (IOC) dependency reached only through the resolved tree", location: "package-lock.json (crossenv)", match: ["indicator-of-compromise"], expectedTier: "high", expectedSeverity: "Critical", note: "package-lock.json carries `crossenv`, declared by no manifest in the target. checkKnownIoc (src/scan/supply-chain.ts) matches the curated malware-name feed against the whole resolved tree since #1231 and rates it high — an exact name match on a package published purely as the payload is ground truth, any version. The lockfile entry is deliberately SYNTHETIC (name only: no resolved URL, no integrity, no license, version `0.0.0-synthetic`) because npm took the real package down in 2017, so no honest hash exists to commit — and the name is the only field this check reads. See GROUND-TRUTH.md §B2 transitive-IOC plant." },

  // #1231's OTHER widening. checkKnownIoc and checkTyposquat were widened to the resolved tree in
  // the same PR, but only the IOC half got a calibration row — the typosquat half was held by unit
  // tests alone, so the gate that fails loud on a silent regression did not cover it. This is that
  // row: the same tree-only reach, scored against the name-shape check instead of the name feed.
  { id: "P-TYPOSQUAT-TRANSITIVE", kind: "positive", cls: "Typosquat-shaped name reached only through the resolved tree", location: "package-lock.json (uid)", match: ["reached only through the resolved dependency tree"], expectedTier: "review", note: "package-lock.json carries `uid`, declared by no manifest in the target; it is Levenshtein-1 from `uuid` in checkTyposquat's popular corpus, so the widened check flags it at review AND says in the finding that it is transitive and therefore not the client's to edit. `uid` is a REAL published npm package (registry HEAD 200, verified 2026-07-27) — chosen deliberately so checkSlopsquat stays silent and this row scores the typosquat check alone, the same construction P-TYPOSQUAT uses for `expres`. The lockfile entry is SYNTHETIC (version `0.0.0-synthetic`, no resolved URL or integrity) because nothing here is ever installed and the name is the only field this check reads. Match is on the transitive-reach sentence, not on the name: the declared-manifest positive P-TYPOSQUAT must not be able to satisfy this row. N-IOC-TRANSITIVE-CLEAN is the shared boundary negative — crypto-browserify sits equally transitively and is edit-distance 1 from nothing." },

  // --- DEFERRED-BATCH POSITIVES (#71 follow-up: secondary manifest fixtures) ---
  // These five needed manifest scenarios that can't coexist in the single root package.json, so
  // they live in standalone fixture app-roots under targets/calibration/fixtures/ (an EOL/vulnerable
  // "legacy-app" and a clean "supported-app"), scanned independently by validate-calibration.ts's
  // scanManifestFixtures. See GROUND-TRUTH.md §B2 for the manifest-layout decision.
  { id: "P-NEXT-EOL", kind: "positive", cls: "Framework EOL — unsupported major line", location: "fixtures/legacy-app/package.json", match: ["end-of-life"], expectedTier: "review", note: "legacy-app pins next@12.3.5 (major 12 < the 14.x EOL threshold). checkNextVersionCVEs emits DEP-NEXT-EOL (review — EOL cutoffs shift, per the check's own doctrine). 12.3.5 sits at/above every curated fixed version for its major, so EOL is the only finding it draws — it doesn't also trip the 29927/RSC/WS-SSRF ranges. Match on 'end-of-life' to isolate it from the react-dom/minimist/IOC findings sharing this manifest." },
  { id: "P-REACT-DOM-CVE", kind: "positive", cls: "Framework CVE — react-dom XSS (CVE-2018-6341)", location: "fixtures/legacy-app/package.json", match: ["react-dom"], expectedTier: "review", expectedSeverity: "Medium", note: "legacy-app pins react-dom@16.4.0, inside the CVE-2018-6341 range (>=16.0.0 <16.4.2). checkKnownDependencyCVEs (src/scan/dependencies.ts, curated-range, offline — same pattern as the Next CVEs) flags it review: the range is approximate (backported patch releases 16.0.1/16.1.2/16.2.1/16.3.3 sit inside the affected majors), so it isn't free-count-precise. supported-app's react-dom@18.3.1 is the implicit negative — outside the range, silent." },
  { id: "P-DEP-CVE-CRITICAL", kind: "positive", cls: "Critical dependency CVE (curated, free-count)", location: "fixtures/legacy-app/package.json", match: ["minimist"], expectedTier: "high", expectedSeverity: "Critical", note: "legacy-app pins minimist@1.2.5, below the CVE-2021-44906 fix (1.2.6). checkKnownDependencyCVEs flags it HIGH — the affected range is crisp (a single '< 1.2.6' boundary, no backport exceptions) and the CVE is Critical (CVSS 9.8, prototype pollution). This is the curated critical-CVE promotion path the OSV-only pass lacked (parseOsvFindings tiers every OSV hit review). No other manifest declares minimist, so there's no free-count FP risk." },
  { id: "P-MISSING-LOCKFILE", kind: "positive", cls: "Missing lockfile (standalone project root)", location: "fixtures/legacy-app", match: ["lockfile"], expectedTier: "high", note: "legacy-app is a standalone project root that ships NO lockfile → checkLockfilePresence emits SUP-NO-LOCKFILE (high). Modelled as its own root (not a sub-package of the main target, whose committed lockfile would cover it — the exact conflict that deferred this class). Match on 'lockfile' and a location WITHOUT '/package.json' to keep it apart from the manifest findings in the same fixture dir." },
  { id: "P-KNOWN-IOC-PKG", kind: "positive", cls: "Known-malicious (IOC) dependency", location: "fixtures/legacy-app/package.json", match: ["flatmap-stream"], expectedTier: "high", note: "legacy-app declares flatmap-stream@0.1.1 (the 2018 event-stream-incident crypto-stealer — data only, NEVER installed). checkKnownIoc (src/scan/supply-chain.ts, new) matches it against a curated IOC feed of names published purely as malware → HIGH (any version is malicious, so an exact name match is ground truth). Slopsquat is NOT re-run on the fixture, so this is a pure IOC-feed catch, not a registry 404." },

  // --- NEGATIVES ---
  { id: "N-LICENSE-PERMISSIVE-TRANSITIVE", kind: "negative", cls: "Permissive license reached only through the resolved tree", location: "sharp@0.34.5", manifest: "package.json", note: "sharp@0.34.5 is Apache-2.0 and sits in the tree exactly as transitively as the LGPL binary it pulls in — the FP a 'the tree is unreviewed, flag it' rule throws once #1213 widened the candidate set from ~11 manifest names to the whole resolved tree. Cleared: a permissive SPDX id draws no license finding however deep it sits. Location pinned to the exact coordinate so it cannot substring-match the @img/sharp-* positive." },
  { id: "N-IOC-TRANSITIVE-CLEAN", kind: "negative", cls: "Ordinary transitive dependency, not on the IOC feed", location: "crypto-browserify@3.12.1", note: "crypto-browserify@3.12.1 sits in the lockfile exactly as transitively as the crossenv plant beside it and is not on the curated malware-name feed — the FP a 'the transitive tree is unreviewed, flag it' rule throws once #1231 widened checkKnownIoc and checkTyposquat from ~11 manifest names to the whole resolved tree. Cleared. Its name is also not edit-distance 1 from any popular package, so it doubles as the typosquat boundary for the same widening." },
  { id: "N-DEP-PINNED", kind: "negative", cls: "Exactly-pinned registry dependency", location: "package.json", match: ["lodash"], note: "lodash@4.17.11 is exact-pinned and registry-sourced, so it never appears in the SUP-UNPINNED or SUP-NON-REGISTRY finding's evidence — the pinned-dep FP that a naive 'any dependency is unpinned' rule throws. Cleared (its OSV CVE finding lives at the lockfile location, not package.json, so it can't be mis-attributed here). Doubles as the registry-source negative for P-NONREGISTRY-DEP." },
  { id: "N-SLOPSQUAT-REAL", kind: "negative", cls: "Real popular dependency, similar name", location: "@supabase/supabase-js", note: "@supabase/supabase-js is a real, popular, scoped package (exact-match in checkTyposquat's popular set; a 200 from checkSlopsquat's registry HEAD) — the FP a name-shape heuristic throws on a legitimate scoped dep. Draws no slopsquat/typosquat finding — cleared." },
  { id: "N-NEXT-SUPPORTED", kind: "negative", cls: "Supported framework major line", location: "fixtures/supported-app/package.json", match: ["end-of-life"], note: "supported-app pins next@15.5.16 — a current, fully-patched version. checkNextVersionCVEs draws nothing from it (no EOL, no 29927/RSC/WS-SSRF). The EOL negative that shares the manifest-version conflict with P-NEXT-EOL, now resolved by living in its own fixture root. Match on 'end-of-life' asserts specifically that the EOL check stays silent here." },
  { id: "N-POSTINSTALL-KNOWN", kind: "negative", cls: "Legitimate package with a postinstall (not an IOC)", location: "fixtures/supported-app/package.json", match: ["esbuild", "install"], note: "supported-app declares esbuild@0.21.5 — a hugely-popular package that famously runs a postinstall to fetch its native binary, exactly the trait a 'has install scripts = suspicious' heuristic false-positives on. checkKnownIoc keys on the curated malware-name feed, not on install-script presence, so esbuild is NOT in the set → cleared. The known-legit-postinstall negative that couldn't be modelled against the single aggregate checkInstallScripts review finding, now distinct against the name-based IOC check." },
];
