// Batch B2 — framework-CVE + supply-chain manifest hygiene (#71, spec
// docs/design/spec-71-security-corpus.md §"Batch 4 — Framework CVEs" + §"Batch 5 — Supply
// chain / manifest hygiene"). Registers detections that already existed in src/scan/dependencies.ts
// (checkNextVersionCVEs, parseOsvFindings) and src/scan/supply-chain.ts but were unrepresented in
// the corpus, plus one new deterministic manifest check (checkNonRegistryDependencies) and its
// typosquat fixture. The already-registered base-batch dep rows (P-NEXT-CVE-29927, P-NEXT-CVE-RSC,
// P-DEP-CVE, P-SLOPSQUAT, P-POSTINSTALL, N-DEV-DEP) are NOT duplicated here. See GROUND-TRUTH.md §B2.
//
// Tiering: only the two deterministic-syntactic checks are `high` (free count) — an exact CVE
// version-range match (WS-SSRF) and the unpinned-range check. The OSV-backed cache-poisoning
// cluster, the offline edit-distance typosquat, and the non-registry-source check stay `review`
// (a version match / edit-distance / git-source presence isn't proof of exploitability).

import type { CorpusEntry } from "./types.js";

export const b2DepsEntries: CorpusEntry[] = [
  // --- POSITIVES ---
  { id: "P-NEXT-CVE-WS-SSRF", kind: "positive", cls: "Framework CVE — WebSocket-upgrade SSRF", location: "next", manifest: "package.json", match: ["44578"], expectedTier: "high", expectedSeverity: "High", note: "next@^14.2.5 falls in the CVE-2026-44578 range (>=13.4.13 <15.5.16, GHSA-c4j6-fc7j-m34r, CVSS 8.6). checkNextVersionCVEs (src/scan/dependencies.ts) — high. Match on the CVE number to disambiguate from the 29927/RSC entries sharing location 'next'." },
  { id: "P-UNPINNED-DEP", kind: "positive", cls: "Unpinned dependency version range", location: "package.json", match: ["unpinned"], expectedTier: "high", note: "The target's ^-ranged deps (next, react, pg, zod, @supabase/supabase-js, react-dom) trip checkUnpinnedDependencies (src/scan/supply-chain.ts) — a deterministic syntactic fact, high precision. Spec drafted this 'review'; the implemented check is ~100%-precise (an unpinned range IS unpinned), so it lands high, guarded by N-DEP-PINNED." },
  { id: "P-NEXT-CVE-CACHE", kind: "positive", cls: "Framework CVE — cache poisoning (May-2026 batch)", location: "next@14.2.35", match: ["cache poisoning"], expectedTier: "review", note: "OSV-Scanner over the committed lockfile (next resolved to 14.2.35) matches the May-2026 cache-poisoning advisories (e.g. GHSA-wfc6-r584-vfw7). parseOsvFindings tiers every non-curated OSV hit review — a version match isn't proof of exploitability." },
  { id: "P-TYPOSQUAT", kind: "positive", cls: "Typosquat — edit-distance-1 dependency name", location: "package.json", match: ["one edit"], expectedTier: "review", note: "'expres' (a real, published npm package — so checkSlopsquat's registry HEAD stays silent) is Levenshtein-1 from 'express'; checkTyposquat (src/scan/supply-chain.ts) flags it at review (offline corpus match, not a live-registry confirmation)." },
  { id: "P-NONREGISTRY-DEP", kind: "positive", cls: "Non-registry dependency source (git/url/file)", location: "package.json", match: ["non-registry"], expectedTier: "review", note: "'left-pad' pinned to a git+https URL (a real npm name, so checkSlopsquat stays silent) trips the new checkNonRegistryDependencies (src/scan/supply-chain.ts) — review (a git source can be intentional; presence isn't proof of a problem)." },

  // --- DEFERRED-BATCH POSITIVES (#71 follow-up: secondary manifest fixtures) ---
  // These five needed manifest scenarios that can't coexist in the single root package.json, so
  // they live in standalone fixture app-roots under targets/calibration/fixtures/ (an EOL/vulnerable
  // "legacy-app" and a clean "supported-app"), scanned independently by validate-calibration.ts's
  // scanManifestFixtures. See GROUND-TRUTH.md §B2 for the manifest-layout decision.
  { id: "P-NEXT-EOL", kind: "positive", cls: "Framework EOL — unsupported major line", location: "fixtures/legacy-app/package.json", match: ["end-of-life"], expectedTier: "review", note: "legacy-app pins next@12.3.5 (major 12 < the 14.x EOL threshold). checkNextVersionCVEs emits DEP-NEXT-EOL (review — EOL cutoffs shift, per the check's own doctrine). 12.3.5 sits at/above every curated fixed version for its major, so EOL is the only finding it draws — it doesn't also trip the 29927/RSC/WS-SSRF ranges. Match on 'end-of-life' to isolate it from the react-dom/minimist/IOC findings sharing this manifest." },
  { id: "P-REACT-DOM-CVE", kind: "positive", cls: "Framework CVE — react-dom XSS (CVE-2018-6341)", location: "fixtures/legacy-app/package.json", match: ["react-dom"], expectedTier: "review", expectedSeverity: "Medium", note: "legacy-app pins react-dom@16.4.0, inside the CVE-2018-6341 range (>=16.0.0 <16.4.2). checkKnownDependencyCVEs (src/scan/dependencies.ts, curated-range, offline — same pattern as the Next CVEs) flags it review: the range is approximate (backported patch releases 16.0.1/16.1.2/16.2.1/16.3.3 sit inside the affected majors), so it isn't free-count-precise. supported-app's react-dom@18.3.1 is the implicit negative — outside the range, silent." },
  { id: "P-DEP-CVE-CRITICAL", kind: "positive", cls: "Critical dependency CVE (curated, free-count)", location: "fixtures/legacy-app/package.json", match: ["minimist"], expectedTier: "high", expectedSeverity: "Critical", note: "legacy-app pins minimist@1.2.5, below the CVE-2021-44906 fix (1.2.6). checkKnownDependencyCVEs flags it HIGH — the affected range is crisp (a single '< 1.2.6' boundary, no backport exceptions) and the CVE is Critical (CVSS 9.8, prototype pollution). This is the curated critical-CVE promotion path the OSV-only pass lacked (parseOsvFindings tiers every OSV hit review). No other manifest declares minimist, so there's no free-count FP risk." },
  { id: "P-MISSING-LOCKFILE", kind: "positive", cls: "Missing lockfile (standalone project root)", location: "fixtures/legacy-app", match: ["lockfile"], expectedTier: "high", note: "legacy-app is a standalone project root that ships NO lockfile → checkLockfilePresence emits SUP-NO-LOCKFILE (high). Modelled as its own root (not a sub-package of the main target, whose committed lockfile would cover it — the exact conflict that deferred this class). Match on 'lockfile' and a location WITHOUT '/package.json' to keep it apart from the manifest findings in the same fixture dir." },
  { id: "P-KNOWN-IOC-PKG", kind: "positive", cls: "Known-malicious (IOC) dependency", location: "fixtures/legacy-app/package.json", match: ["flatmap-stream"], expectedTier: "high", note: "legacy-app declares flatmap-stream@0.1.1 (the 2018 event-stream-incident crypto-stealer — data only, NEVER installed). checkKnownIoc (src/scan/supply-chain.ts, new) matches it against a curated IOC feed of names published purely as malware → HIGH (any version is malicious, so an exact name match is ground truth). Slopsquat is NOT re-run on the fixture, so this is a pure IOC-feed catch, not a registry 404." },

  // --- NEGATIVES ---
  { id: "N-DEP-PINNED", kind: "negative", cls: "Exactly-pinned registry dependency", location: "package.json", match: ["lodash"], note: "lodash@4.17.11 is exact-pinned and registry-sourced, so it never appears in the SUP-UNPINNED or SUP-NON-REGISTRY finding's evidence — the pinned-dep FP that a naive 'any dependency is unpinned' rule throws. Cleared (its OSV CVE finding lives at the lockfile location, not package.json, so it can't be mis-attributed here). Doubles as the registry-source negative for P-NONREGISTRY-DEP." },
  { id: "N-SLOPSQUAT-REAL", kind: "negative", cls: "Real popular dependency, similar name", location: "@supabase/supabase-js", note: "@supabase/supabase-js is a real, popular, scoped package (exact-match in checkTyposquat's popular set; a 200 from checkSlopsquat's registry HEAD) — the FP a name-shape heuristic throws on a legitimate scoped dep. Draws no slopsquat/typosquat finding — cleared." },
  { id: "N-NEXT-SUPPORTED", kind: "negative", cls: "Supported framework major line", location: "fixtures/supported-app/package.json", match: ["end-of-life"], note: "supported-app pins next@15.5.16 — a current, fully-patched version. checkNextVersionCVEs draws nothing from it (no EOL, no 29927/RSC/WS-SSRF). The EOL negative that shares the manifest-version conflict with P-NEXT-EOL, now resolved by living in its own fixture root. Match on 'end-of-life' asserts specifically that the EOL check stays silent here." },
  { id: "N-POSTINSTALL-KNOWN", kind: "negative", cls: "Legitimate package with a postinstall (not an IOC)", location: "fixtures/supported-app/package.json", match: ["esbuild", "install"], note: "supported-app declares esbuild@0.21.5 — a hugely-popular package that famously runs a postinstall to fetch its native binary, exactly the trait a 'has install scripts = suspicious' heuristic false-positives on. checkKnownIoc keys on the curated malware-name feed, not on install-script presence, so esbuild is NOT in the set → cleared. The known-legit-postinstall negative that couldn't be modelled against the single aggregate checkInstallScripts review finding, now distinct against the name-based IOC check." },
];
