// Batch B3 — injection & code-execution family (#71, spec §"Batch 1 — Injection & code-execution").
// Custom Semgrep taint rules (src/scan/rules/semgrep/injection.yml) scored against targets/
// calibration. Tiering follows the locked preamble: only ~100%-precision sinks are `high` (free
// count) — a raw-SQL-executor RPC, `exec`/`execSync` of a request string, and `eval`/`new
// Function` of request input. The heuristic sinks (PostgREST string filters, recursive merge,
// deserialize, XXE options, path traversal, zip-slip, SSTI, ReDoS, log forging) are `review`.
// SQLi-via-template-literal (P-SQLI-CONCAT) and its safe lookalike N-PARAM-QUERY already ship in
// base.entries.ts; the ReDoS-safe / static-fs negatives (N-REDOS-SAFE, N-FS-STATIC) too. See
// GROUND-TRUTH.md §B3.

import type { CorpusEntry } from "./types.js";

export const b3InjectionEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-SQLI-RPC", kind: "positive", cls: "SQLi via raw-SQL-executor RPC", location: "report.js", match: ["rpc", "sql"], expectedTier: "high", note: "req.query.id interpolated into a SQL string run via admin.rpc('exec_sql', { query }) in pages/api/report.js. harvey-sql-injection-rpc gates the sink on raw-SQL-executor function names (exec_sql/execute/run_sql) → high." },
  { id: "P-CMD-INJECTION", kind: "positive", cls: "OS command injection (exec)", location: "convert.js", match: ["command"], expectedTier: "high", note: "req.query.f interpolated into exec(`convert ${f} ...`) in pages/api/convert.js — child_process.exec spawns a shell. harvey-command-injection taint (req → exec/execSync string) → high. This is the CWE-78 shell-STRING shape (#983)." },
  { id: "P-ARG-INJECTION", kind: "positive", cls: "Argument injection (argv-array, CWE-88)", location: "git-clone.js", match: ["argument"], expectedTier: "review", note: "#983: req.query.repo passed as an argv-array element to execFile('git', ['clone', repo, …]) with NO shell in pages/api/git-clone.js — argument injection (a --flag value is read by git), CWE-88, distinct from the CWE-78 shell-string exec. harvey-argument-injection taint → review." },
  { id: "P-EVAL-CODE-INJ", kind: "positive", cls: "Code injection via eval", location: "calc.js", match: ["eval", "code-injection"], expectedTier: "high", note: "eval(req.body.expr) in pages/api/calc.js — arbitrary code execution. harvey-code-injection-eval taint (req → eval/new Function) → high." },
  { id: "P-POSTGREST-FILTER-INJ", kind: "positive", cls: "PostgREST filter injection", location: "find.js", match: ["postgrest", "filter"], expectedTier: "review", note: "req.query.n interpolated into a string .or(`name.eq.${n}`) in pages/api/find.js. harvey-postgrest-filter-injection taint → review (blast radius scoped to the table)." },
  { id: "P-PROTO-POLLUTION", kind: "positive", cls: "Prototype pollution via recursive merge", location: "merge.js", match: ["prototype", "pollution"], expectedTier: "review", note: "lodash.merge(config, req.body) in lib/merge.js — a __proto__ key mutates Object.prototype. harvey-prototype-pollution taint (req.body → merge/defaultsDeep) → review." },
  { id: "P-INSECURE-DESERIALIZE", kind: "positive", cls: "Unsafe deserialization", location: "import.js", match: ["deserial"], expectedTier: "review", note: "unserialize(req.body.data) in pages/api/import.js — node-serialize executes an embedded function body. harvey-unsafe-deserialization taint → review." },
  { id: "P-XXE", kind: "positive", cls: "XXE (external entities enabled)", location: "xml.js", match: ["xxe"], expectedTier: "review", note: "xml2js parseStringPromise(req.body, { noent: true }) in pages/api/xml.js resolves external entities. harvey-xxe pattern (noent/resolveEntities true) → review." },
  { id: "P-PATH-TRAVERSAL", kind: "positive", cls: "Path traversal", location: "file.js", match: ["traversal"], expectedTier: "review", note: "req.query.name joined into path.join('/var/data/uploads', name) then fs.readFileSync in pages/api/file.js. harvey-path-traversal taint (req → fs read/write; path.basename is a sanitizer) → review." },
  { id: "P-ZIP-SLIP", kind: "positive", cls: "Zip-slip archive traversal", location: "unzip.js", match: ["zip-slip", "zip"], expectedTier: "review", note: "fs.writeFileSync(path.join(outDir, entry.entryName), ...) with no containment check in lib/unzip.js. harvey-zip-slip pattern → review." },
  { id: "P-SSTI", kind: "positive", cls: "Server-side template injection", location: "render.js", match: ["template-injection", "template"], expectedTier: "review", note: "ejs.render(req.body.tpl, ...) in pages/api/render.js — user controls the template source (SSTI → RCE on EJS). harvey-template-injection taint → review." },
  { id: "P-SSTI-APPROUTER", kind: "positive", cls: "SSTI via App Router await req.json() template source", location: "ar-ssti/route", match: ["template-injection", "template"], expectedTier: "review", note: "#570: app/api/ar-ssti/route.ts renders ejs.render(String(template ?? ''), ...) where const { template } = await req.json() — the App Router body controls the template SOURCE. Before #570 harvey-template-injection's sources were Express-only (req.query/body/params), so this pure-App-Router SSTI (SuperRedHat F-12 SSTI facet) went dark. harvey-template-injection taint → review." },
  { id: "P-REDOS", kind: "positive", cls: "ReDoS (catastrophic backtracking)", location: "parse.js", match: ["redos"], expectedTier: "review", note: "new RegExp('^(a+)+$') in lib/parse.js — nested quantifier. harvey-redos (metavariable-regex on the nested-quantifier shape) → review." },
  { id: "P-LOG-INJECTION", kind: "positive", cls: "Log injection / forging", location: "track.js", match: ["log-injection"], expectedTier: "review", note: "console.log(`... ${req.query.u} ...`) in pages/api/track.js — CR/LF log forging. harvey-log-injection taint → review (common shape, low severity)." },

  // #984: cookies/headers as taint sources. Before #984 the request source set was only
  // req.query/body/params/searchParams, so any injection entering through req.cookies/req.headers
  // went dark. These prove a cookie/header source reaches a free-count sink, and that the new
  // sources don't over-fire on a parameterized query.
  { id: "P-SQLI-COOKIE-SOURCE", kind: "positive", cls: "SQLi via req.cookies source", location: "cookie-report.js", match: ["sql"], expectedTier: "high", note: "#984: req.cookies.session_token interpolated into a raw SQL string reaching pool.query in pages/api/cookie-report.js. harvey-sql-injection-template taint with the new req.cookies source → high." },
  { id: "P-CMD-HEADER-SOURCE", kind: "positive", cls: "Command injection via req.headers source", location: "header-exec.js", match: ["command"], expectedTier: "high", note: "#984: req.headers['x-forwarded-host'] interpolated into exec(`nslookup ${host}`) in pages/api/header-exec.js. harvey-command-injection taint with the new req.headers source → high." },

  // #985: widened injection SINK coverage — SSRF via the node http/https clients (not just fetch),
  // XXE via a libxmljs parse call (not just the parser option), and generic Mongo NoSQL injection.
  { id: "P-SSRF-HTTP-NODE", kind: "positive", cls: "SSRF via node http.get client", location: "ssrf-http.js", match: ["ssrf"], expectedTier: "review", note: "#985: req.query.url fetched via http.get in pages/api/ssrf-http.js — harvey-ssrf-fetch only matched fetch() before #985; the http/https/axios/request sinks were added. → review." },
  { id: "P-XXE-LIBXMLJS", kind: "positive", cls: "XXE via libxmljs parse call", location: "xxe-parse.js", match: ["xxe"], expectedTier: "review", note: "#985: req.body.xml parsed via libxmljs.parseXml in pages/api/xxe-parse.js. harvey-xxe only matched the noent/resolveEntities parser OPTION; harvey-xxe-parse taints the parse CALL (libxmljs/DOMParser fed request input). → review." },
  { id: "P-NOSQL-REGEX", kind: "positive", cls: "NoSQL (Mongo) injection via $regex operator", location: "nosql-find.js", match: ["nosql", "data query logic"], expectedTier: "review", note: "#985: req.query.name placed under a Mongo $regex operator in findOne in pages/api/nosql-find.js. harvey-nosql-injection taints request input reaching a $where/$regex/$ne/$gt operator. → review (generic Mongo detector; harvey-postgrest-filter-injection is PostgREST-specific)." },

  // #986: transformation-sanitizer (a1) — the unguarded twins that must STILL fire (a sanitizer
  // must not swallow a real finding). The guarded negatives that must now clear are below.
  { id: "P-XSS-TEMPLATE-LITERAL", kind: "positive", cls: "Reflected XSS via HTML template literal to res.send", location: "xss-template-literal.js", match: ["html-template"], expectedTier: "review", note: "#986: req.query.name interpolated raw into an HTML template literal handed to res.send in pages/api/xss-template-literal.js — reflected XSS. harvey-html-template-literal taint → review. Unguarded twin proving the new #986 escaper sanitizer doesn't swallow a real finding." },

  // #987: taint source-pattern robustness — the same request sources reached via method-form,
  // destructured, bracket, and multi-hop/aliased shapes. Measured: the method form needed the new
  // req.get/req.header pattern; destructure/bracket/multi-hop propagate through semgrep taint once
  // the base object is a source. All four fire at the high free-count sink.
  { id: "P-CMD-METHODFORM-SOURCE", kind: "positive", cls: "Command injection via req.get() method-form source", location: "header-getter-exec.js", match: ["command"], expectedTier: "high", note: "#987: req.get('x-forwarded-for') (Express method form) reaches exec() in pages/api/header-getter-exec.js. harvey-command-injection with the new req.get/req.header method-form source → high." },
  { id: "P-SQLI-MULTIHOP-SOURCE", kind: "positive", cls: "SQLi via multi-hop/aliased req.headers source", location: "multihop-sql.js", match: ["sql"], expectedTier: "high", note: "#987: taint aliased (const h = req.headers) then hopped (const token = h.authorization) before the SQL string in pages/api/multihop-sql.js. Semgrep taint dataflow recovers the flow once req.headers is a source → high." },
  { id: "P-SQLI-DESTRUCTURE-SOURCE", kind: "positive", cls: "SQLi via destructured req.cookies source", location: "destructure-sql.js", match: ["sql"], expectedTier: "high", note: "#987: const { id } = req.cookies then interpolated into the SQL string in pages/api/destructure-sql.js — a destructuring source form recovered by semgrep taint once req.cookies is a source → high." },
  { id: "P-CMD-BRACKET-SOURCE", kind: "positive", cls: "Command injection via bracket-access req.query source", location: "bracket-exec.js", match: ["command"], expectedTier: "high", note: "#987: req.query['host'] (bracket access, not dot form) reaches exec() in pages/api/bracket-exec.js — recovered by semgrep taint once req.query is a source → high." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-HEADER-PARAM-QUERY", kind: "negative", cls: "Header value passed as a bound param", location: "header-param.js", note: "#984: req.headers['x-tenant-id'] passed as a $1 bound parameter in pages/api/header-param.js — never interpolated into the SQL string. harvey-sql-injection-template focuses the sink on the SQL text arg, so the new cookies/headers sources must not FP here. Regression guard mirroring N-PARAM-QUERY for the #984 sources." },
  { id: "N-SSRF-HTTP-FIXED", kind: "negative", cls: "node https client called with a fixed URL", location: "ssrf-http-safe.js", match: ["ssrf"], note: "#985: https.get('https://cdn.example.com/status.json') in pages/api/ssrf-http-safe.js — a fixed non-request URL, no taint reaches the sink. Regression guard that the new http/https/axios sinks don't fire without a tainted source (and that the searchParams .get source no longer self-matches https.get)." },
  { id: "N-XXE-PARSE-FIXED", kind: "negative", cls: "libxmljs parse of a constant XML string", location: "xxe-parse-safe.js", match: ["xxe"], note: "#985: libxmljs.parseXml('<root>…</root>') in pages/api/xxe-parse-safe.js — a constant, not request input. harvey-xxe-parse is taint-gated, so the parse-call sink stays dark. Regression guard." },
  { id: "N-NOSQL-EQ-LOOKUP", kind: "negative", cls: "Plain Mongo equality lookup by id", location: "nosql-find-safe.js", match: ["nosql", "data query logic"], note: "#985: findOne({ _id: id }) in pages/api/nosql-find-safe.js — the request value is an ordinary field VALUE, not fed into a $-operator. harvey-nosql-injection requires the tainted value to reach a Mongo operator, so an ordinary id lookup stays dark. Keeps the rule off routine scoped queries." },
  // #986: numeric-coercion / escaper transformation sanitizers ((a1) subset) — each guarded twin
  // must now clear where its unguarded twin still fires (proven above).
  { id: "N-SQLI-PARSEINT", kind: "negative", cls: "SQLi cleared by parseInt coercion", location: "sqli-parseint-safe.js", match: ["sql"], note: "#986: parseInt(req.query.id, 10) interpolated into the SQL string in pages/api/sqli-parseint-safe.js — a number can't carry SQL metacharacters. harvey-sql-injection-template registers parseInt/parseFloat/Number as sanitizers — cleared deterministically (no LLM pass). Regression guard for the (a1) numeric sanitizer." },
  { id: "N-SQLI-PARSEFLOAT", kind: "negative", cls: "SQLi cleared by parseFloat coercion", location: "sqli-parsefloat-safe.js", match: ["sql"], note: "#986: parseFloat(req.query.amount) interpolated into the SQL string in pages/api/sqli-parsefloat-safe.js — coerced to a number, safe. harvey-sql-injection-template parseFloat sanitizer — cleared." },
  { id: "N-SQLI-NUMBER", kind: "negative", cls: "SQLi cleared by Number() coercion", location: "sqli-number-safe.js", match: ["sql"], note: "#986: Number(req.query.page) interpolated into the SQL string in pages/api/sqli-number-safe.js — coerced to a number, safe. harvey-sql-injection-template Number sanitizer — cleared." },
  { id: "N-XSS-TEMPLATE-ESCAPED", kind: "negative", cls: "Template-literal XSS cleared by escapeHtml", location: "xss-template-literal-safe.js", match: ["html-template"], note: "#986: escapeHtml(req.query.name) interpolated into the HTML template literal in pages/api/xss-template-literal-safe.js — the XSS is neutralized. harvey-html-template-literal now registers escapeHtml/escape/DOMPurify.sanitize/sanitizeHtml/sanitize as sanitizers — cleared. Regression guard for the (a1) escaper sanitizer." },
  { id: "N-METHODFORM-PARAM-QUERY", kind: "negative", cls: "Method-form header value passed as a bound param", location: "header-getter-safe.js", match: ["sql"], note: "#987: req.get('x-tenant-id') passed as a $1 bound parameter in pages/api/header-getter-safe.js — never interpolated. The new method-form source must not FP on a parameterized query. Regression guard for the #987 sources." },
  { id: "N-CMD-SAFE", kind: "negative", cls: "execFile with argv array (no shell)", location: "img.js", note: "execFile('convert', [inputPath, ...]) in lib/img.js — discrete argv, no shell, and inputPath is a function param (NOT a request source). harvey-command-injection fires only on exec/execSync of a string, and harvey-argument-injection (CWE-88, #983) is taint-gated so a non-request argv also clears — cleared by both." },
  { id: "N-ARG-INJECTION-FIXED", kind: "negative", cls: "execFile argv with a fixed constant arg", location: "git-clone-safe.js", match: ["argument"], note: "#983: execFile('git', ['clone', 'https://github.com/example/repo.git', …]) in pages/api/git-clone-safe.js — a constant repo URL, no request taint reaches the argv array. harvey-argument-injection is taint-gated — cleared. Regression guard that the CWE-88 rule doesn't fire on every execFile." },
  { id: "N-EVAL-JSON", kind: "negative", cls: "JSON.parse, not eval", location: "cfg.js", note: "JSON.parse(req.body) in lib/cfg.js parses data, cannot execute. harvey-code-injection-eval fires only on eval/new Function — cleared." },
  { id: "N-PROTO-SAFE", kind: "negative", cls: "Shallow Object.assign of picked fields", location: "opts.js", note: "Object.assign({}, DEFAULTS, {theme, pageSize}) in lib/opts.js — shallow, explicit fields, no recursive merge. harvey-prototype-pollution fires only on merge/defaultsDeep/mergeWith — cleared." },
  { id: "N-XXE-SAFE", kind: "negative", cls: "XML parse with entities disabled", location: "xml-safe.js", note: "xml2js parse with { noent: false } in lib/xml-safe.js — hardened. harvey-xxe fires only on noent/resolveEntities true — cleared." },
  { id: "N-PATH-BASENAME", kind: "negative", cls: "path.basename-sanitized file read", location: "dl.js", note: "path.basename(req.query.f) strips directory components before the join in pages/api/dl.js. harvey-path-traversal registers path.basename as a sanitizer — cleared." },
  { id: "N-RPC-PARAM", kind: "negative", cls: "Parameterized Supabase RPC", location: "rep.js", note: "admin.rpc('report_total', { uid }) in pages/api/rep.js — a normal RPC with a bound argument (PostgREST parameterizes it). harvey-sql-injection-rpc fires only on raw-SQL-executor RPC names — cleared." },
  { id: "N-SSTI-APPROUTER-FIXED", kind: "negative", cls: "App Router render of a fixed server-owned template", location: "ar-ssti-safe", match: ["template-injection", "template"], note: "#570: app/api/ar-ssti-safe/route.ts renders a fixed constant template (NOTE_TEMPLATE); only the DATA passed to it comes from await req.json(). harvey-template-injection taints the template SOURCE argument (the first arg), which is the constant here, so no request taint reaches the sink — cleared. Regression guard: confirms the new await-req.json() source doesn't over-fire when only template data (not the template) is user-controlled." },

  // #989: (a2) VALIDATOR-GUARD sanitizer — the tainted value is GATED by a control-flow check that
  // returns on failure, rather than transformed. The three positives below are the soundness half:
  // each wears the same guard SHAPE as a safe twin but is a real injection, so a guard model that
  // ignores anchoring, class polarity, or the early return silently clears a live bug.
  { id: "N-SQLI-REGEX-GUARD", kind: "negative", cls: "SQLi cleared by an anchored allowlist-regex guard", location: "sqli-regex-guard-safe.js", match: ["sql"], note: "#989: `if (!/^[a-zA-Z0-9_]+$/.test(col)) { …; return; }` gates the sort key before it is interpolated in pages/api/sqli-regex-guard-safe.js — nothing outside the allowlist can reach the SQL string. harvey-sql-injection-template registers the whole guard STATEMENT as a by-side-effect sanitizer — cleared deterministically (no LLM pass). Regression guard for the (a2) validator-guard sanitizer." },
  { id: "N-SQLI-ENUM-GUARD", kind: "negative", cls: "SQLi cleared by an enum-allowlist guard", location: "sqli-enum-guard-safe.js", match: ["sql"], note: "#989: `if (![\"title\",\"created_at\",\"id\"].includes(col)) { …; return; }` in pages/api/sqli-enum-guard-safe.js — only one of three constants can reach the SQL string. The .includes allowlist arm of the (a2) guard sanitizer — cleared." },
  { id: "N-CMD-ENUM-GUARD", kind: "negative", cls: "Command injection cleared by an enum-allowlist guard", location: "cmd-enum-guard-safe.js", match: ["command"], note: "#989: the same enum-allowlist early-return guard applied to an execSync sink in pages/api/cmd-enum-guard-safe.js. Proves the (a2) guard sanitizer generalizes past SQL to the command-injection rule — cleared, while the unguarded twin (convert.js, P-CMD-INJECTION) still fires." },
  { id: "P-SQLI-DENYLIST-GUARD", kind: "positive", cls: "SQLi behind a NEGATED-class (denylist) guard", location: "sqli-denylist-guard.js", match: ["sql"], expectedTier: "high", note: "#989 SOUNDNESS: `/^[^\\x00-\\x1f]+$/` is anchored and returns on failure — the (a2) safe-twin shape — but the class is NEGATED, so it is a denylist that strips only control characters while quotes/semicolons/comment markers pass. A real injection. The guard sanitizer's metavariable-regex requires a POSITIVE class, so this must STILL fire at high." },
  { id: "P-SQLI-UNANCHORED-GUARD", kind: "positive", cls: "SQLi behind an unanchored allowlist regex", location: "sqli-unanchored-guard.js", match: ["sql"], expectedTier: "high", note: "#989 SOUNDNESS: `/[a-zA-Z0-9_]+/` has a positive class and returns on failure, but is UNANCHORED — it matches anywhere, so `id; drop table documents--` passes on its leading `id`. A broken safeguard, not a sanitizer. The guard sanitizer requires ^…$ anchoring, so this must STILL fire at high." },
  { id: "P-SQLI-GUARD-NO-RETURN", kind: "positive", cls: "SQLi where the validator's failure branch does not return", location: "sqli-guard-no-return.js", match: ["sql"], expectedTier: "high", note: "#989 SOUNDNESS: the allowlist test is anchored and positive, but the failure branch only logs — execution falls through to the query with the rejected value intact. The guard sanitizer matches the whole guard STATEMENT (test AND early return), not the bare test expression, so this must STILL fire at high. This is the case a naive `pattern: $RE.test($X)` sanitizer silently clears." },
  { id: "P-SQLI-MFLAG-GUARD", kind: "positive", cls: "SQLi behind an anchored allowlist neutered by the /m flag", location: "sqli-mflag-guard.js", match: ["sql"], expectedTier: "high", note: "#1066 SOUNDNESS: the regex is anchored AND its class is positive AND the failure branch returns — it satisfies every #989 constraint — but the /m flag makes ^ and $ match at line breaks, so `/^[a-zA-Z0-9_]+$/m.test(\"id\\n; drop table documents--\")` is TRUE and the payload reaches the SQL string. The (a2) sanitizer's flag group was `[a-z]*`, which admitted `m` at 24 rule sites; it is now `[isuvy]*`, so this must STILL fire at high." },
  { id: "P-SEMGREP-VENDOR-SCOPE", kind: "positive", cls: "Command injection in a directory semgrep's default ignore set drops", location: "vendor/legacy-widget.js", match: ["command"], expectedTier: "high", note: "#1066 SCOPE: vendor/legacy-widget.js is an ordinary request→execSync command injection, planted in a directory semgrep never scanned. MEASURED 2026-07-25 with an identical file copied into eight directories and only `--exclude node_modules` passed: `tests/`, `test/`, `vendor/`, `dist/`, `build/` were never scanned and never listed — 5 of 8 silently dropped, and vendor/ is real shipped code. Harvey now passes --x-ignore-semgrepignore-files (8 of 8), and whatever is STILL unscanned is counted in SEM-SCOPE-00 rather than reading as clean. The end-to-end control for that: if the flag ever stops working this positive goes dark." },

  // #1027: the two guard forms #989 measured but did not model — a SCHEMA validator (zod
  // safeParse + early return on !success) and a Set-backed allowlist. Same structure as the block
  // above: one clearing negative per form, and one positive per soundness constraint. The schema
  // form adds a constraint the bare-regex form does not have — a schema can be well-formed and
  // still accept everything (`z.string()`), so "a schema was used" is not itself a sanitizer.
  { id: "N-CMD-ZOD-GUARD", kind: "negative", cls: "Command injection cleared by a zod schema with an anchored allowlist regex", location: "cmd-zod-guard-safe.js", match: ["command"], note: "#1027: `z.string().regex(/^[a-z]+$/).safeParse(req.query.action)` with an early return on !success in pages/api/cmd-zod-guard-safe.js, and the shell reads `parsed.data` — the value the SCHEMA produced. The schema-validator arm of the (a2) guard sanitizer — cleared. Measured as the largest unmodeled guard sub-population in the #989 census and the idiomatic Next/Express shape." },
  { id: "N-CMD-ZOD-ENUM-GUARD", kind: "negative", cls: "Command injection cleared by a z.enum membership schema", location: "cmd-zod-enum-guard-safe.js", match: ["command"], note: "#1027: `z.enum([\"status\",\"uptime\",\"whoami\"]).safeParse(...)` in pages/api/cmd-zod-enum-guard-safe.js — exact-match membership, so `parsed.data` can only be one of three constants. The enum arm of the schema-validator sanitizer — cleared." },
  { id: "N-CMD-SET-GUARD", kind: "negative", cls: "Command injection cleared by a Set-backed allowlist guard", location: "cmd-set-guard-safe.js", match: ["command"], note: "#1027: `if (!ALLOWED_ACTIONS.has(cmd)) { …; return; }` in pages/api/cmd-set-guard-safe.js — the same exact-match membership test as the shipped `.includes` arm, expressed on a Set. Cleared." },
  { id: "P-CMD-ZOD-BARE-STRING", kind: "positive", cls: "Command injection behind a schema that accepts every string", location: "cmd-zod-bare-string.js", match: ["command"], expectedTier: "high", note: "#1027 SOUNDNESS: pages/api/cmd-zod-bare-string.js wears the entire safe-twin shape — safeParse, early return on !success, sink reads `parsed.data` — but the schema is a bare `z.string()`. Every string parses, so `parsed.data` IS the request value and `status; rm -rf /` reaches the shell. The sanitizer requires the schema to carry an anchored positive-class regex or an enum, so this must STILL fire at high. This is the constraint unique to schema guards: a schema is not a sanitizer, an ALLOWLIST is." },
  { id: "P-CMD-ZOD-UNANCHORED", kind: "positive", cls: "Command injection behind an unanchored schema regex", location: "cmd-zod-unanchored.js", match: ["command"], expectedTier: "high", note: "#1027 SOUNDNESS: `z.string().regex(/[a-z]+/)` — positive class, early return, but UNANCHORED; zod's .regex() uses RegExp.test, which matches anywhere, so `status; rm -rf /` passes on its leading `status`. The anchoring constraint #989 proved on the bare `.test()` form, re-proven on the schema path — must STILL fire at high." },
  { id: "P-CMD-SET-GUARD-NO-RETURN", kind: "positive", cls: "Command injection where a Set allowlist's failure branch does not return", location: "cmd-set-guard-no-return.js", match: ["command"], expectedTier: "high", note: "#1027 SOUNDNESS: `ALLOWED_ACTIONS.has(cmd)` is consulted but the failure branch only logs, so execution falls through to the shell with the rejected value intact. The sanitizer matches the whole guard STATEMENT (test AND early return), so this must STILL fire at high — the case a bare `pattern: $SET.has($X)` sanitizer silently clears." },
];
