// Batch B3 — injection & code-execution family (#71, spec §"Batch 1 — Injection & code-execution").
// Custom Semgrep taint rules (src/scan/rules/semgrep/injection.yml) scored against targets/
// calibration. Tiering follows the locked preamble: only ~100%-precision sinks are `high` (free
// count) — a raw-SQL-executor RPC, `exec`/`execSync` of a request string, and `eval`/`new
// Function` of request input. The heuristic sinks (PostgREST string filters, recursive merge,
// deserialize, XXE options, path traversal, zip-slip, SSTI, ReDoS, log forging) are `review`.
// SQLi-via-template-literal (P-SQLI-CONCAT) and its safe lookalike N-PARAM-QUERY already ship in
// base.entries.ts; the ReDoS-safe / static-fs negatives (N-REDOS-SAFE, N-FS-STATIC) too. See
// GROUND-TRUTH.md §B3.

import type { CorpusEntry } from "./types.js";

export const b3InjectionEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-SQLI-RPC", kind: "positive", cls: "SQLi via raw-SQL-executor RPC", location: "report.js", match: ["rpc", "sql"], expectedTier: "high", note: "req.query.id interpolated into a SQL string run via admin.rpc('exec_sql', { query }) in pages/api/report.js. harvey-sql-injection-rpc gates the sink on raw-SQL-executor function names (exec_sql/execute/run_sql) → high." },
  { id: "P-CMD-INJECTION", kind: "positive", cls: "OS command injection (exec)", location: "convert.js", match: ["command"], expectedTier: "high", note: "req.query.f interpolated into exec(`convert ${f} ...`) in pages/api/convert.js — child_process.exec spawns a shell. harvey-command-injection taint (req → exec/execSync string) → high." },
  { id: "P-EVAL-CODE-INJ", kind: "positive", cls: "Code injection via eval", location: "calc.js", match: ["eval", "code-injection"], expectedTier: "high", note: "eval(req.body.expr) in pages/api/calc.js — arbitrary code execution. harvey-code-injection-eval taint (req → eval/new Function) → high." },
  { id: "P-POSTGREST-FILTER-INJ", kind: "positive", cls: "PostgREST filter injection", location: "find.js", match: ["postgrest", "filter"], expectedTier: "review", note: "req.query.n interpolated into a string .or(`name.eq.${n}`) in pages/api/find.js. harvey-postgrest-filter-injection taint → review (blast radius scoped to the table)." },
  { id: "P-PROTO-POLLUTION", kind: "positive", cls: "Prototype pollution via recursive merge", location: "merge.js", match: ["prototype", "pollution"], expectedTier: "review", note: "lodash.merge(config, req.body) in lib/merge.js — a __proto__ key mutates Object.prototype. harvey-prototype-pollution taint (req.body → merge/defaultsDeep) → review." },
  { id: "P-INSECURE-DESERIALIZE", kind: "positive", cls: "Unsafe deserialization", location: "import.js", match: ["deserial"], expectedTier: "review", note: "unserialize(req.body.data) in pages/api/import.js — node-serialize executes an embedded function body. harvey-unsafe-deserialization taint → review." },
  { id: "P-XXE", kind: "positive", cls: "XXE (external entities enabled)", location: "xml.js", match: ["xxe"], expectedTier: "review", note: "xml2js parseStringPromise(req.body, { noent: true }) in pages/api/xml.js resolves external entities. harvey-xxe pattern (noent/resolveEntities true) → review." },
  { id: "P-PATH-TRAVERSAL", kind: "positive", cls: "Path traversal", location: "file.js", match: ["traversal"], expectedTier: "review", note: "req.query.name joined into path.join('/var/data/uploads', name) then fs.readFileSync in pages/api/file.js. harvey-path-traversal taint (req → fs read/write; path.basename is a sanitizer) → review." },
  { id: "P-ZIP-SLIP", kind: "positive", cls: "Zip-slip archive traversal", location: "unzip.js", match: ["zip-slip", "zip"], expectedTier: "review", note: "fs.writeFileSync(path.join(outDir, entry.entryName), ...) with no containment check in lib/unzip.js. harvey-zip-slip pattern → review." },
  { id: "P-SSTI", kind: "positive", cls: "Server-side template injection", location: "render.js", match: ["template-injection", "template"], expectedTier: "review", note: "ejs.render(req.body.tpl, ...) in pages/api/render.js — user controls the template source (SSTI → RCE on EJS). harvey-template-injection taint → review." },
  { id: "P-SSTI-APPROUTER", kind: "positive", cls: "SSTI via App Router await req.json() template source", location: "ar-ssti/route", match: ["template-injection", "template"], expectedTier: "review", note: "#570: app/api/ar-ssti/route.ts renders ejs.render(String(template ?? ''), ...) where const { template } = await req.json() — the App Router body controls the template SOURCE. Before #570 harvey-template-injection's sources were Express-only (req.query/body/params), so this pure-App-Router SSTI (SuperRedHat F-12 SSTI facet) went dark. harvey-template-injection taint → review." },
  { id: "P-REDOS", kind: "positive", cls: "ReDoS (catastrophic backtracking)", location: "parse.js", match: ["redos"], expectedTier: "review", note: "new RegExp('^(a+)+$') in lib/parse.js — nested quantifier. harvey-redos (metavariable-regex on the nested-quantifier shape) → review." },
  { id: "P-LOG-INJECTION", kind: "positive", cls: "Log injection / forging", location: "track.js", match: ["log-injection"], expectedTier: "review", note: "console.log(`... ${req.query.u} ...`) in pages/api/track.js — CR/LF log forging. harvey-log-injection taint → review (common shape, low severity)." },

  // #984: cookies/headers as taint sources. Before #984 the request source set was only
  // req.query/body/params/searchParams, so any injection entering through req.cookies/req.headers
  // went dark. These prove a cookie/header source reaches a free-count sink, and that the new
  // sources don't over-fire on a parameterized query.
  { id: "P-SQLI-COOKIE-SOURCE", kind: "positive", cls: "SQLi via req.cookies source", location: "cookie-report.js", match: ["sql"], expectedTier: "high", note: "#984: req.cookies.session_token interpolated into a raw SQL string reaching pool.query in pages/api/cookie-report.js. harvey-sql-injection-template taint with the new req.cookies source → high." },
  { id: "P-CMD-HEADER-SOURCE", kind: "positive", cls: "Command injection via req.headers source", location: "header-exec.js", match: ["command"], expectedTier: "high", note: "#984: req.headers['x-forwarded-host'] interpolated into exec(`nslookup ${host}`) in pages/api/header-exec.js. harvey-command-injection taint with the new req.headers source → high." },

  // #985: widened injection SINK coverage — SSRF via the node http/https clients (not just fetch),
  // XXE via a libxmljs parse call (not just the parser option), and generic Mongo NoSQL injection.
  { id: "P-SSRF-HTTP-NODE", kind: "positive", cls: "SSRF via node http.get client", location: "ssrf-http.js", match: ["ssrf"], expectedTier: "review", note: "#985: req.query.url fetched via http.get in pages/api/ssrf-http.js — harvey-ssrf-fetch only matched fetch() before #985; the http/https/axios/request sinks were added. → review." },
  { id: "P-XXE-LIBXMLJS", kind: "positive", cls: "XXE via libxmljs parse call", location: "xxe-parse.js", match: ["xxe"], expectedTier: "review", note: "#985: req.body.xml parsed via libxmljs.parseXml in pages/api/xxe-parse.js. harvey-xxe only matched the noent/resolveEntities parser OPTION; harvey-xxe-parse taints the parse CALL (libxmljs/DOMParser fed request input). → review." },
  { id: "P-NOSQL-REGEX", kind: "positive", cls: "NoSQL (Mongo) injection via $regex operator", location: "nosql-find.js", match: ["nosql", "data query logic"], expectedTier: "review", note: "#985: req.query.name placed under a Mongo $regex operator in findOne in pages/api/nosql-find.js. harvey-nosql-injection taints request input reaching a $where/$regex/$ne/$gt operator. → review (generic Mongo detector; harvey-postgrest-filter-injection is PostgREST-specific)." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-HEADER-PARAM-QUERY", kind: "negative", cls: "Header value passed as a bound param", location: "header-param.js", note: "#984: req.headers['x-tenant-id'] passed as a $1 bound parameter in pages/api/header-param.js — never interpolated into the SQL string. harvey-sql-injection-template focuses the sink on the SQL text arg, so the new cookies/headers sources must not FP here. Regression guard mirroring N-PARAM-QUERY for the #984 sources." },
  { id: "N-SSRF-HTTP-FIXED", kind: "negative", cls: "node https client called with a fixed URL", location: "ssrf-http-safe.js", match: ["ssrf"], note: "#985: https.get('https://cdn.example.com/status.json') in pages/api/ssrf-http-safe.js — a fixed non-request URL, no taint reaches the sink. Regression guard that the new http/https/axios sinks don't fire without a tainted source (and that the searchParams .get source no longer self-matches https.get)." },
  { id: "N-XXE-PARSE-FIXED", kind: "negative", cls: "libxmljs parse of a constant XML string", location: "xxe-parse-safe.js", match: ["xxe"], note: "#985: libxmljs.parseXml('<root>…</root>') in pages/api/xxe-parse-safe.js — a constant, not request input. harvey-xxe-parse is taint-gated, so the parse-call sink stays dark. Regression guard." },
  { id: "N-NOSQL-EQ-LOOKUP", kind: "negative", cls: "Plain Mongo equality lookup by id", location: "nosql-find-safe.js", match: ["nosql", "data query logic"], note: "#985: findOne({ _id: id }) in pages/api/nosql-find-safe.js — the request value is an ordinary field VALUE, not fed into a $-operator. harvey-nosql-injection requires the tainted value to reach a Mongo operator, so an ordinary id lookup stays dark. Keeps the rule off routine scoped queries." },
  { id: "N-CMD-SAFE", kind: "negative", cls: "execFile with argv array (no shell)", location: "img.js", note: "execFile('convert', [inputPath, ...]) in lib/img.js — discrete argv, no shell, no injection. harvey-command-injection fires only on exec/execSync of a string — cleared." },
  { id: "N-EVAL-JSON", kind: "negative", cls: "JSON.parse, not eval", location: "cfg.js", note: "JSON.parse(req.body) in lib/cfg.js parses data, cannot execute. harvey-code-injection-eval fires only on eval/new Function — cleared." },
  { id: "N-PROTO-SAFE", kind: "negative", cls: "Shallow Object.assign of picked fields", location: "opts.js", note: "Object.assign({}, DEFAULTS, {theme, pageSize}) in lib/opts.js — shallow, explicit fields, no recursive merge. harvey-prototype-pollution fires only on merge/defaultsDeep/mergeWith — cleared." },
  { id: "N-XXE-SAFE", kind: "negative", cls: "XML parse with entities disabled", location: "xml-safe.js", note: "xml2js parse with { noent: false } in lib/xml-safe.js — hardened. harvey-xxe fires only on noent/resolveEntities true — cleared." },
  { id: "N-PATH-BASENAME", kind: "negative", cls: "path.basename-sanitized file read", location: "dl.js", note: "path.basename(req.query.f) strips directory components before the join in pages/api/dl.js. harvey-path-traversal registers path.basename as a sanitizer — cleared." },
  { id: "N-RPC-PARAM", kind: "negative", cls: "Parameterized Supabase RPC", location: "rep.js", note: "admin.rpc('report_total', { uid }) in pages/api/rep.js — a normal RPC with a bound argument (PostgREST parameterizes it). harvey-sql-injection-rpc fires only on raw-SQL-executor RPC names — cleared." },
  { id: "N-SSTI-APPROUTER-FIXED", kind: "negative", cls: "App Router render of a fixed server-owned template", location: "ar-ssti-safe", match: ["template-injection", "template"], note: "#570: app/api/ar-ssti-safe/route.ts renders a fixed constant template (NOTE_TEMPLATE); only the DATA passed to it comes from await req.json(). harvey-template-injection taints the template SOURCE argument (the first arg), which is the constant here, so no request taint reaches the sink — cleared. Regression guard: confirms the new await-req.json() source doesn't over-fire when only template data (not the template) is user-controlled." },
];
