// Batch B3 — injection & code-execution family (#71, spec §"Batch 1 — Injection & code-execution").
// Custom Semgrep taint rules (src/scan/rules/semgrep/injection.yml) scored against targets/
// calibration. Tiering follows the locked preamble: only ~100%-precision sinks are `high` (free
// count) — a raw-SQL-executor RPC, `exec`/`execSync` of a request string, and `eval`/`new
// Function` of request input. The heuristic sinks (PostgREST string filters, recursive merge,
// deserialize, XXE options, path traversal, zip-slip, SSTI, ReDoS, log forging) are `review`.
// SQLi-via-template-literal (P-SQLI-CONCAT) and its safe lookalike N-PARAM-QUERY already ship in
// base.entries.ts; the ReDoS-safe / static-fs negatives (N-REDOS-SAFE, N-FS-STATIC) too. See
// GROUND-TRUTH.md §B3.

import type { CorpusEntry } from "./types.js";

export const b3InjectionEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-SQLI-RPC", kind: "positive", cls: "SQLi via raw-SQL-executor RPC", location: "report.js", match: ["rpc", "sql"], expectedTier: "high", note: "req.query.id interpolated into a SQL string run via admin.rpc('exec_sql', { query }) in pages/api/report.js. harvey-sql-injection-rpc gates the sink on raw-SQL-executor function names (exec_sql/execute/run_sql) → high." },
  { id: "P-CMD-INJECTION", kind: "positive", cls: "OS command injection (exec)", location: "convert.js", match: ["command"], expectedTier: "high", note: "req.query.f interpolated into exec(`convert ${f} ...`) in pages/api/convert.js — child_process.exec spawns a shell. harvey-command-injection taint (req → exec/execSync string) → high. This is the CWE-78 shell-STRING shape (#983)." },
  { id: "P-ARG-INJECTION", kind: "positive", cls: "Argument injection (argv-array, CWE-88)", location: "git-clone.js", match: ["argument"], expectedTier: "review", note: "#983: req.query.repo passed as an argv-array element to execFile('git', ['clone', repo, …]) with NO shell in pages/api/git-clone.js — argument injection (a --flag value is read by git), CWE-88, distinct from the CWE-78 shell-string exec. harvey-argument-injection taint → review." },
  { id: "P-EVAL-CODE-INJ", kind: "positive", cls: "Code injection via eval", location: "calc.js", match: ["eval", "code-injection"], expectedTier: "high", note: "eval(req.body.expr) in pages/api/calc.js — arbitrary code execution. harvey-code-injection-eval taint (req → eval/new Function) → high." },
  { id: "P-POSTGREST-FILTER-INJ", kind: "positive", cls: "PostgREST filter injection", location: "find.js", match: ["postgrest", "filter"], expectedTier: "review", note: "req.query.n interpolated into a string .or(`name.eq.${n}`) in pages/api/find.js. harvey-postgrest-filter-injection taint → review (blast radius scoped to the table)." },
  { id: "P-PROTO-POLLUTION", kind: "positive", cls: "Prototype pollution via recursive merge", location: "merge.js", match: ["prototype", "pollution"], expectedTier: "review", note: "lodash.merge(config, req.body) in lib/merge.js — a __proto__ key mutates Object.prototype. harvey-prototype-pollution taint (req.body → merge/defaultsDeep) → review." },
  { id: "P-INSECURE-DESERIALIZE", kind: "positive", cls: "Unsafe deserialization", location: "import.js", match: ["deserial"], expectedTier: "review", note: "unserialize(req.body.data) in pages/api/import.js — node-serialize executes an embedded function body. harvey-unsafe-deserialization taint → review." },
  { id: "P-XXE", kind: "positive", cls: "XXE (external entities enabled)", location: "xml.js", match: ["xxe"], expectedTier: "review", note: "xml2js parseStringPromise(req.body, { noent: true }) in pages/api/xml.js resolves external entities. harvey-xxe pattern (noent/resolveEntities true) → review." },
  { id: "P-PATH-TRAVERSAL", kind: "positive", cls: "Path traversal", location: "file.js", match: ["traversal"], expectedTier: "review", note: "req.query.name joined into path.join('/var/data/uploads', name) then fs.readFileSync in pages/api/file.js. harvey-path-traversal taint (req → fs read/write; path.basename is a sanitizer) → review." },
  { id: "P-ZIP-SLIP", kind: "positive", cls: "Zip-slip archive traversal", location: "unzip.js", match: ["zip-slip"], expectedTier: "review", note: "fs.writeFileSync(path.join(outDir, entry.entryName), ...) with no containment check in lib/unzip.js. harvey-zip-slip pattern → review." },
  { id: "P-SSTI", kind: "positive", cls: "Server-side template injection", location: "render.js", match: ["template-injection", "template"], expectedTier: "review", note: "ejs.render(req.body.tpl, ...) in pages/api/render.js — user controls the template source (SSTI → RCE on EJS). harvey-template-injection taint → review." },
  { id: "P-SSTI-APPROUTER", kind: "positive", cls: "SSTI via App Router await req.json() template source", location: "ar-ssti/route", match: ["template-injection", "template"], expectedTier: "review", note: "#570: app/api/ar-ssti/route.ts renders ejs.render(String(template ?? ''), ...) where const { template } = await req.json() — the App Router body controls the template SOURCE. Before #570 harvey-template-injection's sources were Express-only (req.query/body/params), so this pure-App-Router SSTI (SuperRedHat F-12 SSTI facet) went dark. harvey-template-injection taint → review." },
  { id: "P-REDOS", kind: "positive", cls: "ReDoS (catastrophic backtracking)", location: "parse.js", match: ["redos"], expectedTier: "review", note: "new RegExp('^(a+)+$') in lib/parse.js — nested quantifier. harvey-redos (metavariable-regex on the nested-quantifier shape) → review." },
  { id: "P-LOG-INJECTION", kind: "positive", cls: "Log injection / forging", location: "track.js", match: ["log-injection"], expectedTier: "review", note: "console.log(`... ${req.query.u} ...`) in pages/api/track.js — CR/LF log forging. harvey-log-injection taint → review (common shape, low severity)." },

  // #984: cookies/headers as taint sources. Before #984 the request source set was only
  // req.query/body/params/searchParams, so any injection entering through req.cookies/req.headers
  // went dark. These prove a cookie/header source reaches a free-count sink, and that the new
  // sources don't over-fire on a parameterized query.
  { id: "P-SQLI-COOKIE-SOURCE", kind: "positive", cls: "SQLi via req.cookies source", location: "cookie-report.js", match: ["sql"], expectedTier: "high", note: "#984: req.cookies.session_token interpolated into a raw SQL string reaching pool.query in pages/api/cookie-report.js. harvey-sql-injection-template taint with the new req.cookies source → high." },
  { id: "P-CMD-HEADER-SOURCE", kind: "positive", cls: "Command injection via req.headers source", location: "header-exec.js", match: ["command"], expectedTier: "high", note: "#984: req.headers['x-forwarded-host'] interpolated into exec(`nslookup ${host}`) in pages/api/header-exec.js. harvey-command-injection taint with the new req.headers source → high." },

  // #985: widened injection SINK coverage — SSRF via the node http/https clients (not just fetch),
  // XXE via a libxmljs parse call (not just the parser option), and generic Mongo NoSQL injection.
  { id: "P-SSRF-HTTP-NODE", kind: "positive", cls: "SSRF via node http.get client", location: "ssrf-http.js", match: ["ssrf-fetch"], expectedTier: "review", note: "#985: req.query.url fetched via http.get in pages/api/ssrf-http.js — harvey-ssrf-fetch only matched fetch() before #985; the http/https/axios/request sinks were added. → review." },
  { id: "P-XXE-LIBXMLJS", kind: "positive", cls: "XXE via libxmljs parse call", location: "xxe-parse.js", match: ["xxe-capable"], expectedTier: "review", note: "#985: req.body.xml parsed via libxmljs.parseXml in pages/api/xxe-parse.js. harvey-xxe only matched the noent/resolveEntities parser OPTION; harvey-xxe-parse taints the parse CALL (libxmljs/DOMParser fed request input). → review." },
  { id: "P-NOSQL-REGEX", kind: "positive", cls: "NoSQL (Mongo) injection via $regex operator", location: "nosql-find.js", match: ["nosql-injection", "data query logic"], expectedTier: "review", note: "#985: req.query.name placed under a Mongo $regex operator in findOne in pages/api/nosql-find.js. harvey-nosql-injection taints request input reaching a $where/$regex/$ne/$gt operator. → review (generic Mongo detector; harvey-postgrest-filter-injection is PostgREST-specific)." },

  // #1273: the three sink classes #985's expansion comment recorded and its closing PR never
  // tracked. MEASURED 2026-07-31 by running the real semgrep pass over planted shapes: XPath, LDAP
  // and CSV-formula injection existed in NO harvey-* rule and in no issue anywhere in the repo.
  // Each positive is paired with a constant-source negative, which is the taint gate's boundary —
  // a rule that matched the sink CALL rather than the tainted argument fires on it.
  { id: "P-XPATH-INJECTION", kind: "positive", cls: "XPath injection via a concatenated predicate", location: "xpath-lookup.js", match: ["XPath injection"], expectedTier: "review", expectedSeverity: "High", note: "#1273: req.query.name concatenated into an XPath predicate in pages/api/xpath-lookup.js — `' or '1'='1` rewrites the predicate to match every node, and against an XML-backed credential store the same rewrite is an auth bypass. harvey-xpath-injection taints the EXPRESSION argument of xpath.select/select1/evaluate/parse and of DOM evaluate/selectNodes/selectSingleNode → review. Stays review: the AST proves the concatenation, not that the XML store holds anything sensitive." },
  { id: "P-LDAP-INJECTION", kind: "positive", cls: "LDAP injection via a concatenated search filter", location: "ldap-lookup.js", match: ["LDAP injection"], expectedTier: "review", expectedSeverity: "High", note: "#1273: req.query.uid concatenated into the ldapjs search filter in pages/api/ldap-lookup.js — `*)(uid=*` turns a single-account lookup into a directory dump, and an LDAP-backed login into an auth bypass. harvey-ldap-injection taints the options object of a search/bind/compare/modify call inside a file that requires ldapjs → review." },
  { id: "P-CSV-FORMULA", kind: "positive", cls: "CSV formula injection in a spreadsheet export", location: "csv-export.js", match: ["formula injection"], expectedTier: "review", expectedSeverity: "Medium", note: "#1273: req.query.label serialized into a csv-stringify export in pages/api/csv-export.js with no formula-prefix neutralization — a cell beginning =/+/-/@/tab/CR is executed as a formula by Excel and Sheets when a colleague opens the file. harvey-csv-formula-injection taints the records argument of the CSV/spreadsheet serializers → review at Medium: the victim is the file's opener, not the server, and exploitability depends on their spreadsheet settings." },

  // #986: transformation-sanitizer (a1) — the unguarded twins that must STILL fire (a sanitizer
  // must not swallow a real finding). The guarded negatives that must now clear are below.
  { id: "P-XSS-TEMPLATE-LITERAL", kind: "positive", cls: "Reflected XSS via HTML template literal to res.send", location: "xss-template-literal.js", match: ["html-template"], expectedTier: "review", note: "#986: req.query.name interpolated raw into an HTML template literal handed to res.send in pages/api/xss-template-literal.js — reflected XSS. harvey-html-template-literal taint → review. Unguarded twin proving the new #986 escaper sanitizer doesn't swallow a real finding." },

  // #987: taint source-pattern robustness — the same request sources reached via method-form,
  // destructured, bracket, and multi-hop/aliased shapes. Measured: the method form needed the new
  // req.get/req.header pattern; destructure/bracket/multi-hop propagate through semgrep taint once
  // the base object is a source. All four fire at the high free-count sink.
  { id: "P-CMD-METHODFORM-SOURCE", kind: "positive", cls: "Command injection via req.get() method-form source", location: "header-getter-exec.js", match: ["command"], expectedTier: "high", note: "#987: req.get('x-forwarded-for') (Express method form) reaches exec() in pages/api/header-getter-exec.js. harvey-command-injection with the new req.get/req.header method-form source → high." },
  { id: "P-SQLI-MULTIHOP-SOURCE", kind: "positive", cls: "SQLi via multi-hop/aliased req.headers source", location: "multihop-sql.js", match: ["sql-injection"], expectedTier: "high", note: "#987: taint aliased (const h = req.headers) then hopped (const token = h.authorization) before the SQL string in pages/api/multihop-sql.js. Semgrep taint dataflow recovers the flow once req.headers is a source → high." },
  { id: "P-SQLI-DESTRUCTURE-SOURCE", kind: "positive", cls: "SQLi via destructured req.cookies source", location: "destructure-sql.js", match: ["sql-injection"], expectedTier: "high", note: "#987: const { id } = req.cookies then interpolated into the SQL string in pages/api/destructure-sql.js — a destructuring source form recovered by semgrep taint once req.cookies is a source → high." },
  { id: "P-CMD-BRACKET-SOURCE", kind: "positive", cls: "Command injection via bracket-access req.query source", location: "bracket-exec.js", match: ["command"], expectedTier: "high", note: "#987: req.query['host'] (bracket access, not dot form) reaches exec() in pages/api/bracket-exec.js — recovered by semgrep taint once req.query is a source → high." },

  // #1221: the App Router source blind spots, one entry per rule MEASURED silent on 2026-07-27
  // (semgrep 1.164.0) with a declared-source control firing on the same sink. Every `match` here
  // asserts the RULE ID, not a topic word: harvey-lib-* captures exported functions, so an App
  // Router handler produces a finding from the LIBRARY rule even when the app-layer rule is blind
  // — scoring on "a relevant finding appeared" records these gaps as covered (#1222).
  { id: "P-CMD-REQUEST-PARAM", kind: "positive", cls: "Command injection via an App-Router `request` parameter", location: "ar-src-cmd/route", match: ["harvey-command-injection"], expectedTier: "high", expectedSeverity: "Critical", note: "#1221: app/api/ar-src-cmd/route.ts reads request.headers.get('x-forwarded-host') into exec(). The handler parameter is named `request` (the App Router convention) and the old source list spelled the prefix LITERALLY as `req.`, so it could not see the object at all. The canonical block name-constrains $REQ instead. harvey-command-injection → high." },
  { id: "P-EVAL-SEARCHPARAMS", kind: "positive", cls: "Code injection via the split searchParams read", location: "ar-src-eval/route", match: ["harvey-code-injection-eval"], expectedTier: "high", expectedSeverity: "Critical", note: "#1221: app/api/ar-src-eval/route.ts evals a value read via `const u = new URL(req.url); u.searchParams.get('expr')`. harvey-code-injection-eval was one of the 19 of 21 rules blind to searchParams.get; the split form is also why `$U.searchParams` (not `new URL($REQ.url).searchParams`) is the load-bearing pattern. → high." },
  { id: "P-NOSQL-JSON-BODY", kind: "positive", cls: "NoSQL injection via the App Router JSON body", location: "ar-src-nosql/route", match: ["harvey-nosql-injection"], expectedTier: "review", expectedSeverity: "High", note: "#1221: app/api/ar-src-nosql/route.ts places `const { name } = await req.json()` under a Mongo $regex operator. harvey-nosql-injection was one of the 17 of 21 rules blind to await req.json(). → review." },
  { id: "P-LOG-SEARCHPARAMS", kind: "positive", cls: "Log injection via searchParams", location: "ar-src-log/route", match: ["harvey-log-injection"], expectedTier: "review", expectedSeverity: "Low", note: "#1221: app/api/ar-src-log/route.ts logs `new URL(req.url).searchParams.get('u')` unescaped — CR/LF log forging. harvey-log-injection was blind to the searchParams source. → review." },
  { id: "P-PATH-SEARCHPARAMS", kind: "positive", cls: "Path traversal via the inline App Router searchParams read", location: "ar-src-path/route", match: ["harvey-path-traversal"], expectedTier: "review", expectedSeverity: "High", note: "#1220/#1221: app/api/ar-src-path/route.ts joins `new URL(request.url).searchParams.get('path')` into an fs.readFileSync path. This is the exact probe #1220 measured silent while its req.query control fired — the source vocabulary was the first of that issue's two independent causes. The `match` deliberately asserts harvey-path-traversal, because harvey-lib-path-traversal also fires on this file and would otherwise score the gap covered. → review." },

  // #1220: harvey-path-traversal's SINK surface. Gap 1 (the source list) is #1221's canonical
  // block; this is the independent second gap — either alone suppressed the finding on the real
  // ATC route, and both were present.
  { id: "P-STORAGE-TRAVERSAL", kind: "positive", cls: "Cross-tenant path traversal into Supabase Storage", location: "ar-storage-path/route", match: ["harvey-path-traversal"], expectedTier: "review", expectedSeverity: "High", note: "#1220: app/api/ar-storage-path/route.ts signs a request-controlled object key on a SERVICE-ROLE storage client, guarded only by `key.startsWith(`${tenantId}/`)`. Storage was an unmodeled path-sink surface entirely — for a Supabase-specialist audit, the notable hole. The GUARD is why this entry matters as much as the sink: a prefix test is not a containment test, and `<tenant>/../<other>/f` satisfies it (jharvieux/ATC#2050), so this must keep firing however the sanitizer set grows. Verified 2026-07-27 against the real route (ATC apps/main/src/app/api/imports/source-file/route.ts): 0 findings before, harvey-path-traversal after. → review." },
  { id: "P-PATH-FS-PROMISES", kind: "positive", cls: "Path traversal via a bare fs/promises readFile", location: "ar-fsp-path/route", match: ["harvey-path-traversal"], expectedTier: "review", expectedSeverity: "High", note: "#1220: app/api/ar-fsp-path/route.ts calls `readFile` imported bare from node:fs/promises — the idiomatic App Router file read. All five modelled sinks were callback/sync forms spelled with a LITERAL `fs.` prefix, so the promise API reached none of them no matter how the value arrived. → review." },

  // #1224: the two rules #1221 split out for per-rule judgment. They got OPPOSITE calls, and the
  // sink is what separates them — a recursive merge pollutes via KEYS, so an attacker-controlled
  // string is inert; unserialize() consumes a STRING, so every one of them is in class. Both
  // rationales, including the sources deliberately left out, are written on the rules themselves.
  { id: "P-PROTO-JSON-BODY", kind: "positive", cls: "Prototype pollution via the App Router JSON body", location: "ar-proto-json/route", match: ["harvey-prototype-pollution"], expectedTier: "review", expectedSeverity: "High", note: "#1224: app/api/ar-proto-json/route.ts merges `await req.json()` into a settings object, so a `__proto__` key mutates Object.prototype. A JSON body is exactly what carries that key — the rule's single most important omission, and it had one of the two narrowest source lists in the directory. It did NOT take the canonical block: route params and searchParams.get return strings that cannot pollute a prototype, and URLSearchParams/cookies()/headers() keep their entries in internal slots a deep merge never walks. → review." },
  { id: "P-DESER-COOKIE", kind: "positive", cls: "Unsafe deserialization of an App Router cookie", location: "ar-deser-cookie/route", match: ["harvey-unsafe-deserialization"], expectedTier: "review", expectedSeverity: "High", note: "#1224: app/api/ar-deser-cookie/route.ts passes a serialized session blob from cookies() to node-serialize, which executes an embedded function body — RCE. A session cookie is the classic vector for this weakness and the Express-only source list could not see the App Router accessor at all. This rule DID take the canonical block, unlike its neighbour: its sink consumes a string, so nothing in the block is out of class. → review." },

  // #1222: ATTRIBUTION, not detection. Both this entry and P-CMD-REQUEST-PARAM cover an App Router
  // handler reaching exec; the difference is that this one exists to fail when the finding comes
  // from the RIGHT weakness but the WRONG rule.
  { id: "P-ATTRIB-APPROUTER-CMD", kind: "positive", cls: "App Router command injection attributed to the app-layer rule", location: "ar-attrib-cmd/route", match: ["harvey-command-injection"], expectedTier: "high", expectedSeverity: "Critical", note: "#1222: app/api/ar-attrib-cmd/route.ts is an App Router POST handler reaching exec. `export async function POST(...)` matched harvey-lib-*'s `export function $F($P, ...)` source, so before #1222 a route the app-layer rule was blind to STILL produced a finding — from the library rule, at Medium instead of Critical, saying 'an exported library function's parameter' about a public HTTP route. The corpus danger exceeds the severity: an entry scored on 'did a relevant finding appear?' reads the gap as COVERED, which is the #1062 masking shape reached through rule precedence. `match` is the rule id and expectedSeverity is Critical precisely because a harvey-lib-command-injection finding would satisfy NEITHER — the entry is the regression detector for the attribution, not for the detection." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-STORAGE-BASENAME", kind: "negative", cls: "Storage key sanitized by path.basename", location: "ar-storage-path-safe/route", note: "#1220: app/api/ar-storage-path-safe/route.ts runs the request value through path.basename before assembling the tenant-prefixed key, so no directory component survives. Proves the new storage sinks stay taint-gated and honour the existing sanitizer set instead of firing on every .storage.from(...) call." },
  { id: "N-STORAGE-DB-PATH", kind: "negative", cls: "Storage key read from a DB row via a tenant-scoped client", location: "ar-storage-dbpath/route", note: "#1220: app/api/ar-storage-dbpath/route.ts signs a key taken from a help_doc_versions row through a TENANT-SCOPED client; the request only supplies the row id. This mirrors the SECOND real ATC route (help/docs/export/[jobId]) — the external tool flagged it and it is a false positive. A storage-sink widening that lights this up has bought its recall with precision, so the entry charges for that; re-verified 2026-07-27 against the real route, still silent." },
  { id: "N-PATH-RESOLVE-VERIFIED", kind: "negative", cls: "Path confined by resolve-then-re-verify", location: "ar-path-contained/route", note: "#1220: app/api/ar-path-contained/route.ts prefix-tests the output of path.resolve, the correct containment idiom — path.resolve collapses `..`, so the string it returns IS the path opened. Widening the sinks to fs/promises newly reaches this shape, so it is modelled in the same change that created the exposure rather than shipped as noise. Paired with P-STORAGE-TRAVERSAL, whose near-identical prefix test is on the RAW value and must keep firing: a containment sanitizer that cannot tell the two apart is worse than none. The guard also had to match the BRACELESS early return — MEASURED 2026-07-27, the block-only form every other (a2) arm uses missed this fixture outright." },
  { id: "N-SOURCE-BENIGN-GET", kind: "negative", cls: "Non-request .get()/property reads reaching a command and a log sink", location: "ar-src-benign/route", note: "#1221: app/api/ar-src-benign/route.ts reaches exec() and console.log() from a Map lookup, an upstream Response's headers.get('etag') and that Response's .body — none of them request input. This is the measured FP shape of the widening: a FREE `$REQ.` metavariable (what #1221 recommended) fired on all of these plus config.get()/formData.get()/builder.query. The name-constrained block must stay silent here while every ar-src-* positive fires — the pair is what makes the widening a recall gain rather than a precision trade." },
  { id: "N-HEADER-PARAM-QUERY", kind: "negative", cls: "Header value passed as a bound param", location: "header-param.js", note: "#984: req.headers['x-tenant-id'] passed as a $1 bound parameter in pages/api/header-param.js — never interpolated into the SQL string. harvey-sql-injection-template focuses the sink on the SQL text arg, so the new cookies/headers sources must not FP here. Regression guard mirroring N-PARAM-QUERY for the #984 sources." },
  { id: "N-SSRF-HTTP-FIXED", kind: "negative", cls: "node https client called with a fixed URL", location: "ssrf-http-safe.js", note: "#985: https.get('https://cdn.example.com/status.json') in pages/api/ssrf-http-safe.js — a fixed non-request URL, no taint reaches the sink. Regression guard that the new http/https/axios sinks don't fire without a tainted source (and that the searchParams .get source no longer self-matches https.get)." },
  { id: "N-XXE-PARSE-FIXED", kind: "negative", cls: "libxmljs parse of a constant XML string", location: "xxe-parse-safe.js", note: "#985: libxmljs.parseXml('<root>…</root>') in pages/api/xxe-parse-safe.js — a constant, not request input. harvey-xxe-parse is taint-gated, so the parse-call sink stays dark. Regression guard." },
  { id: "N-NOSQL-EQ-LOOKUP", kind: "negative", cls: "Plain Mongo equality lookup by id", location: "nosql-find-safe.js", note: "#985: findOne({ _id: id }) in pages/api/nosql-find-safe.js — the request value is an ordinary field VALUE, not fed into a $-operator. harvey-nosql-injection requires the tainted value to reach a Mongo operator, so an ordinary id lookup stays dark. Keeps the rule off routine scoped queries." },
  // #1273: the boundary negatives for the three new sink classes. Each calls the same sink as its
  // positive with a SERVER-OWNED expression/filter/record set, the request value touching only the
  // result — so the taint gate is the single difference between the pair, and a rule that matched
  // the sink CALL rather than its tainted argument would fail loud here.
  { id: "N-XPATH-CONSTANT", kind: "negative", cls: "XPath query with a server-owned constant expression", location: "xpath-lookup-safe.js", note: "#1273: xpath.select(\"//user[@role='admin']\", doc) in pages/api/xpath-lookup-safe.js — the expression is a constant and req.query.name only filters the RESULT in JavaScript. harvey-xpath-injection is taint-gated on the expression argument, so it stays dark. Boundary guard: matching xpath.select on presence rather than on taint fires here." },
  { id: "N-LDAP-CONSTANT-FILTER", kind: "negative", cls: "LDAP search with a server-owned constant filter", location: "ldap-lookup-safe.js", note: "#1273: client.search(base, { filter: \"(objectClass=inetOrgPerson)\" }) in pages/api/ldap-lookup-safe.js — a constant filter; req.query.uid is only echoed in the response. harvey-ldap-injection is taint-gated on the options object, so it stays dark. Boundary guard for the new search/bind/compare/modify sinks." },
  { id: "N-CSV-FORMULA-CONSTANT", kind: "negative", cls: "CSV export of a server-owned constant label set", location: "csv-export-safe.js", note: "#1273: stringify() over a constant LABELS list in pages/api/csv-export-safe.js — req.query.prefix SELECTS which rows go out, it never becomes a cell. harvey-csv-formula-injection is taint-gated on the records argument, so it stays dark. Boundary guard: an export route is a routine shape and matching the serializer call alone would flag every one of them." },
  // #986: numeric-coercion / escaper transformation sanitizers ((a1) subset) — each guarded twin
  // must now clear where its unguarded twin still fires (proven above).
  { id: "N-SQLI-PARSEINT", kind: "negative", cls: "SQLi cleared by parseInt coercion", location: "sqli-parseint-safe.js", note: "#986: parseInt(req.query.id, 10) interpolated into the SQL string in pages/api/sqli-parseint-safe.js — a number can't carry SQL metacharacters. harvey-sql-injection-template registers parseInt/parseFloat/Number as sanitizers — cleared deterministically (no LLM pass). Regression guard for the (a1) numeric sanitizer." },
  { id: "N-SQLI-PARSEFLOAT", kind: "negative", cls: "SQLi cleared by parseFloat coercion", location: "sqli-parsefloat-safe.js", note: "#986: parseFloat(req.query.amount) interpolated into the SQL string in pages/api/sqli-parsefloat-safe.js — coerced to a number, safe. harvey-sql-injection-template parseFloat sanitizer — cleared." },
  { id: "N-SQLI-NUMBER", kind: "negative", cls: "SQLi cleared by Number() coercion", location: "sqli-number-safe.js", note: "#986: Number(req.query.page) interpolated into the SQL string in pages/api/sqli-number-safe.js — coerced to a number, safe. harvey-sql-injection-template Number sanitizer — cleared." },
  { id: "N-XSS-TEMPLATE-ESCAPED", kind: "negative", cls: "Template-literal XSS cleared by escapeHtml", location: "xss-template-literal-safe.js", match: ["html-template"], note: "#986: escapeHtml(req.query.name) interpolated into the HTML template literal in pages/api/xss-template-literal-safe.js — the XSS is neutralized. harvey-html-template-literal now registers escapeHtml/escape/DOMPurify.sanitize/sanitizeHtml/sanitize as sanitizers — cleared. Regression guard for the (a1) escaper sanitizer." },
  { id: "N-METHODFORM-PARAM-QUERY", kind: "negative", cls: "Method-form header value passed as a bound param", location: "header-getter-safe.js", match: ["sql"], note: "#987: req.get('x-tenant-id') passed as a $1 bound parameter in pages/api/header-getter-safe.js — never interpolated. The new method-form source must not FP on a parameterized query. Regression guard for the #987 sources." },
  { id: "N-CMD-SAFE", kind: "negative", cls: "execFile with argv array (no shell)", location: "img.js", note: "execFile('convert', [inputPath, ...]) in lib/img.js — discrete argv, no shell, and inputPath is a function param (NOT a request source). harvey-command-injection fires only on exec/execSync of a string, and harvey-argument-injection (CWE-88, #983) is taint-gated so a non-request argv also clears — cleared by both." },
  { id: "N-ARG-INJECTION-FIXED", kind: "negative", cls: "execFile argv with a fixed constant arg", location: "git-clone-safe.js", match: ["argument"], note: "#983: execFile('git', ['clone', 'https://github.com/example/repo.git', …]) in pages/api/git-clone-safe.js — a constant repo URL, no request taint reaches the argv array. harvey-argument-injection is taint-gated — cleared. Regression guard that the CWE-88 rule doesn't fire on every execFile." },
  { id: "N-EVAL-JSON", kind: "negative", cls: "JSON.parse, not eval", location: "cfg.js", note: "JSON.parse(req.body) in lib/cfg.js parses data, cannot execute. harvey-code-injection-eval fires only on eval/new Function — cleared." },
  { id: "N-PROTO-SAFE", kind: "negative", cls: "Shallow Object.assign of picked fields", location: "opts.js", note: "Object.assign({}, DEFAULTS, {theme, pageSize}) in lib/opts.js — shallow, explicit fields, no recursive merge. harvey-prototype-pollution fires only on merge/defaultsDeep/mergeWith — cleared." },
  { id: "N-XXE-SAFE", kind: "negative", cls: "XML parse with entities disabled", location: "xml-safe.js", note: "xml2js parse with { noent: false } in lib/xml-safe.js — hardened. harvey-xxe fires only on noent/resolveEntities true — cleared." },
  { id: "N-PATH-BASENAME", kind: "negative", cls: "path.basename-sanitized file read", location: "dl.js", note: "path.basename(req.query.f) strips directory components before the join in pages/api/dl.js. harvey-path-traversal registers path.basename as a sanitizer — cleared." },
  { id: "N-RPC-PARAM", kind: "negative", cls: "Parameterized Supabase RPC", location: "rep.js", note: "admin.rpc('report_total', { uid }) in pages/api/rep.js — a normal RPC with a bound argument (PostgREST parameterizes it). harvey-sql-injection-rpc fires only on raw-SQL-executor RPC names — cleared." },
  { id: "N-SSTI-APPROUTER-FIXED", kind: "negative", cls: "App Router render of a fixed server-owned template", location: "ar-ssti-safe", match: ["template-injection", "template"], note: "#570: app/api/ar-ssti-safe/route.ts renders a fixed constant template (NOTE_TEMPLATE); only the DATA passed to it comes from await req.json(). harvey-template-injection taints the template SOURCE argument (the first arg), which is the constant here, so no request taint reaches the sink — cleared. Regression guard: confirms the new await-req.json() source doesn't over-fire when only template data (not the template) is user-controlled." },

  // #989: (a2) VALIDATOR-GUARD sanitizer — the tainted value is GATED by a control-flow check that
  // returns on failure, rather than transformed. The three positives below are the soundness half:
  // each wears the same guard SHAPE as a safe twin but is a real injection, so a guard model that
  // ignores anchoring, class polarity, or the early return silently clears a live bug.
  { id: "N-SQLI-REGEX-GUARD", kind: "negative", cls: "SQLi cleared by an anchored allowlist-regex guard", location: "sqli-regex-guard-safe.js", note: "#989: `if (!/^[a-zA-Z0-9_]+$/.test(col)) { …; return; }` gates the sort key before it is interpolated in pages/api/sqli-regex-guard-safe.js — nothing outside the allowlist can reach the SQL string. harvey-sql-injection-template registers the whole guard STATEMENT as a by-side-effect sanitizer — cleared deterministically (no LLM pass). Regression guard for the (a2) validator-guard sanitizer." },
  { id: "N-SQLI-ENUM-GUARD", kind: "negative", cls: "SQLi cleared by an enum-allowlist guard", location: "sqli-enum-guard-safe.js", note: "#989: `if (![\"title\",\"created_at\",\"id\"].includes(col)) { …; return; }` in pages/api/sqli-enum-guard-safe.js — only one of three constants can reach the SQL string. The .includes allowlist arm of the (a2) guard sanitizer — cleared." },
  { id: "N-CMD-ENUM-GUARD", kind: "negative", cls: "Command injection cleared by an enum-allowlist guard", location: "cmd-enum-guard-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#989: the same enum-allowlist early-return guard applied to an execSync sink in pages/api/cmd-enum-guard-safe.js. Proves the (a2) guard sanitizer generalizes past SQL to the command-injection rule — cleared, while the unguarded twin (convert.js, P-CMD-INJECTION) still fires." },
  { id: "P-SQLI-DENYLIST-GUARD", kind: "positive", cls: "SQLi behind a NEGATED-class (denylist) guard", location: "sqli-denylist-guard.js", match: ["sql-injection"], expectedTier: "high", note: "#989 SOUNDNESS: `/^[^\\x00-\\x1f]+$/` is anchored and returns on failure — the (a2) safe-twin shape — but the class is NEGATED, so it is a denylist that strips only control characters while quotes/semicolons/comment markers pass. A real injection. The guard sanitizer's metavariable-regex requires a POSITIVE class, so this must STILL fire at high." },
  { id: "P-SQLI-UNANCHORED-GUARD", kind: "positive", cls: "SQLi behind an unanchored allowlist regex", location: "sqli-unanchored-guard.js", match: ["sql-injection"], expectedTier: "high", note: "#989 SOUNDNESS: `/[a-zA-Z0-9_]+/` has a positive class and returns on failure, but is UNANCHORED — it matches anywhere, so `id; drop table documents--` passes on its leading `id`. A broken safeguard, not a sanitizer. The guard sanitizer requires ^…$ anchoring, so this must STILL fire at high." },
  { id: "P-SQLI-GUARD-NO-RETURN", kind: "positive", cls: "SQLi where the validator's failure branch does not return", location: "sqli-guard-no-return.js", match: ["sql-injection"], expectedTier: "high", note: "#989 SOUNDNESS: the allowlist test is anchored and positive, but the failure branch only logs — execution falls through to the query with the rejected value intact. The guard sanitizer matches the whole guard STATEMENT (test AND early return), not the bare test expression, so this must STILL fire at high. This is the case a naive `pattern: $RE.test($X)` sanitizer silently clears." },
  { id: "P-SQLI-MFLAG-GUARD", kind: "positive", cls: "SQLi behind an anchored allowlist neutered by the /m flag", location: "sqli-mflag-guard.js", match: ["sql-injection"], expectedTier: "high", note: "#1066 SOUNDNESS: the regex is anchored AND its class is positive AND the failure branch returns — it satisfies every #989 constraint — but the /m flag makes ^ and $ match at line breaks, so `/^[a-zA-Z0-9_]+$/m.test(\"id\\n; drop table documents--\")` is TRUE and the payload reaches the SQL string. The (a2) sanitizer's flag group was `[a-z]*`, which admitted `m` at 24 rule sites; it is now `[isuvy]*`, so this must STILL fire at high." },
  { id: "P-SEMGREP-VENDOR-SCOPE", kind: "positive", cls: "Command injection in a directory semgrep's default ignore set drops", location: "vendor/legacy-widget.js", match: ["command"], expectedTier: "high", note: "#1066 SCOPE: vendor/legacy-widget.js is an ordinary request→execSync command injection, planted in a directory semgrep never scanned. MEASURED 2026-07-25 with an identical file copied into eight directories and only `--exclude node_modules` passed: `tests/`, `test/`, `vendor/`, `dist/`, `build/` were never scanned and never listed — 5 of 8 silently dropped, and vendor/ is real shipped code. Harvey now passes --x-ignore-semgrepignore-files (8 of 8), and whatever is STILL unscanned is counted in SEM-SCOPE-00 rather than reading as clean. The end-to-end control for that: if the flag ever stops working this positive goes dark." },

  // #1027: the two guard forms #989 measured but did not model — a SCHEMA validator (zod
  // safeParse + early return on !success) and a Set-backed allowlist. Same structure as the block
  // above: one clearing negative per form, and one positive per soundness constraint. The schema
  // form adds a constraint the bare-regex form does not have — a schema can be well-formed and
  // still accept everything (`z.string()`), so "a schema was used" is not itself a sanitizer.
  { id: "N-CMD-ZOD-GUARD", kind: "negative", cls: "Command injection cleared by a zod schema with an anchored allowlist regex", location: "cmd-zod-guard-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#1027: `z.string().regex(/^[a-z]+$/).safeParse(req.query.action)` with an early return on !success in pages/api/cmd-zod-guard-safe.js, and the shell reads `parsed.data` — the value the SCHEMA produced. The schema-validator arm of the (a2) guard sanitizer — cleared. Measured as the largest unmodeled guard sub-population in the #989 census and the idiomatic Next/Express shape." },
  { id: "N-CMD-ZOD-ENUM-GUARD", kind: "negative", cls: "Command injection cleared by a z.enum membership schema", location: "cmd-zod-enum-guard-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#1027: `z.enum([\"status\",\"uptime\",\"whoami\"]).safeParse(...)` in pages/api/cmd-zod-enum-guard-safe.js — exact-match membership, so `parsed.data` can only be one of three constants. The enum arm of the schema-validator sanitizer — cleared." },
  { id: "N-CMD-SET-GUARD", kind: "negative", cls: "Command injection cleared by a Set-backed allowlist guard", location: "cmd-set-guard-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#1027: `if (!ALLOWED_ACTIONS.has(cmd)) { …; return; }` in pages/api/cmd-set-guard-safe.js — the same exact-match membership test as the shipped `.includes` arm, expressed on a Set. Cleared." },
  { id: "P-CMD-ZOD-BARE-STRING", kind: "positive", cls: "Command injection behind a schema that accepts every string", location: "cmd-zod-bare-string.js", match: ["command"], expectedTier: "high", note: "#1027 SOUNDNESS: pages/api/cmd-zod-bare-string.js wears the entire safe-twin shape — safeParse, early return on !success, sink reads `parsed.data` — but the schema is a bare `z.string()`. Every string parses, so `parsed.data` IS the request value and `status; rm -rf /` reaches the shell. The sanitizer requires the schema to carry an anchored positive-class regex or an enum, so this must STILL fire at high. This is the constraint unique to schema guards: a schema is not a sanitizer, an ALLOWLIST is." },
  { id: "P-CMD-ZOD-UNANCHORED", kind: "positive", cls: "Command injection behind an unanchored schema regex", location: "cmd-zod-unanchored.js", match: ["command"], expectedTier: "high", note: "#1027 SOUNDNESS: `z.string().regex(/[a-z]+/)` — positive class, early return, but UNANCHORED; zod's .regex() uses RegExp.test, which matches anywhere, so `status; rm -rf /` passes on its leading `status`. The anchoring constraint #989 proved on the bare `.test()` form, re-proven on the schema path — must STILL fire at high." },
  { id: "P-CMD-SET-GUARD-NO-RETURN", kind: "positive", cls: "Command injection where a Set allowlist's failure branch does not return", location: "cmd-set-guard-no-return.js", match: ["command"], expectedTier: "high", note: "#1027 SOUNDNESS: `ALLOWED_ACTIONS.has(cmd)` is consulted but the failure branch only logs, so execution falls through to the shell with the rejected value intact. The sanitizer matches the whole guard STATEMENT (test AND early return), so this must STILL fire at high — the case a bare `pattern: $SET.has($X)` sanitizer silently clears." },

  // #1057: the fourth and last guard form #1027 measured but refused — a PROJECTION guard, where
  // the allowlist is checked on `new URL(x).hostname` while the sink receives `x`. The five
  // positives came FIRST and each is a working alarm: MEASURED 2026-07-26, loosening one soundness
  // constraint at a time in a scratch copy of the rules dir silences exactly one of them (affix
  // membership → P-…-AFFIX; drop the early return → P-…-NO-RETURN; match the guard condition
  // deeply so a nested boolean qualifies → P-…-RELATIVE; unpin the projection from the WHATWG
  // constructor → both P-…-USERINFO rows). P-…-BACKSLASH is the alarm on the guard being on EVERY
  // path rather than nested behind another condition: unwrapping its outer `if` — the only edit —
  // makes it clear, which is the same file as N-REDIRECT-HOST-ALLOWLIST.
  { id: "N-REDIRECT-HOST-ALLOWLIST", kind: "negative", cls: "Open redirect cleared by a WHATWG host-projection allowlist", location: "redirect-host-allowlist-safe.js", note: "#1057: `new URL(next).hostname` — ONE argument, so `next` must be absolute — checked against an exact-match array allowlist with an early return on both the parse failure and the rejection. What passes is a URL whose WHATWG host is one of two constants, and that is exactly the host the browser contacts. The projection arm of the (a2) guard sanitizer — cleared." },
  { id: "N-SSRF-HOST-ALLOWLIST", kind: "negative", cls: "SSRF cleared by a Set-backed WHATWG host-projection allowlist", location: "ssrf-host-allowlist-safe.js", note: "#1057: the same projection guard on the fetch() side, expressed with the Set membership arm. Proves the sanitizer is on harvey-ssrf-fetch as well as harvey-open-redirect — extending the plain (a2) block to this rule was measured INERT in #1027 because the guard never sits on the value the fetch receives." },
  { id: "P-REDIRECT-HOST-USERINFO", kind: "positive", cls: "Open redirect behind a hand-rolled host projection", location: "redirect-host-userinfo.js", match: ["open-redirect"], expectedTier: "review", note: "#1057 SOUNDNESS: exact-match allowlist, early return — but the host is extracted by `.replace(/^https?:\\/\\//).split('/')[0].split('@')[0]`, not by a URL parser. `https://api.trusted.example@evil.tld/` reads as `api.trusted.example` to that extractor and as `evil.tld` to every WHATWG parser, so the allowlist passes and the browser leaves the site. The sanitizer is anchored on `new URL($X).hostname` precisely because the soundness comes from the PARSER, not from the guard — must STILL fire." },
  { id: "P-SSRF-HOST-USERINFO", kind: "positive", cls: "SSRF behind a hand-rolled host projection", location: "ssrf-host-userinfo.js", match: ["ssrf-fetch"], expectedTier: "review", note: "#1057 SOUNDNESS: the fetch() twin of P-REDIRECT-HOST-USERINFO, same userinfo payload. Present so the projection constraint is proven on BOTH rules carrying the sanitizer rather than on one of them — must STILL fire." },
  { id: "P-REDIRECT-HOST-RELATIVE", kind: "positive", cls: "Open redirect where a protocol-relative value skips the host allowlist", location: "redirect-host-relative.js", match: ["open-redirect"], expectedTier: "review", note: "#1057 SOUNDNESS: the projection IS `new URL(next).hostname`, but `//evil.tld` has no scheme, `new URL` throws, the catch leaves parsedHost null and the guard's own `parsedHost !== null` short-circuit skips the membership test entirely. The sanitizer requires the membership test to be the WHOLE guard condition; a guard the sink can be reached without is not a sanitizer — must STILL fire." },
  { id: "P-REDIRECT-HOST-BACKSLASH", kind: "positive", cls: "Open redirect where a backslash-prefixed value skips the host allowlist", location: "redirect-host-backslash.js", match: ["open-redirect"], expectedTier: "review", note: "#1057 SOUNDNESS: the host allowlist runs only inside a `/^https?:\\/\\//` pre-test, so `/\\evil.tld` walks past it to res.redirect — and every WHATWG parser normalises the leading backslash, so the browser reads `//evil.tld`. The sanitizer is anchored at the PROJECTION SITE, a point on the dataflow path, so the path that skips the projection is never cleared — must STILL fire." },
  { id: "P-REDIRECT-HOST-AFFIX", kind: "positive", cls: "Open redirect behind an affix host allowlist", location: "redirect-host-affix.js", match: ["open-redirect"], expectedTier: "review", note: "#1057 SOUNDNESS: correct WHATWG projection, early return — but the membership test is `.endsWith('trusted.example')`, and `evilapi.trusted.example` is registrable by anyone. The #1027 class-1 refusal (affix guards are unsound the way an unanchored regex is) restated on the projection: the sanitizer models exact `.includes`/`.has` membership only — must STILL fire." },
  { id: "P-REDIRECT-HOST-NO-RETURN", kind: "positive", cls: "Open redirect where the host allowlist's failure branch does not return", location: "redirect-host-no-return.js", match: ["open-redirect"], expectedTier: "review", note: "#1057 SOUNDNESS: correct projection, exact membership, but the rejection branch only writes a status — execution falls through to res.redirect with the rejected host intact. The #989 whole-guard-STATEMENT constraint re-proven on the projection form — must STILL fire." },

  // #1236: the BRACELESS early return. Every (a2) arm above matched only `if (!ok) { … return; }`,
  // so `if (!ok) return Response.json(…)` — the dominant App Router idiom, and the only spelling
  // available to a handler that must RETURN its error response — read as unguarded. MEASURED
  // 2026-07-27 (semgrep 1.164.0) against planted braceless twins of the safe fixtures: SQLi,
  // command injection and the schema arm all fired on correct code.
  //
  // Widening a SANITIZER trades recall for precision, so every arm carries its adversarial twins
  // BELOW as well as its clearing negative. The soundness argument is the ECMAScript one: an
  // IfStatement's consequent may be any Statement, and a bare `return;`/`return <expr>;` leaves the
  // function exactly as a block containing only that return does — the block form's `...` merely
  // permits statements BEFORE the return, so the braceless form is a strict subset of it, never a
  // weaker check. What the widened pattern still requires is unchanged: the test is NEGATED, the
  // consequent IS a return, and the regex/schema constraints are on a separate conjunct. The three
  // #1057 projection positives that key on the PROJECTION rather than the consequent
  // (P-REDIRECT-HOST-USERINFO, -RELATIVE, -BACKSLASH) are deliberately not twinned: the widening
  // does not touch the `new URL($X).hostname` conjunct they exercise.
  { id: "N-SQLI-REGEX-GUARD-BRACELESS", kind: "negative", cls: "SQLi cleared by a braceless anchored allowlist-regex guard", location: "sqli-regex-guard-braceless-safe.js", note: "#1236: the braceless twin of N-SQLI-REGEX-GUARD, spelled with a bare `return;` so the widened arm is proven on a return with NO value as well as `return <expr>;`. Before #1236 this correct code was reported as a Critical SQLi." },
  { id: "N-SQLI-ENUM-GUARD-BRACELESS", kind: "negative", cls: "SQLi cleared by a braceless enum-allowlist guard", location: "sqli-enum-guard-braceless-safe.js", note: "#1236: the braceless twin of N-SQLI-ENUM-GUARD — the array-`.includes` arm, returning a response value rather than falling into a block." },
  { id: "N-CMD-SET-GUARD-BRACELESS", kind: "negative", cls: "Command injection cleared by a braceless Set-allowlist guard", location: "cmd-set-guard-braceless-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#1236: the braceless twin of N-CMD-SET-GUARD — the `Set.has` arm." },
  { id: "N-CMD-ZOD-GUARD-BRACELESS", kind: "negative", cls: "Command injection cleared by a braceless zod schema guard", location: "cmd-zod-guard-braceless-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#1236: the braceless twin of N-CMD-ZOD-GUARD — the schema-validator arm, `if (!parsed.success) return <expr>;`. The zod arm is the idiomatic Next/Express shape, and the braceless return is the idiomatic way to write it." },
  { id: "N-CMD-ZOD-ENUM-GUARD-BRACELESS", kind: "negative", cls: "Command injection cleared by a braceless z.enum membership guard", location: "cmd-zod-enum-guard-braceless-safe.js", match: ["command"], reviewTierHits: ["javascript.lang.security.detect-child-process.detect-child-process"], note: "#1236: the braceless twin of N-CMD-ZOD-ENUM-GUARD — the `z.enum` membership arm." },
  { id: "N-REDIRECT-HOST-ALLOWLIST-BRACELESS", kind: "negative", cls: "Open redirect cleared by a braceless host-projection allowlist", location: "redirect-host-allowlist-braceless-safe.js", note: "#1236: the braceless twin of N-REDIRECT-HOST-ALLOWLIST — the #1057 WHATWG host-projection guard with braceless early returns on the parse failure and the rejection." },
  { id: "N-SSRF-HOST-ALLOWLIST-BRACELESS", kind: "negative", cls: "SSRF cleared by a braceless Set-backed host-projection allowlist", location: "ssrf-host-allowlist-braceless-safe.js", note: "#1236: the braceless twin of N-SSRF-HOST-ALLOWLIST — proves the widened projection arm reaches harvey-ssrf-fetch as well as harvey-open-redirect." },
  { id: "N-AR-CMD-GUARD-BRACELESS", kind: "negative", cls: "App Router command guard cleared by a braceless Response.json early return", location: "ar-cmd-guard-braceless-safe", match: ["command"], note: "#1236: the headline shape of the bug — an App Router handler CANNOT write to a `res`, it must RETURN its error response, so `if (!ok) return Response.json({…}, { status: 400 })` is not a style choice but the only spelling available. MEASURED 2026-07-27: before the widening this correct handler was reported as a Critical command injection." },
  { id: "P-AR-CMD-GUARD-WRONG-BRANCH", kind: "positive", cls: "App Router command injection where the guard returns on the PASSING branch", location: "ar-cmd-guard-wrong-branch", match: ["command"], expectedTier: "high", note: "#1236 SOUNDNESS: exact allowlist, braceless App Router early return — but the test is NOT negated, so the handler bails on the three allowed values and reaches the shell with everything else. The widened arms all keep the `!`; a guard matched on the test alone would clear this. Must STILL fire at high." },
  { id: "P-SQLI-DENYLIST-GUARD-BRACELESS", kind: "positive", cls: "SQLi behind a braceless NEGATED-class (denylist) guard", location: "sqli-denylist-guard-braceless.js", match: ["sql-injection"], expectedTier: "high", note: "#1236 SOUNDNESS: the braceless twin of P-SQLI-DENYLIST-GUARD. The positive-class metavariable-regex is a separate conjunct from the guard shape, and this proves the widening did not disturb it — must STILL fire at high." },
  { id: "P-SQLI-UNANCHORED-GUARD-BRACELESS", kind: "positive", cls: "SQLi behind a braceless unanchored allowlist regex", location: "sqli-unanchored-guard-braceless.js", match: ["sql-injection"], expectedTier: "high", note: "#1236 SOUNDNESS: the braceless twin of P-SQLI-UNANCHORED-GUARD — `/[a-zA-Z0-9_]+/` matches anywhere, so `id; drop table documents--` passes on its leading `id`. Must STILL fire at high." },
  { id: "P-SQLI-MFLAG-GUARD-BRACELESS", kind: "positive", cls: "SQLi behind a braceless anchored allowlist neutered by the /m flag", location: "sqli-mflag-guard-braceless.js", match: ["sql-injection"], expectedTier: "high", note: "#1236 SOUNDNESS: the braceless twin of P-SQLI-MFLAG-GUARD — the #1066 [isuvy] flag group must survive the widening. Must STILL fire at high." },
  { id: "P-SQLI-GUARD-BRACELESS-NO-RETURN", kind: "positive", cls: "SQLi where the braceless consequent is not a return", location: "sqli-guard-braceless-no-return.js", match: ["sql-injection"], expectedTier: "high", note: "#1236 SOUNDNESS: the shape the widening most risks swallowing — a braceless consequent that is NOT a return, so execution falls straight through to the query with the rejected value intact. The widened arm requires `return ...;` as the WHOLE consequent, so a bare statement there is not a guard. Must STILL fire at high." },
  { id: "P-CMD-SET-GUARD-WRONG-BRANCH", kind: "positive", cls: "Command injection where a Set allowlist returns on the PASSING branch", location: "cmd-set-guard-wrong-branch.js", match: ["command"], expectedTier: "high", note: "#1236 SOUNDNESS: the Pages Router spelling of P-AR-CMD-GUARD-WRONG-BRANCH, on the `Set.has` arm. Must STILL fire at high." },
  { id: "P-CMD-ZOD-BARE-STRING-BRACELESS", kind: "positive", cls: "Command injection behind a braceless guard on a schema that accepts every string", location: "cmd-zod-bare-string-braceless.js", match: ["command"], expectedTier: "high", note: "#1236 SOUNDNESS: the braceless twin of P-CMD-ZOD-BARE-STRING — a bare `z.string()` parses everything, so `parsed.data` IS the request value. A schema is not a sanitizer, an ALLOWLIST is. Must STILL fire at high." },
  { id: "P-CMD-ZOD-UNANCHORED-BRACELESS", kind: "positive", cls: "Command injection behind a braceless guard on an unanchored schema regex", location: "cmd-zod-unanchored-braceless.js", match: ["command"], expectedTier: "high", note: "#1236 SOUNDNESS: the braceless twin of P-CMD-ZOD-UNANCHORED — zod's `.regex()` uses RegExp.test, which matches anywhere. Must STILL fire at high." },
  { id: "P-REDIRECT-HOST-AFFIX-BRACELESS", kind: "positive", cls: "Open redirect behind a braceless affix host allowlist", location: "redirect-host-affix-braceless.js", match: ["open-redirect"], expectedTier: "review", note: "#1236 SOUNDNESS: the braceless twin of P-REDIRECT-HOST-AFFIX — `.endsWith('trusted.example')` admits `evilapi.trusted.example`, which anyone can register. The widened projection arm still models exact `.includes`/`.has` membership only. Must STILL fire." },
  { id: "P-REDIRECT-HOST-BRACELESS-NO-RETURN", kind: "positive", cls: "Open redirect where the braceless host-allowlist consequent is not a return", location: "redirect-host-braceless-no-return.js", match: ["open-redirect"], expectedTier: "review", note: "#1236 SOUNDNESS: the braceless twin of P-REDIRECT-HOST-NO-RETURN, on the projection arm — a braceless consequent is only a guard when it RETURNS. Must STILL fire." },

  // #1363 — the HOISTED-CONSTANT spelling of the same (a2) validator guard. `metavariable-regex`
  // reads a metavariable's matched TEXT, so with `const OK = /^…$/` the constraint was being applied
  // to the identifier `OK` and never to the regex, and correct code read as vulnerable at HIGH tier
  // on a `precisionTier: high` rule. MEASURED 2026-07-31 with semgrep 1.164.0 over an independently
  // written fixture set: the braced and braceless named-const forms failed IDENTICALLY, which is
  // what shows this is NOT a #1236 regression — the braced form is the pre-#1236 shape and missed
  // too. The fix moves the anchoring/positive-class constraint onto the LITERAL the const binds,
  // so the three soundness positives below have to survive it; accepting a named const
  // unconditionally would clear all three, which is why that option was rejected.
  { id: "N-SQLI-CONST-GUARD", kind: "negative", cls: "SQLi cleared by a BRACED guard on a hoisted anchored allowlist constant", location: "sqli-const-guard-safe.js", note: "#1363: N-SQLI-REGEX-GUARD with the regex hoisted to `const SORT_KEY = /^[a-zA-Z0-9_]+$/` — the normal spelling once the regex is reused, and the one that avoids recompiling it per request. Before the fix this correct handler was reported as a Critical SQL injection." },
  { id: "N-SQLI-CONST-GUARD-BRACELESS", kind: "negative", cls: "SQLi cleared by a BRACELESS guard on a hoisted anchored allowlist constant", location: "sqli-const-guard-braceless-safe.js", note: "#1363: the braceless twin of N-SQLI-CONST-GUARD. Both spellings are registered because both were broken — the pairing is the evidence that the named-const gap is pre-existing rather than something #1236 introduced." },
  { id: "P-SQLI-CONST-UNANCHORED-GUARD", kind: "positive", cls: "SQLi behind a hoisted UNANCHORED allowlist constant", location: "sqli-const-unanchored-guard.js", match: ["sql-injection"], expectedTier: "high", note: "#1363 SOUNDNESS: the hoisted twin of P-SQLI-UNANCHORED-GUARD. `/[a-zA-Z0-9_]+/` matches anywhere, so `id; drop table documents--` passes on its leading `id`. The anchoring check follows the regex to the literal the const binds; must STILL fire at high." },
  { id: "P-SQLI-CONST-DENYLIST-GUARD", kind: "positive", cls: "SQLi behind a hoisted NEGATED-class (denylist) allowlist constant", location: "sqli-const-denylist-guard.js", match: ["sql-injection"], expectedTier: "high", note: "#1363 SOUNDNESS: the hoisted twin of P-SQLI-DENYLIST-GUARD — a negated character class is a denylist, not an allowlist. The positive-class half of the constraint moves to $LIT with the anchoring half; must STILL fire at high." },
  { id: "P-SQLI-REASSIGNED-GUARD", kind: "positive", cls: "SQLi where the hoisted allowlist regex is REASSIGNED to a permissive one before the guard", location: "sqli-reassigned-guard.js", match: ["sql-injection"], expectedTier: "high", note: "#1363 SOUNDNESS, and the reason the new arm binds a `const` DECLARATION rather than a bare `$RE = $LIT` assignment. MEASURED 2026-07-31: with the bare-assignment binding semgrep satisfies the anchoring constraint from the FIRST assignment, a literal no longer in force, and this handler goes SILENT — a sanitizer clearing a real bug. The `const` binding rules the shape out; this row is what keeps that choice honest, and it is also why the `let`/`var` spellings are deliberately left drawing the finding (an over-report, never a missed bug). Must fire at high." },

  // #946: LIBRARY-INTERNAL parameter-sourced taint. The injection rules above all key on an HTTP
  // REQUEST source (req.query/body/params/cookies/headers, App-Router searchParams). These prove the
  // new library-taint.yml axis: a taint source that is a PARAMETER of a public library entry point —
  // an exported function, or a raw node http/https server's request callback — with no request layer
  // at all. This is the axis SecBench.js exercises (measured 0/600 through the request rules), scoped
  // in by the operator 2026-07-26. All are review tier: a function parameter is a far broader source
  // than a request object, so these never enter the free/high count.
  { id: "P-LIB-PATH-TRAVERSAL", kind: "positive", cls: "Library-internal path traversal via exported-function param", location: "lib-file-reader.js", match: ["traversal"], expectedTier: "review", note: "#946: the exported readUserFile(name) joins its param into fs.readFileSync(path.join('/var/data/uploads', name)) with no containment in lib/lib-file-reader.js — the @vivaxy/here / asset-cache SecBench path-traversal shape. harvey-lib-path-traversal source B (exported-function parameter) → review." },
  { id: "P-LIB-HTTP-TRAVERSAL", kind: "positive", cls: "Library-internal path traversal via http.createServer request param", location: "lib-static-server.js", match: ["traversal"], expectedTier: "review", note: "#946: a raw node http server whose request-callback param req.url is concatenated into a path and read via fs.readFile in lib/lib-static-server.js — the DOMINANT SecBench path-traversal shape, which the Express/Next request sources never modelled. harvey-lib-path-traversal source A (http/https server request callback) → review." },
  { id: "P-LIB-CMD-INJECTION", kind: "positive", cls: "Library-internal command injection via exported-function param", location: "lib-exec-runner.js", match: ["command"], expectedTier: "review", note: "#946: the exported ping(target) interpolates its param into exec(`ping -c 1 ${target}`) in lib/lib-exec-runner.js — library-internal OS command injection (the SecBench command-injection shape, request layer removed). harvey-lib-command-injection → review." },
  { id: "P-LIB-CODE-INJECTION", kind: "positive", cls: "Library-internal code injection via exported-function param", location: "lib-exec-runner.js", match: ["code"], expectedTier: "review", note: "#946: the exported compute(formula) passes its param to eval(formula) in lib/lib-exec-runner.js — library-internal code injection. harvey-lib-code-injection → review." },
  { id: "N-LIB-PATH-SANITIZED", kind: "negative", cls: "Exported-function param confined with path.basename", location: "lib-safe-reader.js", match: ["traversal"], note: "#946: readSafeFile(name) reads fs.readFileSync(path.join(base, path.basename(name))) in lib/lib-safe-reader.js — path.basename strips every directory component and is registered as the harvey-lib-path-traversal sanitizer, so the parameter source must NOT fire. The guard that keeps parameter-as-source from flagging every exported file reader." },
  { id: "N-LIB-PARAM-NOSINK", kind: "negative", cls: "Exported-function param that never reaches a sink", location: "lib-safe-reader.js", match: ["traversal"], note: "#946: greet(name) returns a template string and reaches no fs/exec/eval sink in lib/lib-safe-reader.js. Parameter-as-source is taint-gated on REACHING a sink, so an ordinary exported function must stay silent — the regression guard that the broad new source does not fire on every exported function." },
  { id: "N-LIB-EXEC-NOSINK", kind: "negative", cls: "Exported-function param used only as data, no exec/eval", location: "lib-safe-runner.js", match: ["command", "code"], note: "#946: label(name) returns `job:${name}` and reaches no exec/eval in lib/lib-safe-runner.js. harvey-lib-command-injection / harvey-lib-code-injection are taint-gated on reaching the shell/eval sink, so a param used only as string data stays silent." },
];
