// Batch B4 — XSS & client-side sink family (#71, spec §"Batch 2 — XSS & client-side sink
// family"). Custom Semgrep taint rules (src/scan/rules/semgrep/xss.yml) scored against targets/
// calibration. Tiering follows the locked preamble: only ~100%-precision sinks are `high` (free
// count) — .innerHTML/insertAdjacentHTML and document.write, which execute markup/script
// unconditionally once the source is tainted. The heuristic sinks (href scheme, window.location
// assignment, setAttribute, a DB-read source reaching dangerouslySetInnerHTML) are `review`.
// XSS-via-tainted-dangerouslySetInnerHTML (P-XSS-DSIH) and its sanitized/constant lookalike
// (N-DSIH-SANITIZED) already ship in base.entries.ts; B4 does not duplicate them. See
// GROUND-TRUTH.md §B4.

import type { CorpusEntry } from "./types.js";

export const b4XssEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-DOM-XSS-INNERHTML", kind: "positive", cls: "DOM XSS via .innerHTML", location: "Widget.jsx", match: ["innerhtml"], expectedTier: "high", note: "router.query.q assigned straight to ref.current.innerHTML in components/Widget.jsx. harvey-dom-innerhtml taint (router.query/location/searchParams → innerHTML/insertAdjacentHTML, sanitizer stop) → high." },
  { id: "P-DOM-XSS-DOCWRITE", kind: "positive", cls: "DOM XSS via document.write", location: "Embed.jsx", match: ["document-write"], expectedTier: "high", note: "location.hash (URL fragment) flows into document.write() in components/Embed.jsx. harvey-document-write taint → high." },
  { id: "P-XSS-STORED-DSIH", kind: "positive", cls: "Stored XSS — DB value into dangerouslySetInnerHTML", location: "comment.js", match: ["stored"], expectedTier: "review", note: "A Supabase select().single() result flows into __html with no sanitizer in pages/comment.js — stored XSS (persisted payload, not reflected). harvey-dangerously-set-inner-html-stored taint (supabase .from().select() → dangerouslySetInnerHTML) → review." },

  // #613 (vibe-dummy stage-06/10) — the prop/param-sourced dangerouslySetInnerHTML family. The stored
  // rule keys on a Supabase select and the reflected rule on request sources; neither matches HTML that
  // arrives as a component prop or function parameter, which is the common React shape.
  { id: "P-DSIH-PROP", kind: "positive", cls: "prop/param value into dangerouslySetInnerHTML, no sanitizer", location: "UserBioDangerous.tsx", match: ["inner-html-prop"], expectedTier: "review", note: "#613: components/UserBioDangerous.tsx renders <div dangerouslySetInnerHTML={{ __html: user.bio }} /> (a prop member) and __html: html (a bare param) with no sanitizer. harvey-dangerously-set-inner-html-prop matches any non-literal, non-sanitized $VAL (string literals — incl. propagated consts — and DOMPurify.sanitize/sanitizeHtml/sanitize/escapeHtml wraps excluded via metavariable-pattern) → review. The prop/param source facet neither the stored (DB) nor reflected (request) rule covered." },
  { id: "N-DSIH-PROP-ESCAPED", kind: "negative", cls: "prop escaped before __html + constant literal + plain text", location: "UserBioSafe.tsx", match: ["inner-html-prop"], note: "#613 stage-11 control: components/UserBioSafe.tsx wraps the prop in escapeHtml() before __html, renders a constant STATIC_HTML literal, and interpolates {user.bio} as plain JSX text. harvey-dangerously-set-inner-html-prop excludes sanitizer wraps and (via constant propagation) string-literal consts, and plain text is not a dangerouslySetInnerHTML sink at all — cleared. Also proves it stays dark on the existing pages/about.js STATIC_BIO/sanitizeHtml negative." },
  { id: "P-XSS-LOCAL-SANITIZE", kind: "positive", cls: "XSS cleared by a locally-defined no-op named sanitize", location: "UserBioLocalSanitize.tsx", match: ["inner-html-prop"], expectedTier: "review", note: "#1066 SOUNDNESS: components/UserBioLocalSanitize.tsx wraps the prop in `sanitize(...)` where `sanitize` is a pass-through defined three lines below the sink. Every XSS rule excluded a BARE `sanitize(...)` by name, so the audited party could clear a real XSS by naming a function — the #989 lesson (a sanitizer that silently clears real bugs scores identically to doing nothing) recurring in the rules #989 did not touch. The exclusion now requires an import binding, so this must STILL fire." },
  { id: "N-XSS-IMPORT-SANITIZE", kind: "negative", cls: "XSS cleared by an import-bound library sanitize", location: "UserBioImportSanitize.tsx", match: ["inner-html-prop"], note: "#1066 control: components/UserBioImportSanitize.tsx applies the SAME `sanitize(...)` wrap, but the name resolves to `import { sanitize } from \"isomorphic-dompurify\"`. Proves the #1066 tightening narrowed the sanitizer exclusion rather than deleting it — cleared." },
  { id: "P-XSS-HREF-JS", kind: "positive", cls: "javascript: URL XSS via <a href>", location: "AnchorLink.jsx", match: ["href-js-url"], expectedTier: "review", note: "router.query.next flows into a native <a href> with no scheme allowlist in components/AnchorLink.jsx. harvey-href-js-url taint → review." },
  { id: "P-XSS-DANGEROUS-URL", kind: "positive", cls: "Open-URL sink via window.location assignment", location: "LocationNav.jsx", match: ["open-url-sink"], expectedTier: "review", note: "A URLSearchParams 'to' value is assigned directly to window.location in components/LocationNav.jsx. harvey-open-url-sink taint → review." },
  { id: "P-XSS-SETATTR", kind: "positive", cls: "javascript: URL XSS via setAttribute", location: "ImgAttr.jsx", match: ["set-attribute-xss"], expectedTier: "review", note: "router.query.avatar flows into ref.current.setAttribute('src', ...) in components/ImgAttr.jsx. harvey-set-attribute-xss taint → review." },

  // #1223: the DOM-XSS fragment source. The same drift as #1221 reaching the client rules — three
  // URL sinks were blind to location.hash/.search while two sibling rules in the same file already
  // declared both. `match` asserts the RULE ID (#1222).
  { id: "P-XSS-HASH-OPENURL", kind: "positive", cls: "DOM XSS — URL fragment assigned to window.location", location: "HashNav.jsx", match: ["harvey-open-url-sink"], expectedTier: "review", expectedSeverity: "Medium", note: "#1223: components/HashNav.jsx assigns location.hash.slice(1) to window.location.href. The fragment is the canonical DOM-XSS source precisely because it never reaches the server — invisible to every server-side control and to a WAF — and it is the shape most client-side PoCs use. MEASURED silent 2026-07-27 with the searchParams control firing on the same sink. → review." },
  { id: "P-XSS-SEARCH-SETATTR", kind: "positive", cls: "DOM XSS — raw location.search into setAttribute(\"href\")", location: "SearchAttr.jsx", match: ["harvey-set-attribute-xss"], expectedTier: "review", expectedSeverity: "Medium", note: "#1223: components/SearchAttr.jsx reads the raw query STRING (location.search, not via URLSearchParams) into setAttribute('href', …). The rule saw `$SP.get(...)` but not the raw-string read, so a component that parses the query itself went dark. → review." },
  { id: "P-XSS-HASH-HREF", kind: "positive", cls: "DOM XSS — URL fragment into a native <a href>", location: "HashAnchor.jsx", match: ["harvey-href-js-url"], expectedTier: "review", expectedSeverity: "Medium", note: "#1223: components/HashAnchor.jsx puts location.hash.slice(1) in a native <a href> with no scheme allowlist, so `#javascript:alert(1)` runs on click. harvey-href-js-url was NOT named in #1223's scope, but the same probe measured it equally blind to the fragment — folded in rather than left as a third instance of one defect. → review." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-XSS-HASH-ALLOWLISTED", kind: "negative", cls: "Fragment route gated by an exact-match allowlist", location: "HashNavAllowlisted.jsx", note: "#1223: components/HashNavAllowlisted.jsx uses the same fragment source and window.location sink as HashNav, gated by `ALLOWED_ROUTES.includes(to)` with an early return. The three URL sink rules carried NO sanitizers at all before this, so adding the fragment source without a guard model would have made every correctly-written fragment router a finding — the guard lands with the source for that reason. MEASURED: the guard had to match the BRACELESS early return (`return ...;`), because the block-only form the shipped (a2) arms use missed this fixture." },
  { id: "N-INNERHTML-STATIC", kind: "negative", cls: "innerHTML assigned a constant literal", location: "WidgetSafe.jsx", note: "ref.current.innerHTML = '<strong>Loading…</strong>' in components/WidgetSafe.jsx — constant string, no tainted source. harvey-dom-innerhtml fires only on router.query/location/searchParams — cleared." },
  { id: "N-HREF-INTERNAL", kind: "negative", cls: "href from a constant internal route", location: "NavLink.jsx", note: "<Link href=\"/dashboard\"> in components/NavLink.jsx — next/link, constant string, not a native <a> and not request-derived. harvey-href-js-url fires only on a native <a href={...}> from a tainted source — cleared." },
  { id: "N-SEARCHPARAMS-TEXT", kind: "negative", cls: "searchParams value rendered as text", location: "search-results.js", note: "<p>Results for: {router.query.q}</p> in pages/search-results.js — React text child, auto-escaped, never an innerHTML/href/setAttribute/document.write sink. None of the B4 rules match a plain text expression — cleared." },
];
