// Batch B5 (#71, spec §"Batch 6 — Headers / CORS / CSRF / transport / error-hygiene").
// Custom Semgrep rules (src/scan/rules/semgrep/headers.yml) scored against targets/calibration.
// Tiering follows the locked preamble: only the reflected-origin CORS rule and the bare-cookie
// rule are ~100%-precision sinks (`high`, free count); the rest are heuristic presence/pattern
// checks (`review`). P-NO-CSP (checkMissingCsp) and P-CORS-WILDCARD (harvey-permissive-cors)
// already ship in base.entries.ts and P-OPEN-REDIRECT ([exists]) too — not duplicated here. See
// GROUND-TRUTH.md §B5.

import type { CorpusEntry } from "./types.js";

export const b5HeadersEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-CORS-REFLECT-ORIGIN", kind: "positive", cls: "CORS reflects Origin + credentials", location: "middleware.ts", match: ["cors-reflected-origin"], expectedTier: "high", note: "Access-Control-Allow-Origin set to req.headers.get('origin') verbatim + Allow-Credentials true, in middleware.ts. harvey-cors-reflected-origin (two-statement pattern requiring both header sets in the same function) → high." },
  { id: "P-COOKIE-INSECURE", kind: "positive", cls: "Session cookie w/ no Secure/HttpOnly/SameSite", location: "pages/api/session.js", match: ["cookie-insecure"], expectedTier: "high", note: "res.setHeader('Set-Cookie', 'sid=' + sessionId) with zero attributes in pages/api/session.js. harvey-cookie-insecure (metavariable-regex: cookie value has no semicolon) → high." },
  { id: "P-COOKIE-EXPRESS-INSECURE", kind: "positive", cls: "Express res.cookie() missing HttpOnly/Secure/SameSite", location: "pages/api/cookie-express.js", match: ["cookie-insecure-express"], expectedTier: "high", note: "#988: res.cookie('session', sessionId, { maxAge: 900000 }) in pages/api/cookie-express.js — the Express method form with an options object that omits all three security flags. harvey-cookie-insecure-express (fires unless httpOnly+secure+sameSite are all set) → high." },
  { id: "P-CSP-UNSAFE-INLINE", kind: "positive", cls: "CSP present but script-src allows unsafe-inline", location: "lib/security-headers.js", match: ["csp-unsafe-inline"], expectedTier: "review", note: "A CSP header object with script-src 'self' 'unsafe-inline' in lib/security-headers.js (kept out of next.config.js/middleware.ts/vercel.json so it doesn't flip the existing P-NO-CSP fixture off). harvey-csp-unsafe-inline (metavariable-regex on the CSP value) → review." },
  { id: "P-NO-HSTS", kind: "positive", cls: "Missing Strict-Transport-Security", location: "next.config.js", match: ["missing-hsts"], expectedTier: "review", note: "next.config.js headers() default route sets one unrelated header, omits HSTS. harvey-missing-hsts (pattern-not: array has no {key:'Strict-Transport-Security',...} element) → review." },
  { id: "P-NO-FRAME-OPTIONS", kind: "positive", cls: "Missing X-Frame-Options (clickjacking)", location: "next.config.js", match: ["missing-frame-options"], expectedTier: "review", note: "Same next.config.js default route omits X-Frame-Options. harvey-missing-frame-options → review." },
  { id: "P-NO-NOSNIFF", kind: "positive", cls: "Missing X-Content-Type-Options: nosniff", location: "next.config.js", match: ["missing-nosniff"], expectedTier: "review", note: "Same next.config.js default route omits X-Content-Type-Options. harvey-missing-nosniff → review." },
  { id: "P-CSRF-MISSING", kind: "positive", cls: "Cookie-authed mutation w/ no Origin/CSRF check", location: "app/actions.ts", match: ["csrf-missing"], expectedTier: "review", note: "'use server' deleteAccount() calls supabase.from('accounts').delete() with no Origin check anywhere in the function, in app/actions.ts. harvey-csrf-missing (pattern-not-inside: no headers().get('origin') call) → review." },
  { id: "P-VERBOSE-ERROR", kind: "positive", cls: "Stack trace echoed to client", location: "pages/api/verbose.js", match: ["verbose-error"], expectedTier: "review", note: "catch (err) { res.status(500).json({ ok: false, stack: err.stack }) } in pages/api/verbose.js. harvey-verbose-error → review." },
  { id: "P-DB-ERROR-DISCLOSURE", kind: "positive", cls: "Raw Postgres/PostgREST error echoed to client", location: "pages/api/orders.js", match: ["db-error-disclosure"], expectedTier: "review", note: "res.status(500).json(error) with the raw supabase-js destructured error object, in pages/api/orders.js. harvey-db-error-disclosure (matches the literal `error` identifier by name) → review." },
  { id: "P-NODE-ENV-NOT-PROD", kind: "positive", cls: "NODE_ENV force-assigned to a non-prod value", location: "lib/env.js", match: ["node-env-not-prod"], expectedTier: "review", note: "process.env.NODE_ENV = 'development' hardcoded in lib/env.js. harvey-node-env-not-prod → review." },
  { id: "P-VERBOSE-ERROR-APPROUTER", kind: "positive", cls: "Error stack echoed to the client from an App Router route handler", location: "app/api/ar-debug-env/route.ts", match: ["verbose-error"], expectedTier: "review", note: "#1184 (cipherx CX-18): `return NextResponse.json({ …, stack: (err as Error).stack, … }, { status: 500 })`. harvey-verbose-error's four original patterns were all Express-shaped AND single-argument, so the App Router form — a second `init` argument — matched none of them; MEASURED 2026-07-27, the whole file produced zero harvey findings before this change. The patterns now use `$RES.json(…, ...)`, which covers res.json / NextResponse.json / Response.json in one and admits the init argument while still matching the one-argument call (P-VERBOSE-ERROR, pages/api/verbose.js, still fires). → review." },
  { id: "P-INTERNAL-STATE-RESPONSE", kind: "positive", cls: "process.env / process.cwd() returned in a response body", location: "app/api/ar-debug-env/route.ts", match: ["internal-state-response"], expectedTier: "review", expectedSeverity: "Medium", note: "#1184 (cipherx CX-18): the same handler also returns `cwd: process.cwd()` and `env: process.env`. cipherx's debug route was recorded as caught only for the connection string that happened to be embedded in the env dump — the dump itself, the cwd and the stack were 'semantic-only'. harvey-internal-state-response matches process.env / process.cwd() in a RESPONSE position only; reading process.env to configure a client and logging process.cwd() server-side are the normal uses and must not fire. Matches the object as a WHOLE (`process.env`), not a single read (`process.env.NEXT_PUBLIC_URL`), so echoing one already-public config value back is not a hit. → review (Medium)." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-VERBOSE-ERROR-LOGGED-NOT-RETURNED", kind: "negative", cls: "App Router handler that LOGS the stack/cwd/env server-side and returns a generic message", location: "app/api/ar-debug-env-safe/route.ts", match: ["verbose-error", "internal-state-response"], note: "#1184: `console.error('report load failed', (err as Error).stack, process.cwd(), process.env.NODE_ENV)` followed by `return NextResponse.json({ message: 'Unable to load that report' }, { status: 500 })`. Every token the two rules key on is present in the file — .stack, process.cwd(), process.env — and none of them is in a response body. This is the whole precision argument for both rules: logging the detail is the RECOMMENDED practice, returning it is the defect, so a file-level keyword match would flag correct code. match is scoped to the two rule ids so an unrelated route-level finding on this handler cannot stand in for them." },
  { id: "N-CORS-ALLOWLIST", kind: "negative", cls: "CORS origin checked against an explicit allowlist", location: "lib/cors-allowlist.js", reviewTierHits: ["javascript.express.security.cors-misconfiguration.cors-misconfiguration"], note: "Access-Control-Allow-Origin is only ever set to the validated `origin` variable, never directly to req.headers.get('origin'). harvey-cors-reflected-origin's two-statement pattern requires the literal req.headers.get('origin') expression as the value — cleared." },
  { id: "N-COOKIE-SECURE", kind: "negative", cls: "Session cookie hardened w/ HttpOnly/Secure/SameSite", location: "pages/api/session-secure.js", reviewTierHits: ["src.scan.rules.semgrep.harvey-crlf-header-injection"], note: "Set-Cookie value contains three semicolon-delimited attributes. harvey-cookie-insecure's metavariable-regex requires zero semicolons in the value — cleared." },
  { id: "N-COOKIE-EXPRESS-SECURE", kind: "negative", cls: "Express res.cookie() hardened w/ HttpOnly/Secure/SameSite", location: "pages/api/cookie-express-safe.js", note: "#988: res.cookie('session', sessionId, { httpOnly: true, secure: true, sameSite: 'strict', maxAge: 900000 }) in pages/api/cookie-express-safe.js. harvey-cookie-insecure-express's pattern-not excludes the fully-hardened form — cleared." },
  { id: "N-CSP-PRESENT", kind: "negative", cls: "Strict CSP with no unsafe-inline/unsafe-eval", location: "lib/security-headers.js", match: ["cspheaderstrict"], note: "script-src 'self' only, no unsafe-inline/unsafe-eval. harvey-csp-unsafe-inline's metavariable-regex requires that substring in script-src — cleared (review tier only regardless, since it shares a file with the P-CSP-UNSAFE-INLINE positive). match keyword is the export name, disjoint from the positive's 'csp-unsafe-inline' rule-id keyword, so the two fixtures in this file can't cross-attribute." },
  { id: "N-HEADERS-VERCEL", kind: "negative", cls: "Route with HSTS/X-Frame-Options/nosniff all present", location: "next.config.js", match: ["api-headers-route"], note: "The /api/(.*) headers() route sets Strict-Transport-Security, X-Frame-Options, and X-Content-Type-Options together (modeled as a second next.config.js route rather than vercel.json, so it's in the same globally-scanned config surface as the P-NO-HSTS/FRAME-OPTIONS/NOSNIFF positives without JSON-language parsing gaps). None of the three missing-header rules match this route object — cleared (review tier only regardless, since it shares a file with those positives). match keyword is disjoint from 'missing-hsts'/'missing-frame-options'/'missing-nosniff' so it can't cross-attribute to any of the three positives sharing this file." },
  { id: "N-CSRF-ORIGIN-CHECKED", kind: "negative", cls: "Cookie-authed mutation guarded by an Origin check", location: "app/actions.ts", match: ["origin-checked"], note: "updateAccountName() checks headers().get('origin') against an allowlisted APP_ORIGIN before mutating. harvey-csrf-missing's pattern-not-inside excludes any function containing that call — cleared (review tier only regardless, since it shares a file with the P-CSRF-MISSING positive). match keyword is disjoint from the positive's 'csrf-missing' rule-id keyword." },
  { id: "N-ERROR-GENERIC", kind: "negative", cls: "Generic error message, no stack/raw error object", location: "pages/api/orders-safe.js", reviewTierHits: ["src.scan.rules.semgrep.harvey-select-star-pii"], note: "res.status(500).json({ error: 'Server error' }) — a literal string, not err.stack/err.message or the raw `error` identifier. Clears both harvey-verbose-error and harvey-db-error-disclosure." },
  { id: "N-NODE-ENV-PROD", kind: "negative", cls: "NODE_ENV read (branch), never assigned", location: "lib/env-check.js", note: "if (process.env.NODE_ENV !== 'production') { ... } reads the value; harvey-node-env-not-prod only matches a literal assignment — cleared." },

  // #578 — security-header presence over a hosting config (public/_headers / netlify.toml / vercel.json),
  // for apps that set headers OUTSIDE next.config.js (the harvey-missing-* semgrep rules are next.config-
  // only). checkHostingConfigHeaders (src/scan/hosting-headers.ts). Positive-only in the corpus: the
  // check is a GLOBAL presence check over one well-known file set, so a headers-present negative can't
  // coexist in the same target — the negative is exercised by hosting-headers.test.ts (temp dirs).
  { id: "P-HOSTING-HEADERS-MISSING", kind: "positive", cls: "hosting config sets response headers but no security headers", location: "public/_headers", match: ["hosting-header"], expectedTier: "review", note: "#578: public/_headers (a Netlify-style hosting-header file — how a Vite/no-code SPA export sets headers) declares Cache-Control/X-DNS-Prefetch-Control but NO Strict-Transport-Security / X-Frame-Options / X-Content-Type-Options. checkHostingConfigHeaders emits HOSTING-HEADER-hsts/-frame-options/-nosniff → review. Sibling of checkMissingCsp for the non-Next hosting-config surface." },
];
