// Batch B7 — auth / access-control heuristics (#71, spec §"Batch 7 — Auth / access-control /
// left-open"). Custom Semgrep rules in src/scan/rules/semgrep/auth.yml, plus one extension to
// the existing leftover-auth grep (src/scan/leftover-auth.ts — a sensitive-auth-route +
// no-rate-limiter-hint check) and one reuse of its existing bypassAuth grep. Scheduled
// deliberately LAST in the #71 fan-out: it has the HIGHEST negative-precision risk in the corpus
// (a static tool cannot confirm an ownership/permission/rate-limit check is correct, only that
// the shape is absent), so EVERY entry here is `review` tier — none feed the free count.
// P-DEBUG-ENDPOINT, P-TODO-AUTH (leftover-auth greps, base.entries.ts) and P-SRV-KEY-CLIENT
// (harvey-service-role-in-client, base.yml) already ship — not duplicated here. See
// GROUND-TRUTH.md §B7.

import type { CorpusEntry } from "./types.js";

export const b7AuthEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught, all review tier) ---
  { id: "P-AUTH-BYPASS-CONST", kind: "positive", cls: "Hardcoded bypassAuth gate", location: "reports/export.js", match: ["bypassauth"], expectedTier: "review", note: "const bypassAuth = true; guards an admin.from('reports').select('*') call in pages/api/reports/export.js. leftover-auth's existing bypassAuth grep (src/scan/leftover-auth.ts) → review." },
  { id: "P-SERVER-ACTION-NOAUTH", kind: "positive", cls: "'use server' mutation w/ no authority check", location: "actions-auth.ts", match: ["server-action-noauth"], expectedTier: "review", note: "archiveDocument() in app/actions-auth.ts checks the request Origin but calls no assertPermission/requirePermission/requireRole before supabase.from('documents').update(). harvey-server-action-noauth → review." },
  { id: "P-ROUTE-NOAUTH", kind: "positive", cls: "Route handler mutation w/ no auth guard", location: "settings/delete.js", match: ["route-noauth"], expectedTier: "review", note: "pages/api/settings/delete.js deletes a settings row with no session read/supabase.auth.getUser() call anywhere in the handler. harvey-route-noauth → review." },
  { id: "P-ROUTE-NOAUTH-CUSTOM-VERB", kind: "positive", cls: "Route handler mutation w/ no auth guard (custom-verb regression guard)", location: "permissions/purge.js", match: ["route-noauth"], expectedTier: "review", note: "#126 regression guard: pages/api/permissions/purge.js calls scheduleCleanup() (not a recognized guard verb, no auth-ish token) before deleting, with no session read and no supabase.auth.getUser() call. Confirms the #126 broadened pattern-not-regex didn't over-suppress genuinely unguarded routes. harvey-route-noauth → review." },
  { id: "P-ROUTE-NOAUTH-DELETE-VERB", kind: "positive", cls: "App Router DELETE route handler mutation w/ no auth guard", location: "app/api/tenant-docs/route.ts", match: ["route-noauth"], expectedTier: "review", note: "#382: app/api/tenant-docs/route.ts exports an App Router DELETE handler that deletes a documents row with no session read/supabase.auth.getUser()/guard call anywhere in the body. Before #382 harvey-route-noauth's App Router half matched POST only, so this DELETE was silently never flagged. harvey-route-noauth → review." },
  { id: "P-ROUTE-NOAUTH-PUT-VERB", kind: "positive", cls: "App Router PUT route handler mutation w/ no auth guard", location: "app/api/tenant-profile/route.ts", match: ["route-noauth"], expectedTier: "review", note: "#382: app/api/tenant-profile/route.ts exports an App Router PUT handler that updates a profiles row with no auth-check call anywhere in the body — the idiomatic update verb, outside harvey-route-noauth's pre-#382 POST-only App Router pattern set. harvey-route-noauth → review." },
  { id: "P-IDOR-PARAM", kind: "positive", cls: "IDOR — id from request, no ownership predicate", location: "order/get.js", match: ["idor-param"], expectedTier: "review", note: "pages/api/order/get.js looks an order up by req.query.id alone — no owner/tenant .eq(). harvey-idor-param (taint: req.query -> exact-shape .eq('id', $ID) sink) → review." },
  { id: "P-MASS-ASSIGNMENT", kind: "positive", cls: "Mass assignment — req.body spread into update", location: "profile/settings.js", match: ["mass-assignment"], expectedTier: "review", note: "pages/api/profile/settings.js spreads the entire req.body into admin.from('profiles').update({ ...req.body }). harvey-mass-assignment (taint: req.body -> insert/update spread sink) → review." },
  { id: "P-SERVER-CLIENT-LEAK", kind: "positive", cls: "Full DB row spread into a Client Component", location: "documents/detail-page.tsx", match: ["server-client-leak"], expectedTier: "review", note: "app/documents/detail-page.tsx destructures a select('*') row and spreads it whole into <DocumentCard {...data} />, a 'use client' component. harvey-server-client-leak → review." },
  { id: "P-MISSING-SERVER-ONLY", kind: "positive", cls: "Secret module missing import 'server-only'", location: "lib/secret.js", match: ["missing-server-only"], expectedTier: "review", note: "lib/secret.js reads process.env.INTERNAL_API_SECRET with no 'import server-only' guard and no 'use client' (the more specific, already-covered case). harvey-missing-server-only → review." },
  { id: "P-NO-RATE-LIMIT", kind: "positive", cls: "Login route w/ no rate limiter", location: "auth/login.js", match: ["rate limit"], expectedTier: "review", note: "pages/api/auth/login.js calls admin.auth.signInWithPassword with no rate-limiter hint anywhere in the file. leftover-auth's new sensitive-auth-route + no-rate-limit-hint check (src/scan/leftover-auth.ts) → review." },
  { id: "P-FAIL-OPEN", kind: "positive", cls: "Rate-limit check fails open on backing-store error", location: "lib/rate-limiter.js", match: ["fail-open"], expectedTier: "review", note: "checkRateLimit() in lib/rate-limiter.js returns true from its catch block when the Redis call throws — an outage becomes an unlimited-request bypass. harvey-fail-open → review." },
  { id: "P-INMEMORY-RATE-LIMIT", kind: "positive", cls: "Rate limiter backed by process-local state (resets per serverless instance)", location: "lib/rate-limiter-memory.js", match: ["in-memory rate limiter"], expectedTier: "review", note: "#1046: lib/rate-limiter-memory.js counts attempts in a module-scope `new Map()`. On a serverless host every cold start starts from empty and each concurrent instance keeps its own counter, so the real budget is 10 × live instances and an attacker who paces requests never hits it. The capability docs/free-tier-scope.md advertised with NO detector behind it — and worse, the INVERSE of AUTH-no-rate-limit, which matches the `memoryRateLimit` identifier as a limiter hint and CLEARS the login route that uses it (pages/api/auth/login-memory-limited.js). leftover-auth's usesProcessLocalRateLimiter (limiter intent AND a module-scope Map/Set/object store AND no shared-store hint) → review." },
  { id: "P-ROUTE-NOAUTH-GETUSER-ABSENT", kind: "positive", cls: "Route mutation with no session read (getUser-wrapper regression guard)", location: "app/api/profile-noguard/route.ts", match: ["route-noauth"], expectedTier: "review", note: "#562: app/api/profile-noguard/route.ts is the getUser-wrapper negative's paired positive — the same PATCH-mutation shape with the getUser(req) session read removed. Confirms the #562 guard-name broadening (bare getUser/getSession/auth) did not over-suppress a genuinely unguarded route. harvey-route-noauth → review." },
  { id: "P-PUBLIC-BUCKET", kind: "positive", cls: "Public storage bucket created in app/seed code", location: "scripts/seed-public-bucket.mjs", match: ["public-bucket"], expectedTier: "review", note: "#560: scripts/seed-public-bucket.mjs calls admin.storage.createBucket(\"documents\", { public: true }) — a public bucket skips storage RLS for reads, so every object is world-readable by URL (the vandyand teardown #7 miss, KYC/patient docs). Static source-only sibling of the connected-tier live checkPublicBucketsWithNoPolicies. harvey-public-bucket → review." },
  { id: "P-AUTHED-NO-ROLE-CHECK", kind: "positive", cls: "Authenticated admin route with no server-side role check", location: "app/api/admin/revenue/route.ts", match: ["authed-no-role-check"], expectedTier: "review", note: "#561: app/api/admin/revenue/route.ts reads the session (getUser) and 401s anon, but returns org-wide revenue with no role/permission gate — any authenticated member reaches the CFO view (broken function-level authz, OWASP API5). The real shape behind vandyand #5, previously only heuristically flagged as 'unauthenticated' (a false rationale). harvey-authed-no-role-check → review." },
  { id: "P-AUTHED-NO-ROLE-CHECK-JWT", kind: "positive", cls: "Custom-JWT-authenticated admin route with no server-side role check", location: "app/api/admin/users-jwt/route.ts", match: ["authed-no-role-check"], expectedTier: "review", note: "#586: app/api/admin/users-jwt/route.ts authenticates via a CUSTOM HS256 JWT (jwt.verify), not Supabase getUser/getSession, and 401s an invalid token — but returns every user's record with no role/permission gate. The SuperRedHat F-04 shape (app/api/admin/users), MISSED by #561 because its 'authenticated' signal only knew Supabase getUser/getSession; #586 broadened harvey-authed-no-role-check to fire on any auth establishment (jwt.verify method call, or a bare verifyToken/verifySession/requireAuth helper). Regression-paired with the Supabase-getUser P-AUTHED-NO-ROLE-CHECK (revenue), which must still fire. harvey-authed-no-role-check → review." },
  { id: "P-IDOR-APPROUTER", kind: "positive", cls: "IDOR — id from the App Router { params } arg, no ownership predicate", location: "ar-idor/[id]", match: ["idor-param"], expectedTier: "review", note: "#570: app/api/ar-idor/[id]/route.ts reads a note by params.id (the App Router route-handler second-arg) as the sole predicate — .select('*').eq('id', params.id).single(), no owner scope. Before #570 harvey-idor-param's sources were Express-only (req.query/req.params) and its sink didn't tolerate the trailing .single(), so this pure-App-Router IDOR (SuperRedHat F-03) went dark. harvey-idor-param → review." },
  { id: "P-MASS-ASSIGN-APPROUTER", kind: "positive", cls: "Mass assignment — App Router await req.json() body spread into insert", location: "ar-mass/route", match: ["mass-assignment"], expectedTier: "review", note: "#570: app/api/ar-mass/route.ts spreads the App Router body (const body = await req.json()) whole into admin.from('notes').insert({ ...body }). Before #570 harvey-mass-assignment's only source was Express req.body, so the await-req.json() body never connected to the spread sink (SuperRedHat F-07). harvey-mass-assignment → review." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-SERVER-ACTION-GUARDED", kind: "negative", cls: "'use server' mutation guarded by assertPermission", location: "actions-auth.ts", match: ["restore"], note: "restoreDocument() in app/actions-auth.ts calls assertPermission('documents:restore') before mutating. harvey-server-action-noauth's pattern-not-inside excludes it — cleared (match keyword disjoint from the positive sharing this file)." },
  { id: "N-ROUTE-AUTH-CHECKED", kind: "negative", cls: "Route handler mutation guarded by a session read", location: "settings/delete-safe.js", note: "pages/api/settings/delete-safe.js reads getServerSession(req) and 401s before the delete. harvey-route-noauth's pattern-not-inside excludes it — cleared." },
  { id: "N-ROUTE-NOAUTH-CUSTOM-GUARD", kind: "negative", cls: "Route handler mutation guarded by a custom-named helper", location: "permissions/revoke.js", note: "#126: pages/api/permissions/revoke.js calls assertPermission(req, 'permissions:revoke') before deleting — the exact ATC dogfood shape (assertPlatformAdmin/assertPermission/authenticateUser, 122 FPs) the rule couldn't previously see. harvey-route-noauth's broadened pattern-not-regex (assert/require/ensure/authenticate/authorize/guard verb prefix) excludes it — cleared." },
  { id: "N-ROUTE-NOAUTH-ADMIN-AREA", kind: "negative", cls: "Route handler mutation guarded by the assert*Area guard variant", location: "app/api/admin/pricing/route.ts", match: ["route-noauth"], note: "#171: app/api/admin/pricing/route.ts calls assertPlatformAdminArea(req, 'pricing') before updating pricing_plans — the ATC dogfood's 'Area'-suffixed assert variant (#126/#127 broadened the assert-prefix bucket, which already covers this without further changes). harvey-route-noauth's assert-prefix bucket excludes it — cleared." },
  { id: "N-ROUTE-NOAUTH-CONSTANT-TIME", kind: "negative", cls: "Route handler mutation guarded by a constant-time header-secret comparison", location: "app/api/admin/tenants/route.ts", match: ["route-noauth"], note: "#171: app/api/admin/tenants/route.ts checks constantTimeEqual(header, ADMIN_HEADER_SECRET) before inserting a tenant — no assert/require verb and no auth-ish token in the call name, so the pre-#171 regex couldn't see it (~70 ATC admin-route FPs). harvey-route-noauth now recognizes constantTimeEqual/timingSafeEqual as fixed guard names — cleared." },
  { id: "N-ROUTE-NOAUTH-ADMIN-AUDIT", kind: "negative", cls: "Route handler mutation wrapped by a withPlatformAdminAudit(...) guard HOC", location: "app/api/admin/audit/route.ts", match: ["route-noauth"], note: "#171: app/api/admin/audit/route.ts wraps its mutation in withPlatformAdminAudit(req, ...) — the ATC dogfood's audit-wrapper guard (@/lib/db/platform-admin-client). harvey-route-noauth's weak-verb bucket now includes 'with' (paired with an auth-ish token, here 'Admin'), matching the existing jwtVerify/verifyWebhookSignature precedent — cleared." },
  { id: "N-ROUTE-NOAUTH-DELETE-GUARDED", kind: "negative", cls: "App Router DELETE route handler guarded by a session read", location: "app/api/tenant-docs-safe/route.ts", match: ["route-noauth"], note: "#382: app/api/tenant-docs-safe/route.ts reads supabase.auth.getUser() and 401s before the DELETE. harvey-route-noauth's supabase.auth.getUser() pattern-not-inside is declared over the widened verb metavariable, so it suppresses the DELETE match exactly as it always has for POST — cleared. Regression guard: confirms widening the verb set to DELETE didn't drop the session-read suppression." },
  { id: "N-ROUTE-NOAUTH-PUT-GUARDED", kind: "negative", cls: "App Router PUT route handler guarded by a custom-named helper", location: "app/api/tenant-profile-safe/route.ts", match: ["route-noauth"], note: "#382: app/api/tenant-profile-safe/route.ts calls assertPermission(req, 'profiles:update') before the PUT update. harvey-route-noauth's #126 guard-name regex (assert/require/... prefix) is verb-agnostic, so it suppresses the widened PUT match the same way it does for POST — cleared." },
  { id: "N-IDOR-SCOPED", kind: "negative", cls: "By-id query scoped by an owner predicate", location: "order/scoped.js", note: "pages/api/order/scoped.js chains .eq('id', req.query.id).eq('user_id', session.user.id) — the extra .eq() makes the destructured RHS a different (longer) expression tree than harvey-idor-param's exact-shape sink pattern. Cleared." },
  { id: "N-MASS-ASSIGN-PICK", kind: "negative", cls: "Explicit field projection, not a body spread", location: "profile/settings-safe.js", note: "pages/api/profile/settings-safe.js destructures { displayName, bio } = req.body and passes only those named fields to update(). harvey-mass-assignment's sink pattern requires a { ...req.body } spread — cleared." },
  { id: "N-DTO-MAPPED", kind: "negative", cls: "Explicit DTO passed to a Client Component", location: "documents/detail-page-safe.tsx", note: "app/documents/detail-page-safe.tsx passes only two named fields (title, updated_at) to <DocumentCard>, not the raw select('*') row. harvey-server-client-leak's {...$DATA} spread sink does not match a picked object literal — cleared." },
  { id: "N-SERVER-ONLY-PRESENT", kind: "negative", cls: "Secret module guarded by import 'server-only'", location: "lib/secret-safe.js", note: "lib/secret-safe.js reads the same secret but starts with import 'server-only'. harvey-missing-server-only's pattern-not-inside excludes it — cleared." },
  { id: "N-RATE-LIMIT-PRESENT", kind: "negative", cls: "Login route guarded by a rate limiter", location: "auth/login-limited.js", note: "pages/api/auth/login-limited.js calls rateLimit(req) and 429s before signing in. leftover-auth's rate-limiter-hint regex matches the call — cleared." },
  { id: "N-RATE-LIMIT-SHARED-STORE", kind: "negative", cls: "Rate limiter backed by a store shared across instances", location: "lib/rate-limiter.js", match: ["in-memory rate limiter"], note: "#1046: lib/rate-limiter.js counts through `redis.incr(key)` — a store every instance shares, which is the correct serverless shape. usesProcessLocalRateLimiter's shared-store hint clears it, so the in-memory detector stays silent here even though the file is all about rate limiting. (Its own separate defect, failing open on a Redis error, is P-FAIL-OPEN above — matched on a disjoint keyword.)" },
  { id: "N-INMEMORY-CACHE-NOT-LIMITER", kind: "negative", cls: "Module-scope Map used as a memo cache, not a limiter", location: "lib/memo.js", match: ["in-memory rate limiter"], note: "#1046: lib/memo.js has the identical process-local `new Map()` store as the P-INMEMORY-RATE-LIMIT positive, but its CODE reads as memoization — no limiter name, no admission comparison. This is briefs/fp-rules.txt's standing rule ('IN-PROCESS CACHES ARE NOT LIMITERS') given a detector to hold it to, and it is why the check strips comments first: this fixture's own prose says 'not a rate limiter', which a naive content grep reads as limiter intent. Pairs with the pre-existing N-INMEM-CACHE row in base.entries.ts." },
  { id: "N-DEBUG-ROUTE-GUARDED", kind: "negative", cls: "Debug-path route guarded by a session read", location: "debug/status.js", note: "pages/api/debug/status.js sits under a /debug path segment but reads getServerSession(req) and 401s first. leftover-auth's existing sensitive-route AUTH_HINT regex matches getServerSession — cleared (regression guard: confirms the pre-existing P-DEBUG-ENDPOINT heuristic doesn't over-fire on a genuinely guarded debug route)." },
  { id: "N-ROUTE-NOAUTH-GETUSER-WRAPPER", kind: "negative", cls: "Route mutation guarded by a bare getUser() session-read wrapper", location: "app/api/profile-getuser/route.ts", match: ["route-noauth"], note: "#562: app/api/profile-getuser/route.ts reads the session through a plain top-level wrapper — getUser(req) — before mutating (the vandyand app/api/profile/route.ts shape). harvey-route-noauth previously asserted 'no auth-check call anywhere' here because it only recognized the supabase.auth.getUser() METHOD call; #562 added the bare session-accessor names to the guard-name regex — cleared. (The route's real defect is mass assignment, a different rule/M2, not route-noauth.)" },
  { id: "N-PRIVATE-BUCKET", kind: "negative", cls: "Private storage bucket created in app/seed code", location: "scripts/seed-private-bucket.mjs", match: ["public-bucket"], note: "#560: scripts/seed-private-bucket.mjs calls createBucket(\"documents\", { public: false, fileSizeLimit: \"5mb\" }) — a private bucket enforces storage RLS, not a public-exposure defect. harvey-public-bucket's { public: true } pattern does not match public: false — cleared." },
  { id: "N-AUTHED-ROLE-CHECKED", kind: "negative", cls: "Authenticated admin route guarded by a role check", location: "app/api/admin/revenue-guarded/route.ts", match: ["authed-no-role-check"], note: "#561: app/api/admin/revenue-guarded/route.ts reads the caller's role and 403s a non-admin before returning any data. harvey-authed-no-role-check's pattern-not-regex clears any handler referencing a role/authz gate (the .role read, the 403 response) — cleared. Regression guard: confirms the rule fires only on the missing-gate case, not on a properly role-gated privileged route." },
  { id: "N-AUTHED-ROLE-CHECKED-JWT", kind: "negative", cls: "Custom-JWT-authenticated admin route guarded by a role check", location: "app/api/admin/users-jwt-guarded/route.ts", match: ["authed-no-role-check"], note: "#586: app/api/admin/users-jwt-guarded/route.ts verifies the same custom HS256 JWT (jwt.verify) but reads the role claim off the decoded token and 403s a non-admin before returning any data. harvey-authed-no-role-check's pattern-not-regex clears any handler referencing a role/authz gate (the .role read, the 403 response) — cleared. Regression guard: confirms the #586 broadened jwt.verify/verify-helper signal fires only on the missing-gate case, not on a properly role-gated custom-auth route." },
  { id: "N-IDOR-APPROUTER-SCOPED", kind: "negative", cls: "App Router by-id read scoped by an owner predicate", location: "ar-idor-scoped", match: ["idor-param"], note: "#570: app/api/ar-idor-scoped/[id]/route.ts chains .eq('id', params.id).eq('owner_id', user.sub).single() — the scoping .eq() sits between .eq('id', params.id) and .single(), so the RHS is a different (longer) expression tree than harvey-idor-param's exact-shape sink variants. Cleared. Regression guard: confirms the new trailing-.single() sink variants don't over-match a properly scoped App Router query." },
  { id: "N-MASS-ASSIGN-APPROUTER-PICK", kind: "negative", cls: "App Router explicit field projection, not a body spread", location: "ar-mass-safe", match: ["mass-assignment"], note: "#570: app/api/ar-mass-safe/route.ts destructures { title, body } = await req.json() and inserts only those named fields — no { ...body } spread. harvey-mass-assignment's sink requires a spread of the body; a named object literal is a safe shape. Cleared. Regression guard: confirms the new await-req.json() source doesn't over-fire on a picked-field insert." },

  // #568 — leftover-auth sensitive-route AUTH_HINT broadened to the bare session-accessor wrappers.
  { id: "P-SENSITIVE-ROUTE-NOAUTH", kind: "positive", cls: "admin route with no session read of any name", location: "app/api/admin/metrics-open/route.ts", match: ["sensitive-route"], expectedTier: "review", note: "#568: app/api/admin/metrics-open/route.ts is an admin-path route with NO auth-call hint of any kind. leftover-auth's sensitive-route heuristic (AUTH-sensitive-route, taxonomy 'Unauthenticated debug/admin route') → review. Paired positive for N-SENSITIVE-ROUTE-GETUSER: confirms the #568 AUTH_HINT broadening did not over-suppress a genuinely unauthenticated route." },

  // --- NEGATIVE (#568) ---
  { id: "N-SENSITIVE-ROUTE-GETUSER", kind: "negative", cls: "admin route guarded by a bare getUser() wrapper", location: "app/api/admin/metrics-getuser/route.ts", match: ["sensitive-route"], note: "#568: app/api/admin/metrics-getuser/route.ts reads the session through a bare top-level wrapper — getUser(req) — before responding (the vandyand app/api/admin/revenue shape). leftover-auth's sensitive-route heuristic previously labelled this 'Unauthenticated debug/admin route' because AUTH_HINT only knew the dotted supabase.auth.getUser() METHOD call; #568 added the bare session-accessor names (getUser/getSession/getCurrentUser/…) — no AUTH-sensitive-route finding fires here now, cleared. Same false-premise class as #562 (harvey-route-noauth)." },

  // #601 (cipherx CX-13/14) — App Router taint precision: the Next 15/16 awaited-params IDOR source
  // and the bare-variable mass-assignment sink. Both are request-shape variants the App Router taint
  // campaign (#570) did not yet key on.
  { id: "P-IDOR-AWAIT-PARAMS", kind: "positive", cls: "IDOR — id from an awaited params promise (Next 15/16), no ownership predicate", location: "ar-idor-await/[id]", match: ["idor-param"], expectedTier: "review", note: "#601 CX-13: app/api/ar-idor-await/[id]/route.ts reads the id as `const { id } = await params` (Next 15/16 makes params a Promise) then .select('*').eq('id', id).single() with no owner scope. harvey-idor-param's App Router source was `params.id` (property access); #601 added an `await params` source so the awaited-promise destructure taints id. harvey-idor-param → review." },
  { id: "N-IDOR-AWAIT-PARAMS-SCOPED", kind: "negative", cls: "awaited-params by-id read scoped by an owner predicate", location: "ar-idor-await-scoped", match: ["idor-param"], note: "#601: app/api/ar-idor-await-scoped/[id]/route.ts chains .eq('id', id).eq('company_id', user.sub).single() — the scoping .eq() lengthens the sink RHS expression tree, so harvey-idor-param's exact-shape sink doesn't match. Cleared. Regression guard: the new await-params source doesn't over-fire on a properly scoped query." },
  { id: "P-MASS-ASSIGN-BARE", kind: "positive", cls: "Mass assignment — whole parsed body passed bare to update() (no spread)", location: "ar-mass-bare/route", match: ["mass-assignment"], expectedTier: "review", note: "#601 CX-14: app/api/ar-mass-bare/route.ts does `const body = await req.json(); admin.from('profiles').update(body).eq('id', user.id)` — the whole body passed directly, no spread and no allowlist. harvey-mass-assignment required an object SPREAD; the new harvey-mass-assignment-bare unifies $BODY to the identifier declared from await req.json()/req.body, so a bare-variable payload fires while a reconstructed object stays dark. → review." },
  { id: "N-MASS-ASSIGN-BARE-RECONSTRUCTED", kind: "negative", cls: "reconstructed named-field object passed to update() (not the raw body)", location: "ar-mass-bare-safe/route", match: ["mass-assignment"], note: "#601: app/api/ar-mass-bare-safe/route.ts copies two named fields into a NEW object `const upd = { display_name: body.display_name, bio: body.bio }` then update(upd). harvey-mass-assignment-bare binds $BODY to the identifier declared from await req.json(); `upd` has an object-literal RHS, so it never binds $BODY — cleared. Proves the bare sink keys on the raw body variable, not on any variable-argument update()." },

  // #601 (cipherx CX-17, headers.yml) — object-literal reflected-origin CORS. Placed here for locality
  // with the other #601 shapes; the rule lives in headers.yml alongside the imperative reflected rule.
  { id: "P-CORS-REFLECTED-OBJLIT", kind: "positive", cls: "CORS reflects Origin + credentials in an object-literal headers map", location: "ar-cors-reflected/route", match: ["cors-reflected"], expectedTier: "high", note: "#601 CX-17: app/api/ar-cors-reflected/route.ts builds `{ 'Access-Control-Allow-Origin': origin, 'Access-Control-Allow-Credentials': 'true' }` (origin = request.headers.get('origin')) and returns it via new NextResponse(body, { headers }). harvey-cors-reflected-origin-object (taint: request origin -> object field, gated on Allow-Credentials 'true' in the same literal) → high. The object-literal variant the imperative res.headers.set() reflected rule missed." },
  { id: "N-CORS-OBJLIT-REFLECTED-SAFE", kind: "negative", cls: "object-literal CORS map with a hardcoded allowlisted origin + credentials", location: "ar-cors-reflected-safe/route", match: ["cors-reflected"], note: "#601: app/api/ar-cors-reflected-safe/route.ts uses the same object-literal headers map with Allow-Credentials 'true', but Access-Control-Allow-Origin is a hardcoded 'https://app.example.com', not the reflected request Origin. harvey-cors-reflected-origin-object's taint source is the request origin; a constant string is not tainted, so the sink is never reached — cleared." },
];
