// Batch B7 — auth / access-control heuristics (#71, spec §"Batch 7 — Auth / access-control /
// left-open"). Custom Semgrep rules in src/scan/rules/semgrep/auth.yml, plus one extension to
// the existing leftover-auth grep (src/scan/leftover-auth.ts — a sensitive-auth-route +
// no-rate-limiter-hint check) and one reuse of its existing bypassAuth grep. Scheduled
// deliberately LAST in the #71 fan-out: it has the HIGHEST negative-precision risk in the corpus
// (a static tool cannot confirm an ownership/permission/rate-limit check is correct, only that
// the shape is absent), so EVERY entry here is `review` tier — none feed the free count.
// P-DEBUG-ENDPOINT, P-TODO-AUTH (leftover-auth greps, base.entries.ts) and P-SRV-KEY-CLIENT
// (harvey-service-role-in-client, base.yml) already ship — not duplicated here. See
// GROUND-TRUTH.md §B7.

import type { CorpusEntry } from "./types.js";

export const b7AuthEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught, all review tier) ---
  { id: "P-AUTH-BYPASS-CONST", kind: "positive", cls: "Hardcoded bypassAuth gate", location: "reports/export.js", match: ["bypassauth"], expectedTier: "review", note: "const bypassAuth = true; guards an admin.from('reports').select('*') call in pages/api/reports/export.js. leftover-auth's existing bypassAuth grep (src/scan/leftover-auth.ts) → review." },
  { id: "P-SERVER-ACTION-NOAUTH", kind: "positive", cls: "'use server' mutation w/ no authority check", location: "actions-auth.ts", match: ["server-action-noauth"], expectedTier: "review", note: "archiveDocument() in app/actions-auth.ts checks the request Origin but calls no assertPermission/requirePermission/requireRole before supabase.from('documents').update(). harvey-server-action-noauth → review." },
  { id: "P-ROUTE-NOAUTH", kind: "positive", cls: "Route handler mutation w/ no auth guard", location: "settings/delete.js", match: ["route-noauth"], expectedTier: "review", note: "pages/api/settings/delete.js deletes a settings row with no session read/supabase.auth.getUser() call anywhere in the handler. harvey-route-noauth → review." },
  { id: "P-ROUTE-NOAUTH-CUSTOM-VERB", kind: "positive", cls: "Route handler mutation w/ no auth guard (custom-verb regression guard)", location: "permissions/purge.js", match: ["route-noauth"], expectedTier: "review", note: "#126 regression guard: pages/api/permissions/purge.js calls scheduleCleanup() (not a recognized guard verb, no auth-ish token) before deleting, with no session read and no supabase.auth.getUser() call. Confirms the #126 broadened pattern-not-regex didn't over-suppress genuinely unguarded routes. harvey-route-noauth → review." },
  { id: "P-IDOR-PARAM", kind: "positive", cls: "IDOR — id from request, no ownership predicate", location: "order/get.js", match: ["idor-param"], expectedTier: "review", note: "pages/api/order/get.js looks an order up by req.query.id alone — no owner/tenant .eq(). harvey-idor-param (taint: req.query -> exact-shape .eq('id', $ID) sink) → review." },
  { id: "P-MASS-ASSIGNMENT", kind: "positive", cls: "Mass assignment — req.body spread into update", location: "profile/settings.js", match: ["mass-assignment"], expectedTier: "review", note: "pages/api/profile/settings.js spreads the entire req.body into admin.from('profiles').update({ ...req.body }). harvey-mass-assignment (taint: req.body -> insert/update spread sink) → review." },
  { id: "P-SERVER-CLIENT-LEAK", kind: "positive", cls: "Full DB row spread into a Client Component", location: "documents/detail-page.tsx", match: ["server-client-leak"], expectedTier: "review", note: "app/documents/detail-page.tsx destructures a select('*') row and spreads it whole into <DocumentCard {...data} />, a 'use client' component. harvey-server-client-leak → review." },
  { id: "P-MISSING-SERVER-ONLY", kind: "positive", cls: "Secret module missing import 'server-only'", location: "lib/secret.js", match: ["missing-server-only"], expectedTier: "review", note: "lib/secret.js reads process.env.INTERNAL_API_SECRET with no 'import server-only' guard and no 'use client' (the more specific, already-covered case). harvey-missing-server-only → review." },
  { id: "P-NO-RATE-LIMIT", kind: "positive", cls: "Login route w/ no rate limiter", location: "auth/login.js", match: ["rate limit"], expectedTier: "review", note: "pages/api/auth/login.js calls admin.auth.signInWithPassword with no rate-limiter hint anywhere in the file. leftover-auth's new sensitive-auth-route + no-rate-limit-hint check (src/scan/leftover-auth.ts) → review." },
  { id: "P-FAIL-OPEN", kind: "positive", cls: "Rate-limit check fails open on backing-store error", location: "lib/rate-limiter.js", match: ["fail-open"], expectedTier: "review", note: "checkRateLimit() in lib/rate-limiter.js returns true from its catch block when the Redis call throws — an outage becomes an unlimited-request bypass. harvey-fail-open → review." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-SERVER-ACTION-GUARDED", kind: "negative", cls: "'use server' mutation guarded by assertPermission", location: "actions-auth.ts", match: ["restore"], note: "restoreDocument() in app/actions-auth.ts calls assertPermission('documents:restore') before mutating. harvey-server-action-noauth's pattern-not-inside excludes it — cleared (match keyword disjoint from the positive sharing this file)." },
  { id: "N-ROUTE-AUTH-CHECKED", kind: "negative", cls: "Route handler mutation guarded by a session read", location: "settings/delete-safe.js", note: "pages/api/settings/delete-safe.js reads getServerSession(req) and 401s before the delete. harvey-route-noauth's pattern-not-inside excludes it — cleared." },
  { id: "N-ROUTE-NOAUTH-CUSTOM-GUARD", kind: "negative", cls: "Route handler mutation guarded by a custom-named helper", location: "permissions/revoke.js", note: "#126: pages/api/permissions/revoke.js calls assertPermission(req, 'permissions:revoke') before deleting — the exact ATC dogfood shape (assertPlatformAdmin/assertPermission/authenticateUser, 122 FPs) the rule couldn't previously see. harvey-route-noauth's broadened pattern-not-regex (assert/require/ensure/authenticate/authorize/guard verb prefix) excludes it — cleared." },
  { id: "N-IDOR-SCOPED", kind: "negative", cls: "By-id query scoped by an owner predicate", location: "order/scoped.js", note: "pages/api/order/scoped.js chains .eq('id', req.query.id).eq('user_id', session.user.id) — the extra .eq() makes the destructured RHS a different (longer) expression tree than harvey-idor-param's exact-shape sink pattern. Cleared." },
  { id: "N-MASS-ASSIGN-PICK", kind: "negative", cls: "Explicit field projection, not a body spread", location: "profile/settings-safe.js", note: "pages/api/profile/settings-safe.js destructures { displayName, bio } = req.body and passes only those named fields to update(). harvey-mass-assignment's sink pattern requires a { ...req.body } spread — cleared." },
  { id: "N-DTO-MAPPED", kind: "negative", cls: "Explicit DTO passed to a Client Component", location: "documents/detail-page-safe.tsx", note: "app/documents/detail-page-safe.tsx passes only two named fields (title, updated_at) to <DocumentCard>, not the raw select('*') row. harvey-server-client-leak's {...$DATA} spread sink does not match a picked object literal — cleared." },
  { id: "N-SERVER-ONLY-PRESENT", kind: "negative", cls: "Secret module guarded by import 'server-only'", location: "lib/secret-safe.js", note: "lib/secret-safe.js reads the same secret but starts with import 'server-only'. harvey-missing-server-only's pattern-not-inside excludes it — cleared." },
  { id: "N-RATE-LIMIT-PRESENT", kind: "negative", cls: "Login route guarded by a rate limiter", location: "auth/login-limited.js", note: "pages/api/auth/login-limited.js calls rateLimit(req) and 429s before signing in. leftover-auth's rate-limiter-hint regex matches the call — cleared." },
  { id: "N-DEBUG-ROUTE-GUARDED", kind: "negative", cls: "Debug-path route guarded by a session read", location: "debug/status.js", note: "pages/api/debug/status.js sits under a /debug path segment but reads getServerSession(req) and 401s first. leftover-auth's existing sensitive-route AUTH_HINT regex matches getServerSession — cleared (regression guard: confirms the pre-existing P-DEBUG-ENDPOINT heuristic doesn't over-fire on a genuinely guarded debug route)." },
];
