// Batch B8 (#71) — Supabase live-tier config (spec `docs/design/spec-71-security-corpus.md`
// §"Batch 10 — Supabase project config"). No `module` field: these are M1 entries, not a separate
// cross-module tool.
//
// VENUES, split 2026-07-28 by #1428. Every row here used to be `expectedTier: "connected"`, which
// scoreEntry() scored N/A unconditionally — so the whole batch was scored by nothing and could not
// fail. `pnpm validate:connected` now scores them against a real stack, and they do not all need the
// same one, which the single "connected" label hid:
//   local  — a Postgres connection to a `supabase start` stack answers it (the Splinter lints, the
//            storage-bucket query, the installed-extension list). Nine of the fourteen rows.
//   hosted — needs the Management API's auth config (GET /v1/projects/{ref}/config/auth) and
//            therefore a real hosted project plus a PAT. The four auth rows, and only those: HIBP
//            protection has no local CLI field at all, and the other three are read from the API
//            response rather than by parsing config.toml, so a local stack cannot answer them
//            either. They report NOT SCORED until a run declares that venue (#1098).
// The first live run of this batch also corrected two answer keys and recorded one measured gap —
// see P-PGNET-SSRF, N-DEFINER-SCOPED and P-SENSITIVE-COLS below. All three had been green-by-N/A
// since #71.
//
// Detection code for all seven advisor lints already exists and is generic — parseAdvisorFindings
// (src/scan/supabase-advisors.ts) maps ANY lint name through CURATED_SEVERITY, which already
// carries rls_disabled_in_public, rls_enabled_no_policy, auth_users_exposed, security_definer_view,
// function_search_path_mutable, rls_references_user_metadata, and sensitive_columns_exposed — so
// this batch adds fixtures + calibration rows + recorded-JSON parsing tests (supabase-advisors.
// test.ts), not new detection code. Storage/auth-config/extension checks (checkPublicBuckets
// WithNoPolicies, checkAuthConfig, checkDangerousExtensions in supabase-config.ts) were already
// wired for a prior batch and are reused unchanged here. Fixtures live in
// targets/calibration/supabase/migrations/20260709000004_b8_connected_advisors.sql and
// targets/calibration/supabase/config.toml. See GROUND-TRUTH.md §"Batch B8" — live advisor
// confirmation against a running project is a deferred main-session pass (this PR is offline-only:
// parsing-logic unit tests + the static gate no-regression check).

import type { CorpusEntry } from "./types.js";

export const b8SupaEntries: CorpusEntry[] = [
  // --- POSITIVES (live tiers — scored by `pnpm validate:connected`, never by a static run) ---
  { id: "P-RLS-ENABLED-NO-POLICY", kind: "positive", cls: "RLS enabled, zero policies (tenant-facing table)", location: "reports", match: ["rls_enabled_no_policy"], expectedTier: "local", note: "public.reports (migrations/20260709000004) gets RLS enabled but no policy is ever created — unlike service_state (N-RLS-DENY-ALL), reports is meant to be tenant-readable, so this is a genuine 'forgot to finish RLS' signal. Splinter rls_enabled_no_policy, curated to Medium in CURATED_SEVERITY." },
  { id: "P-AUTH-USERS-EXPOSED", kind: "positive", cls: "auth.users exposed via a public view", location: "user_directory", match: ["auth_users_exposed"], expectedTier: "local", note: "public.user_directory selects id/email/created_at from auth.users and grants select to anon/authenticated. Splinter auth_users_exposed, curated to Critical." },
  { id: "P-SECDEF-VIEW", kind: "positive", cls: "SECURITY DEFINER view", location: "tenant_totals", match: ["security_definer_view"], expectedTier: "local", note: "public.tenant_totals aggregates invoices with no security_invoker=true option, so it runs as the owning role and bypasses the invoices RLS policies for whoever reads it. Splinter security_definer_view, curated to High." },
  { id: "P-FN-SEARCH-PATH", kind: "positive", cls: "Mutable search_path on a function", location: "get_invoice_total", match: ["function_search_path_mutable"], expectedTier: "local", note: "public.get_invoice_total has no `set search_path`, unlike public.current_tenant_id() (the N-DEFINER-SCOPED negative, which sets it). Splinter function_search_path_mutable, curated to Medium." },
  { id: "P-RLS-USER-META", kind: "positive", cls: "RLS policy trusts user_metadata", location: "internal_notes", match: ["rls_references_user_metadata"], expectedTier: "local", note: "internal_notes_admin_read policy checks (auth.jwt() -> 'user_metadata' ->> 'is_admin') — a claim any authenticated user can set on themselves via the client SDK. Splinter rls_references_user_metadata, curated to High." },
  { id: "P-SENSITIVE-COLS", kind: "positive", cls: "Sensitive column exposed via API", location: "support_tickets", match: ["ssn"], expectedTier: "none", gapKind: "measured-gap", note: "support_tickets.customer_ssn is a known-sensitive column name pattern reachable via PostgREST for any tenant member — the column itself, not the row set, is the exposure. Splinter sensitive_columns_exposed, curated to High. MEASURED GAP, found 2026-07-28 by #1428 on the first live run this row has ever had: the lint does NOT fire, because its own SQL (src/scan/rules/splinter.sql) requires the table to be exposed via the API *without RLS*, and support_tickets has RLS enabled — so the fixture as planted can never satisfy it. Re-checked against the whole live schema: the five public tables with RLS off (audit_logs, billing_exports, coupon_redemptions, export_audit, mt_invoices) carry no sensitive-pattern column, so nothing in this target reaches the lint. Recorded `none`/measured-gap rather than left as a connected-tier N/A, so the static gate fails loud if a rule ever DOES reach the class; the fixture work is #1492." },
  { id: "P-STORAGE-PUBLIC", kind: "positive", cls: "Public storage bucket, zero object policies", location: "avatars", match: ["public bucket with no policies"], expectedTier: "local", note: "[storage.buckets.avatars] public=true in config.toml; no storage.objects policy scoped to it anywhere in supabase/migrations/. checkPublicBucketsWithNoPolicies (supabase-config.ts), already wired — high-precision once run against the live bucket/policy query." },
  { id: "P-LEAKED-PW-OFF", kind: "positive", cls: "Leaked-password (HIBP) protection disabled", location: "Auth config", match: ["hibp", "leaked-password"], expectedTier: "hosted", note: "Not representable in supabase/config.toml — HIBP protection is a hosted-project Auth setting with no local CLI field, so this positive has no local fixture; it can only be confirmed via a GET /v1/projects/{ref}/config/auth read. checkAuthConfig(password_hibp_enabled: false) is wired and unit-tested (supabase-config.test.ts); the field NAME is confirmed against the captured response schema (src/scan/__fixtures__/supabase/, 2026-07-26), but no live project has been read — #1098." },
  { id: "P-EMAIL-CONFIRM-OFF", kind: "positive", cls: "Email confirmation disabled", location: "config.toml", match: ["enable_confirmations", "email confirmation"], expectedTier: "hosted", note: "[auth.email] enable_confirmations = false in config.toml — the local-CLI equivalent of the hosted mailer_autoconfirm=true Auth setting checkAuthConfig flags. Read from the Management API config, not by parsing config.toml directly; mailer_autoconfirm is confirmed against the captured response schema (src/scan/__fixtures__/supabase/, 2026-07-26), not against a live project — #1098." },
  { id: "P-OTP-LONG-EXPIRY", kind: "positive", cls: "OTP expiry far past baseline", location: "Auth config", match: ["mailer_otp_exp", "sms_otp_exp", "otp expiry"], expectedTier: "hosted", note: "[auth.email] otp_expiry = 86400 (24h) in config.toml, vs. checkAuthConfig's 3600s (1h) baseline. The hosted API spells it mailer_otp_exp (email) / sms_otp_exp (SMS) — see src/scan/__fixtures__/supabase/. NOT yet confirmed against a live project: #1098 found the check reading the config.toml spelling, so it could never have fired on one." },
  { id: "P-OAUTH-REDIRECT-WILD", kind: "positive", cls: "Wildcard OAuth/redirect allowlist", location: "config.toml", match: ["redirect_urls", "redirect allowlist", "wildcard"], expectedTier: "hosted", note: "[auth] additional_redirect_urls includes a bare \"*\" in config.toml. checkAuthConfig(uri_allow_list.includes('*')) is already wired and unit-tested; read from the Management API config, whose uri_allow_list field is confirmed against the captured response schema (src/scan/__fixtures__/supabase/, 2026-07-26) — no live project read yet, #1098." },
  { id: "P-PGNET-SSRF", kind: "positive", cls: "Dangerous extension (pg_net) with a callable RPC", location: "extension: pg_net", match: ["dangerous extension"], expectedTier: "local", note: "pg_net is enabled and public.fetch_webhook_preview (SECURITY DEFINER) calls net.http_get(p_url) with a caller-supplied URL, granted to authenticated — a DB-originated SSRF primitive, not just a dormant extension. checkDangerousExtensions (supabase-config.ts) flags the extension; already wired. ANSWER KEY CORRECTED 2026-07-28 by #1428, the first time this row was ever scored: it named the RPC (`fetch_webhook_preview`) as its location, but checkDangerousExtensions locates its finding at `extension: pg_net (schema extensions)`, so the row could only ever have MISSED. It scored N/A instead, which is why four months of that went unnoticed. Matched on the taxonomy (\"Dangerous extension enabled\") rather than \"pg_net\", which is a substring of the corrected location and would be vacuous under #1355. What the row now asserts is narrower than its class sentence — the extension is flagged, the RPC that makes it reachable is not; the SECURITY DEFINER half is separately caught by Splinter's anon/authenticated_security_definer_function_executable lints on the same function." },

  // --- NEGATIVES (live tier — must NOT be flagged in the free count of a live run) ---
  { id: "N-DEFINER-SCOPED", kind: "negative", cls: "SECURITY DEFINER function with search_path set + auth.uid() check", location: "current_tenant_id", match: ["function_search_path_mutable"], expectedTier: "local", note: "public.current_tenant_id() (schema migration) is SECURITY DEFINER but sets search_path = public and scopes its query by auth.uid() — the correct pattern. Splinter function_search_path_mutable does not fire; contrasts P-FN-SEARCH-PATH. SCOPED 2026-07-28 by #1428, the first time this row was ever scored: with no `match` key it claimed the function draws NO free-count finding at all, and a live run shows it draws two — Splinter's anon_security_definer_function_executable (High) and authenticated_security_definer_function_executable (Medium), because the fixture grants execute on it to anon. Those are a different lint answering a different question, and the note above only ever claimed the search_path one. The key narrows the row to the claim it documents; whether the FIXTURE should grant this helper to anon at all is a separate question, filed as #1493." },
  { id: "N-STORAGE-PRIVATE", kind: "negative", cls: "Private storage bucket", location: "invoices-private", expectedTier: "local", note: "[storage.buckets.invoices-private] public=false in config.toml. checkPublicBucketsWithNoPolicies filters on public=true first — cleared regardless of policy count; contrasts P-STORAGE-PUBLIC." },
];
