// Batch B9 — secrets & config-secret breadth (#71, spec docs/design/corpus-roadmap-to-100.md §3a).
// Extends the existing secret scanners (no new scanner): custom gitleaks rules in
// src/scan/rules/gitleaks-supabase.toml and three structural Semgrep rules in
// src/scan/rules/semgrep/secrets.yml. Tiering per the locked preamble: only ~100%-precision
// detections are `high` (free count) — a dedicated-format prefix / published-constant / structural
// sink whose match alone is proof. Provider-key patterns that only live verification would confirm
// (the fake AIza key, the committed storage JWT) stay `review`, as does the secret-in-URL heuristic.
// See GROUND-TRUTH.md §B9. All planted secrets are FAKE and non-functional.

import type { CorpusEntry } from "./types.js";

export const b9SecretsEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-NEXTCONFIG-ENV-SECRET", kind: "positive", cls: "Secret inlined to client via next.config env", location: "next.config.js", match: ["harvey-nextconfig-env-secret"], expectedTier: "high", note: "SUPABASE_SERVICE_ROLE_KEY mapped through next.config `env:{}` is inlined into the browser bundle. Semgrep harvey-nextconfig-env-secret (secret-named key whose value is a process.env read, scoped inside an env block) → high. Match on the rule id to isolate it from the B5 missing-header findings sharing this file." },
  { id: "P-SB-DEFAULT-JWT-SECRET", kind: "positive", cls: "Unrotated self-hosted Supabase default JWT secret", location: "docker.env", match: ["supabase-default-jwt-secret", "default jwt"], expectedTier: "high", note: "The published self-hosted default JWT secret committed unrotated in supabase/docker.env — every anon/service_role JWT is forgeable by anyone. gitleaks custom supabase-default-jwt-secret matches the exact well-known string → high (nothing else matches it)." },
  { id: "P-NPM-TOKEN-COMMITTED", kind: "positive", cls: "npm _authToken committed in .npmrc", location: ".npmrc", match: ["npm-access-token", "npm_"], expectedTier: "high", note: "An npm automation token (npm_ + 36) committed in .npmrc grants publish/read on private packages. gitleaks default npm-access-token, promoted to high in secrets.ts (the npm_ format is a dedicated token namespace). Value FAKE." },
  { id: "P-GCP-SA-JSON", kind: "positive", cls: "Google service-account JSON committed", location: "gcp-service-account.json", match: ["private-key", "private key"], expectedTier: "high", note: "A committed GCP service-account key file (type:service_account with a private_key block). gitleaks private-key fires on the -----BEGIN PRIVATE KEY----- body → high (already in the high set). The FAKE key body is inert. The .json.example placeholder (no PEM block) is the negative." },
  { id: "P-SLACK-WEBHOOK-URL", kind: "positive", cls: "Slack webhook URL committed", location: "notify.js", match: ["slack-webhook-url", "slack"], expectedTier: "high", note: "A hooks.slack.com/workflows/… URL committed in lib/notify.js — anyone with it can trigger the workflow. gitleaks default slack-webhook-url (matches any services/workflows/triggers path), promoted to high in secrets.ts. FAKE, and on the /workflows/ path (not /services/) so it's inert to GitHub push protection's incoming-webhook pattern." },
  { id: "P-URI-CREDS-NONPG", kind: "positive", cls: "Non-DB service URI with inline password", location: "mailer.js", match: ["harvey-uri-credentials", "smtp"], expectedTier: "high", note: "smtp://mailer:<pw>@host in lib/mailer.js. gitleaks custom harvey-uri-credentials covers the non-database schemes (smtp/ftp/http), complementing harvey-db-uri-credentials; loopback hosts and ${env} interpolation are excluded → high. Password FAKE." },
  { id: "P-EDGEFN-SECRET", kind: "positive", cls: "Hardcoded secret fallback in a Supabase Edge Function", location: "send-email/index.ts", match: ["harvey-edgefn-secret-fallback"], expectedTier: "high", note: "Deno.env.get('RESEND_API_KEY') ?? 're_…' in an Edge Function ships the literal in the deployed bundle/history. Semgrep harvey-edgefn-secret-fallback matches the string-literal ?? / || fallback → high. The fail-closed (throw) variant in send-email-safe is the negative. Key value FAKE." },
  { id: "P-DB-WEBHOOK-SECRET-SQL", kind: "positive", cls: "Outbound DB-webhook bearer literal in committed SQL", location: "b9_db_webhook.sql", match: ["harvey-http-authorization-bearer", "bearer"], expectedTier: "high", note: "A net.http_post trigger with a hardcoded Authorization Bearer token in a committed migration. gitleaks custom harvey-http-authorization-bearer matches the 24+ char literal after Bearer → high; the current_setting() variant (no literal) is the negative. Token FAKE." },
  { id: "P-GCP-API-KEY", kind: "positive", cls: "Google API key (AIza) committed", location: "maps.js", match: ["harvey-gcp-api-key", "aiza", "google api"], expectedTier: "review", note: "An AIza-prefixed Google API key literal in lib/maps.js. gitleaks custom harvey-gcp-api-key (the default ruleset ships no working AIza rule in this version) → review (a fake can't be verified and AIza keys are over-reported by docs). The process.env variant is the negative." },
  { id: "P-SECRET-IN-URL", kind: "positive", cls: "API key passed as a URL query parameter", location: "weather.js", match: ["harvey-secret-in-url-param"], expectedTier: "review", note: "fetch(`…?api_key=${KEY}`) in lib/weather.js. Semgrep harvey-secret-in-url-param matches the secret-bearing query param → review (a query param isn't always sensitive). The Authorization-header variant is the negative." },
  { id: "P-SIGNED-URL-TOKEN-SRC", kind: "positive", cls: "Storage signed-URL token committed in source", location: "share.js", match: ["jwt"], expectedTier: "review", note: "A Supabase Storage signed URL committed with its live ?token=eyJ… JWT in lib/share.js. gitleaks default jwt → review (an eyJ token, unverifiable and possibly expired). The token payload decodes to a benign storage claim, NOT service_role, so the high supabase-service-role-jwt rule stays silent. The <SIGNED_URL_TOKEN> placeholder is the negative." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-NEXTCONFIG-ENV-BENIGN", kind: "negative", cls: "Non-secret build constant in next.config env", location: "next.config.js", match: ["app_version"], note: "APP_VERSION in the same next.config env block is a non-secret build constant, safe to inline. harvey-nextconfig-env-secret's key-name regex doesn't match it — no finding carries `app_version`, so it clears (the B5 missing-header highs on this file don't carry it either)." },
  { id: "N-SB-JWT-ROTATED", kind: "negative", cls: "Rotated random JWT secret (not the default)", location: "docker.env", match: ["anon_jwt_secret"], note: "A rotated, random JWT secret is the correct state — it is NOT the published default string, so supabase-default-jwt-secret stays silent. A high-entropy literal draws only a generic-api-key review hit (triaged out), never a free-count finding." },
  { id: "N-NPM-TOKEN-ENV", kind: "negative", cls: "npm _authToken from an env var", location: ".npmrc", match: ["${npm_token}", "npm_token"], note: "//registry/:_authToken=${NPM_TOKEN} sources the token from the environment — no literal, so npm-access-token matches nothing on the line. Cleared." },
  { id: "N-GCP-SA-EXAMPLE", kind: "negative", cls: "Service-account JSON template (placeholder)", location: "gcp-service-account.json.example", note: "The .json.example template has <YOUR_PRIVATE_KEY> in place of the PEM block — no -----BEGIN PRIVATE KEY----- for gitleaks private-key to match. The type:service_account shape draws only a LOW-confidence semgrep hit (review, triaged out), never the high private-key finding. Cleared, and distinct from the real .json positive by its .example location." },
  { id: "N-SLACK-WEBHOOK-PLACEHOLDER", kind: "negative", cls: "Slack webhook documentation placeholder", location: "notify.js", match: ["webhook_token"], note: "hooks.slack.com/services/<TEAM_ID>/<CHANNEL_ID>/<WEBHOOK_TOKEN> is an angle-bracketed placeholder; slack-webhook-url needs a real 24-char token segment, so it doesn't match. No finding carries `webhook_token`. Cleared." },
  { id: "N-URI-CREDS-ENV", kind: "negative", cls: "Non-DB URI with env-interpolated password", location: "mailer.js", match: ["smtp_password"], note: "smtp://mailer:${SMTP_PASSWORD}@host has no literal credential; harvey-uri-credentials's password class excludes ${ } so it doesn't match. Cleared." },
  { id: "N-EDGEFN-SECRET-THROWS", kind: "negative", cls: "Edge Function that fails closed on missing secret", location: "send-email-safe/index.ts", note: "The safe function reads Deno.env.get and throws when absent — no string-literal fallback, so harvey-edgefn-secret-fallback (which requires a `?? \"literal\"`) doesn't match. Cleared." },
  { id: "N-DB-WEBHOOK-SECRET-SETTING", kind: "negative", cls: "DB-webhook bearer from a runtime setting", location: "b9_db_webhook.sql", match: ["current_setting"], note: "The shipped-order webhook builds its Authorization header from current_setting('app.webhook_secret') — no committed literal after Bearer, so harvey-http-authorization-bearer (24-char literal required) doesn't match. No finding carries `current_setting`. Cleared." },
  { id: "N-GCP-KEY-ENV", kind: "negative", cls: "Google API key read from the environment", location: "maps.js", match: ["google_maps_api_key"], note: "process.env.GOOGLE_MAPS_API_KEY has no AIza literal in source, so harvey-gcp-api-key matches nothing here. No finding carries `google_maps_api_key`. Cleared." },
  { id: "N-SECRET-IN-HEADER", kind: "negative", cls: "Secret sent in an Authorization header", location: "weather.js", match: ["getforecastsafe"], note: "getForecastSafe sends the key in an Authorization header with no secret-bearing query param, so harvey-secret-in-url-param's URL regex doesn't match it. No finding carries `getforecastsafe`. Cleared (harvey-secret-in-url-param is review-tier regardless, never free-count)." },
  { id: "N-SIGNED-URL-PLACEHOLDER", kind: "negative", cls: "Signed-URL documentation placeholder", location: "share.js", match: ["signed_url_token"], note: "…/sign/…?token=<SIGNED_URL_TOKEN> is an angle-bracketed placeholder, not a JWT — the jwt rule doesn't match. No finding carries `signed_url_token`. Cleared." },
  { id: "N-BCRYPT-HASH-SEED", kind: "negative", cls: "bcrypt password hash in seed/migration data", location: "seed.sql", match: ["$2b$", "bcrypt", "password_hash"], note: "A precomputed bcrypt digest ($2b$…) in seed data is a one-way hash of a throwaway local-dev password, not a committed secret — a free-count FP guard. gitleaks matches nothing, and semgrep's detected-bcrypt-hash fires only at LOW confidence → review, triaged out of the free count, never high. Cleared." },
];
