// Base corpus batch — the original 17 positives + 15 negatives (issues #61/#52/#9). Moved
// verbatim from calibration.ts; see GROUND-TRUTH.md for the fixtures they score.

import type { CorpusEntry } from "./types.js";

export const baseEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-SQLI-CONCAT", kind: "positive", cls: "SQL injection (string interpolation)", location: "search.js", match: ["sql"], expectedTier: "high", note: "Untrusted q interpolated into a template-literal SQL string on the service pool (#4)." },
  { id: "P-OPEN-REDIRECT", kind: "positive", cls: "Open redirect", location: "redirect.js", match: ["redirect"], expectedTier: "review", note: "req.query URL reaches res.redirect with no host allowlist (#8); review tier (MED conf)." },
  { id: "P-RLS-DISABLED", kind: "positive", cls: "Public table, RLS off", location: "audit_logs", expectedTier: "connected", note: "audit_logs never gets ENABLE RLS (#3). Supabase Advisor / config auditor, connected tier — validated in the 2026-07-08 live run (SB-EXPOSED), not re-run in this static build." },
  { id: "P-SRV-KEY-CLIENT", kind: "positive", cls: "Service-role key in Client Component", location: "AdminPanel", match: ["service-role", "service_role", "SUPABASE_SERVICE_ROLE"], expectedTier: "high", note: "'use client' module references SUPABASE_SERVICE_ROLE_KEY — ships to the browser bundle." },
  { id: "P-NEXTPUBLIC-SECRET", kind: "positive", cls: "Secret mis-prefixed NEXT_PUBLIC_", location: ".env.local", match: ["stripe", "next_public", "secret"], expectedTier: "review", note: "NEXT_PUBLIC_STRIPE_SECRET_KEY=sk_live_... inlined into the client bundle; gitleaks (review — unverified/publishable-key ambiguity keeps it out of the count)." },
  { id: "P-HARDCODED-KEY", kind: "positive", cls: "Hardcoded provider secret", location: "ai.js", match: ["anthropic", "credential", "api-key"], expectedTier: "review", note: "sk-ant-api03-... in source (fake, valid-shape). gitleaks provider pattern (review — TruffleHog can't verify a dead key)." },
  { id: "P-NEXT-CVE-29927", kind: "positive", cls: "Framework CVE — middleware auth bypass", location: "next", manifest: "package.json", match: ["29927"], expectedTier: "high", note: "next@^14.2.5 is < 14.2.25, in the CVE-2025-29927 range (GHSA-f82v-jwr5-mffw)." },
  { id: "P-DEP-CVE", kind: "positive", cls: "Known-vulnerable dependency", location: "lodash", match: ["lodash"], expectedTier: "review", note: "lodash@4.17.11 (prototype-pollution CVE). OSV-Scanner needs a committed lockfile — the calibration target ships none, so this is a no-op in a lockfile-less run (tracked as a follow-up)." },
  { id: "P-XSS-DSIH", kind: "positive", cls: "XSS via tainted dangerouslySetInnerHTML", location: "post.js", match: ["inner"], expectedTier: "high", note: "router.query.body flows unsanitized into __html." },
  { id: "P-CORS-WILDCARD", kind: "positive", cls: "Permissive CORS w/ credentials", location: "data.js", match: ["cors", "origin"], expectedTier: "high", note: "Access-Control-Allow-Origin '*' + Allow-Credentials true." },
  { id: "P-CORS-WILDCARD-OBJLIT", kind: "positive", cls: "Permissive CORS declared in an object-literal headers map", location: "ar-cors.ts", match: ["permissive-cors"], expectedTier: "high", note: "#570: lib/ar-cors.ts declares the wildcard Access-Control-Allow-Origin in an object-literal headers map (const CORS_HEADERS = { 'Access-Control-Allow-Origin': '*', ... }) — the App Router idiom spread into NextResponse.json(body, { headers }). Before #570 harvey-permissive-cors only matched res.setHeader/headers.set('...','*'), so this (SuperRedHat F-10) went dark; #570 added the object-literal wildcard shape. harvey-permissive-cors → high (free count)." },
  { id: "P-NO-CSP", kind: "positive", cls: "Missing security headers / CSP", location: "next.config", match: ["csp", "security-policy", "security headers"], expectedTier: "review", note: "next.config.js defines no CSP and no middleware sets one." },
  { id: "P-SSRF-FETCH", kind: "positive", cls: "SSRF via server-fetched user URL", location: "fetch-preview.js", match: ["ssrf"], expectedTier: "review", note: "fetch(req.query.url) with no host allow/deny; review (needs deploy-network context)." },
  { id: "P-SSRF-APPROUTER", kind: "positive", cls: "SSRF — App Router searchParams URL into a cross-file fetch wrapper", location: "ar-ssrf/route", match: ["ssrf"], expectedTier: "review", note: "#570: app/api/ar-ssrf/route.ts reads new URL(req.url).searchParams.get('url') and passes it to a shared fetchRemote() wrapper (the raw fetch() lives cross-file in lib/ar-fetch.ts). Before #570 harvey-ssrf-fetch missed the App Router searchParams source, and OSS Semgrep's single-file taint can't span the source-in-route/sink-in-helper split, so this (SuperRedHat F-05) went dark; #570 added the searchParams source and keyed the sink on the fetch-wrapper call name. harvey-ssrf-fetch → review." },
  { id: "P-SLOPSQUAT", kind: "positive", cls: "Slopsquatted / hallucinated dep", location: "react-supabase-helpers", match: ["react-supabase-helpers"], expectedTier: "review", note: "Nonexistent package in deps. Needs an npm-registry existence cross-check (not yet built) — the offline typosquat corpus only catches edit-distance-1 names, so this is a documented miss/follow-up." },
  { id: "P-POSTINSTALL", kind: "positive", cls: "Lifecycle-script supply-chain risk", location: "package.json (scripts)", match: ["lifecycle"], expectedTier: "review", note: "postinstall lifecycle script present; review (presence != malicious)." },
  { id: "P-DEBUG-ENDPOINT", kind: "positive", cls: "Debug/seed/admin route w/ no auth", location: "seed.js", match: ["debug", "seed", "route", "auth"], expectedTier: "review", note: "pages/api/dev/seed.js has no auth guard; leftover-auth sensitive-route heuristic (review). pages/api/admin/reset.js (isAdmin=true) is also flagged." },
  { id: "P-TODO-AUTH", kind: "positive", cls: "Placeholder/left-open auth", location: "create.js", match: ["todo"], expectedTier: "review", note: "// TODO: auth above an unguarded mutation; leftover-auth grep (review)." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-ANON-KEY", kind: "negative", cls: "Public anon key looks like a secret", location: ".env.local", match: ["anon"], note: "NEXT_PUBLIC_SUPABASE_ANON_KEY (role:anon) is public by design. gitleaks allowlist (regexTarget=line) suppresses every rule on that line. The single most credibility-fatal FP." },
  { id: "N-ENV-EXAMPLE", kind: "negative", cls: "Placeholder secrets in a sample file", location: ".env.example", note: "Documented placeholders; .env.example path-allowlisted and unverifiable." },
  { id: "N-SECRET-NAME", kind: "negative", cls: "Variable named like a secret, holds none", location: "ResetForm", note: "passwordLabel / awaitingPasswordReset — name-only, no secret value (vs Sonar S2068)." },
  { id: "N-PARAM-QUERY", kind: "negative", cls: "Parameterized query looks like SQLi", location: "list.js", note: "pool.query('... $1', [req.x]) — bound param, not interpolation. SQLi rule must not fire." },
  { id: "N-DSIH-SANITIZED", kind: "negative", cls: "Sanitized/constant dangerouslySetInnerHTML", location: "about.js", note: "sanitizeHtml(...) and a constant literal. The custom rule clears both; a registry .audit rule may flag it at review tier only (triaged out)." },
  { id: "N-OBJ-INJECTION", kind: "negative", cls: "Benign obj[key] bracket access", location: "i18n.js", note: "translations[locale] with locale validated against an enum (vs eslint detect-object-injection)." },
  { id: "N-JSX-KEY", kind: "negative", cls: "Composite/stable JSX key", location: "List.jsx", note: "key={`${it.id}-${i}`} — quality rule, never in the security count (vs Sonar S6479)." },
  { id: "N-WEAK-HASH-CACHE", kind: "negative", cls: "Non-security md5 as cache key", location: "cache.js", note: "md5 as an ETag/cache tag, not auth/integrity (vs Sonar S4790)." },
  { id: "N-REDOS-SAFE", kind: "negative", cls: "Safe (linear) regex looks like ReDoS", location: "validate.js", note: "Linear email regex with negated classes; ReDoS stays out of the count (vs Sonar S5852)." },
  { id: "N-FS-STATIC", kind: "negative", cls: "Static/unrelated fs/.open() call", location: "read-config.js", note: "fs.readFileSync(path.join(__dirname,...)) + an unrelated widget.open() (vs eslint fs rules)." },
  { id: "N-DEV-DEP", kind: "negative", cls: "Vulnerable dep in devDependencies only", location: "webpack", note: "webpack@4.42.0 is dev-only. Excluded from the count; OSV/npm audit would list it at review/informational (needs a lockfile), never high." },
  { id: "N-SERVICE-ROLE-SERVER", kind: "negative", cls: "Legit server-only service-role use", location: "cron.js", note: "import 'server-only' + admin client, no 'use client' — service-role use is not a finding by itself (fp-rules)." },
  { id: "N-RLS-DENY-ALL", kind: "negative", cls: "RLS-enabled-no-policy, service-only table", location: "service_state", note: "RLS on + zero policies = deny-all by design. Advisor lint 0008 is informational, not a finding (connected tier)." },
  { id: "N-URL-ENV", kind: "negative", cls: "Operator/env config URL", location: "redis.js", note: "z.string().url() on process.env.REDIS_URL (redis://) — operator/env URLs are exempt (fp-rules)." },
  { id: "N-INMEM-CACHE", kind: "negative", cls: "Map used as cache, not limiter", location: "memo.js", note: "module-level Map for memoization, not a rate limiter (fp-rules)." },
  { id: "N-SSRF-APPROUTER-FIXED", kind: "negative", cls: "App Router fetch wrapper called with a fixed URL", location: "ar-ssrf-safe", match: ["ssrf"], note: "#570: app/api/ar-ssrf-safe/route.ts calls the fetchRemote() wrapper with a fixed non-request URL — no request-tainted value reaches the sink, so harvey-ssrf-fetch's taint never connects. Cleared. Regression guard: confirms the new searchParams/await-req.json() sources and the wrapper-call sink don't fire without a tainted source." },
  { id: "N-CORS-OBJLIT-ALLOWLIST", kind: "negative", cls: "Object-literal CORS headers with an allowlisted origin", location: "ar-cors-safe", match: ["permissive-cors"], note: "#570: lib/ar-cors-safe.ts declares the same object-literal headers map but sets Access-Control-Allow-Origin to a specific origin, not '*'. harvey-permissive-cors's object-literal shape requires the '*' literal value — cleared. Regression guard: confirms the new object-literal wildcard pattern (free count) doesn't fire on an allowlisted origin." },

  // #625 — over-broad WebExtension manifest permissions (checkWebExtensionManifest, src/scan/webext-
  // manifest.ts). A manifest.json with a broad host pattern + a sensitive capability (cookies/webRequest/
  // tabs/…) can read session cookies on every site the user visits. The ATC apps/extension client instance.
  { id: "P-WEBEXT-OVERBROAD", kind: "positive", cls: "WebExtension manifest: broad host access + cookies", location: "apps/extension/manifest.json", match: ["webext-overbroad"], expectedTier: "review", note: "#625: apps/extension/manifest.json (v3) declares host_permissions [\"https://*/*\"] + \"cookies\" — session/auth-cookie read across every site the user visits, not just the origin it needs (the ATC apps/extension instance). checkWebExtensionManifest flags a broad host pattern (<all_urls>/*://*/*/https://*/*) combined with a sensitive capability → review (High severity, intent-dependent)." },
  { id: "N-WEBEXT-SCOPED-HOST", kind: "negative", cls: "WebExtension with cookies but a single-origin host", location: "apps/extension-safe/manifest.json", match: ["webext-overbroad"], note: "#625: apps/extension-safe/manifest.json requests \"cookies\" but scopes host_permissions to https://app.example.com/* — a narrow, specific origin, not a broad pattern. checkWebExtensionManifest requires a BROAD host to fire — cleared. Proves the rule keys on the broad-host + capability COMBINATION, not on cookies alone." },
  { id: "N-WEBEXT-NO-SENSITIVE-CAP", kind: "negative", cls: "WebExtension with a broad host but no sensitive capability", location: "apps/extension-nocap/manifest.json", match: ["webext-overbroad"], note: "#625: apps/extension-nocap/manifest.json declares host_permissions [\"https://*/*\"] but only \"storage\" — no cookies/webRequest/tabs/history. checkWebExtensionManifest requires a sensitive capability alongside the broad host — cleared. Proves the broad host alone is not flagged." },

  // #611 Gap A — service_role key hardcoded as a JWT literal and passed to createClient
  // (harvey-service-role-literal). The nocode-rescue residual: harvey-vite-service-role-in-client
  // only caught import.meta.env.VITE_*SERVICE_ROLE*; this catches the inline/named-const literal.
  { id: "P-SRV-ROLE-LITERAL-CLIENT", kind: "positive", cls: "service_role key hardcoded as a JWT literal into a browser client", location: "nocodeServiceClient", match: ["service-role-literal"], expectedTier: "high", note: "#611 Gap A: src/lib/nocodeServiceClient.ts hardcodes the service_role JWT as a literal in a service-role-named const and passes it to createClient(import.meta.env.VITE_SUPABASE_URL, SUPABASE_SERVICE_ROLE) — the nocode-rescue before/src/lib/supabaseClient.ts shape. harvey-vite-service-role-in-client (#565) only matched import.meta.env.VITE_*SERVICE_ROLE*, so a literal key went dark; harvey-service-role-literal keys the createClient call on a $JWT literal carrying a service_role base64 signature (const-propagation resolves the named identifier). → high (free count, Critical)." },
  { id: "N-ANON-LITERAL-CLIENT", kind: "negative", cls: "anon/publishable key hardcoded as a literal (public by design)", location: "nocodeAnonClient", match: ["service-role-literal"], note: "#611 Gap A: src/lib/nocodeAnonClient.ts uses the identical inline-literal createClient shape but with the anon key (role:anon), which is meant to be public and shipped to the browser. harvey-service-role-literal requires the service_role token signature — the anon literal is not flagged. The single most important precision guard: the rule keys on the ROLE, not on 'a JWT literal in createClient'. (gitleaks separately flags the JWT as a review-tier 'possible committed credential' — orthogonal, not free-count.)" },
  { id: "N-SRV-ROLE-ENV-CLIENT", kind: "negative", cls: "legit server admin client reading service_role from process.env", location: "serverAdminEnvClient", match: ["service-role-literal"], note: "#611 Gap A: src/lib/serverAdminEnvClient.ts builds the admin client from process.env.SUPABASE_SERVICE_ROLE_KEY (not a literal). harvey-service-role-literal only matches a string-literal key, so the correct env-sourced usage stays dark — the literal-vs-env discriminator that separates a leaked key from a correct one." },
  { id: "N-SRV-ROLE-DEMO-CLIENT", kind: "negative", cls: "public supabase-start local-dev demo service_role key", location: "localDevClient", match: ["service-role-literal"], note: "#611 Gap A: src/lib/localDevClient.ts inlines the well-known local-dev demo service_role key (iss:\"supabase-demo\") against a localhost URL. It IS a service_role token but is public by design; harvey-service-role-literal excludes the supabase-demo base64 signature so a committed local key does not free-count (gitleaks' supabase-demo-key-marker correlation clears its own decoded-claim hit on the same line)." },

  // #614 — plain-Express (req,res) mechanical coverage: permissive CORS via the cors() lib config,
  // and a client-supplied privilege flag used as an authorization gate.
  { id: "P-CORS-EXPRESS-CREDS", kind: "positive", cls: "Express cors() with wildcard origin + credentials", location: "express-cors.js", match: ["permissive-cors"], expectedTier: "high", note: "#614: lib/express-cors.js configures the Express cors middleware as cors({ origin: \"*\", credentials: true }) — the lib reflects the origin, so any site reads authenticated responses cross-origin. harvey-permissive-cors's #614 branch requires BOTH the wildcard origin and credentials:true in the same object literal. → high (free count)." },
  { id: "N-CORS-EXPRESS-ALLOWLIST", kind: "negative", cls: "Express cors() with an allowlisted origin + credentials", location: "express-cors-safe", match: ["permissive-cors"], note: "#614: lib/express-cors-safe.js allows credentials but sets origin to an explicit allowlist array, not \"*\". The #614 cors() branch requires the wildcard origin — cleared. Regression guard that it keys on the wildcard, not on credentials." },
  { id: "N-CORS-EXPRESS-NOCREDS", kind: "negative", cls: "Express cors() wildcard origin with no credentials", location: "express-cors-nocreds", match: ["permissive-cors"], note: "#614: lib/express-cors-nocreds.js is cors({ origin: \"*\" }) with no credentials — the common intended public-API shape. The #614 branch requires credentials:true alongside the wildcard, so this stays dark (severity depends on credentials being allowed)." },
  { id: "P-CLIENT-TRUSTED-ROLE", kind: "positive", cls: "client-supplied privilege flag used as an authz gate", location: "express-role.js", match: ["client-trusted-role"], expectedTier: "review", note: "#614: lib/express-role.js gates an admin grant on req.body.isAdmin — the client names its own privilege level. harvey-client-trusted-role fires on a privilege-flag field read whose root is an HTTP request (req/request). Review tier: reading such a field usually IS the bug, but a read-then-reject shape can't be told apart single-file, so it is surfaced for triage rather than free-counted." },
  { id: "N-SESSION-DERIVED-ROLE", kind: "negative", cls: "role decision taken from the verified session", location: "express-role-safe", match: ["client-trusted-role"], note: "#614: lib/express-role-safe.js takes the admin decision from session.user.role, not the request. harvey-client-trusted-role gates its source root on req/request, so a session-derived role never matches — cleared." },
  { id: "N-BENIGN-BODY-FIELD", kind: "negative", cls: "ordinary non-privilege request body fields", location: "express-role-benign", match: ["client-trusted-role"], note: "#614: lib/express-role-benign.js reads req.body.title / req.body.content — ordinary fields. harvey-client-trusted-role only matches privilege-flag field names (isAdmin/is_admin/role/superuser/…), so benign body reads stay dark." },
];
