import type { CorpusEntry } from "./types.js";

export const m5ExceptionTypeEntries: CorpusEntry[] = [
  {
    module: "M5",
    id: "M5EXC-P-EMPTY",
    kind: "positive",
    cls: "empty catch body silently discards a failure",
    location: "m5-exception-flow/unsafe.ts",
    match: ["empty catch"],
    expectedTier: "review",
    note: "emptyCatch has an AST-empty catch with no ignored-error rationale; detectM5ExceptionFlowFindings emits M5 — Empty catch at review tier.",
  },
  {
    module: "M5",
    id: "M5EXC-P-LOG-FALLTHROUGH",
    kind: "positive",
    cls: "logger helper and console call followed by unsafe continuation",
    location: "m5-exception-flow/unsafe.ts",
    match: ["log-only catch"],
    expectedTier: "review",
    note: "logAndContinue only prepares a message and logs through logError/console.warn before returning ready after the catch; it has no recovery, typed failure, or termination.",
  },
  {
    module: "M5",
    id: "M5EXC-P-AMBIGUOUS-SUCCESS",
    kind: "positive",
    cls: "caught failure is converted to an ambiguous null success",
    location: "m5-exception-flow/unsafe.ts",
    match: ["ambiguous exception success"],
    expectedTier: "review",
    note: "failureLooksLikeSuccess returns null from its catch; the caller cannot distinguish a failed load from an intentional empty result.",
  },
  {
    module: "M5",
    id: "M5EXC-P-NESTED",
    kind: "positive",
    cls: "empty nested catch remains independently visible",
    location: "m5-exception-flow/nested-unsafe.ts",
    match: ["empty catch"],
    expectedTier: "review",
    note: "nestedCatch compensates in the outer catch but contains a separate empty inner catch; the AST walk reports the inner catch without misclassifying the outer block.",
  },
  {
    module: "M5",
    id: "M5EXC-N-SAFE-CONTROLS",
    kind: "negative",
    cls: "rationale, cleanup, telemetry, rethrow, failure result, compensation, and termination controls",
    location: "m5-exception-flow/safe-controls.ts",
    note: "The paired controls cover rationale-bearing ignored cleanup/telemetry, direct and wrapped rethrows, {ok:false,error}, rollback, process termination, cleanup-only handling, and nested safe catches; none should emit M5 exception-flow findings.",
  },
  {
    module: "M1",
    id: "M1EXC-P-AUTH-BOUNDARY",
    kind: "positive",
    cls: "empty catch at an authentication boundary",
    location: "m5-exception-flow/auth/session.ts",
    match: ["auth/security boundary"],
    expectedTier: "review",
    note: "requireSession emits one M1 auth/security-boundary finding and is excluded from the generic M5 export, preventing double delivery.",
  },
  {
    module: "M1",
    id: "M1EXC-P-BILLING-BOUNDARY",
    kind: "positive",
    cls: "log-only catch at a payment boundary",
    location: "m5-exception-flow/billing/charge.ts",
    match: ["billing/payment boundary"],
    expectedTier: "review",
    note: "collectPayment emits one M1 billing/payment-boundary finding and is excluded from the generic M5 export, preventing double delivery.",
  },
  {
    module: "M1",
    id: "M1EXC-P-REQUEST-BOUNDARY",
    kind: "positive",
    cls: "ambiguous-success return at a request boundary",
    location: "m5-exception-flow/app/api/orders/route.ts",
    match: ["request boundary"],
    expectedTier: "review",
    note: "POST emits one M1 request-boundary finding and is excluded from the generic M5 export, preventing double delivery.",
  },
  {
    module: "M5",
    id: "M5TYPE-P-AS-ANY",
    kind: "positive",
    cls: "production expression asserted as any without rationale",
    location: "m5-type-escape/unsafe.ts",
    match: ["type escape (`as any`)"],
    expectedTier: "review",
    note: "uncheckedAny forces an unknown value through as any with no runtime validation or interop rationale.",
  },
  {
    module: "M5",
    id: "M5TYPE-P-DOUBLE",
    kind: "positive",
    cls: "unknown is double-asserted into an unrelated target type",
    location: "m5-type-escape/unsafe.ts",
    match: ["type escape (double assertion)"],
    expectedTier: "review",
    note: "uncheckedAccount uses raw as unknown as Account; collapsedChain proves a longer nested assertion still produces one finding at the outer expression.",
  },
  {
    module: "M5",
    id: "M5TYPE-P-TS-IGNORE",
    kind: "positive",
    cls: "unexplained @ts-ignore in production source",
    location: "m5-type-escape/unsafe.ts",
    match: ["unexplained @ts-ignore"],
    expectedTier: "review",
    note: "silentlySuppressed has a bare @ts-ignore; evidence includes the suppressed source line and the missing approved --/:/em-dash rationale.",
  },
  {
    module: "M5",
    id: "M5TYPE-N-SAFE-CONTROLS",
    kind: "negative",
    cls: "validated schema, prior assertion, interop rationale, and suppression controls",
    location: "m5-type-escape/safe-controls.ts",
    note: "The controls cover schema.parse plus a validation rationale, an assertPayload narrowing boundary, a concrete third-party interop reason, @ts-expect-error, and @ts-ignore with the approved inline reason convention.",
  },
];
