// Static RLS-policy semantics (#220) — the source-tier path to the class the 2026-07-12 public
// sweep proved matters most. Both real Criticals in that sweep lived in `create policy` statements
// in committed migration .sql, findable with no DB connection, yet our semantic reviewer
// (rls-policy-review.ts) ran connected-tier only and the sole static check looked for a missing
// ENABLE RLS. checkMigrationPolicySemantics (src/scan/supabase-static.ts, wired into
// runMechanicalScan) closes that gap: parsePolicies (src/migration-sql-parse.ts) extracts the
// USING / WITH CHECK bodies and the EXISTING reviewer judges them — one rule set, two feeds
// (live pg_policies and migration text).
//
// Every entry is expectedTier "review" BY DESIGN, not as a hedge: static text shows a policy's
// SHAPE but never its behavior against real data, so these surface as free-tier INDICATORS (#227)
// — loud, located, never counted in the grade. The connected-tier entries for the same classes
// (base.entries.ts P-RLS-DISABLED, b16 P-STORAGE-*) are unaffected and still N/A statically.
//
// Tenancy is inferred PER TABLE (a table declaring tenant_id is per-tenant; one without it is
// per-user), because a real app mixes both shapes and judging all tables against one model
// reproduces the #206 FP — that inference is what clears the storage own-folder policies below.

import type { CorpusEntry } from "./types.js";

export const rlsStaticSemanticsEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-RLS-AUTH-ROLE-STATIC", kind: "positive", cls: "policy checks logged-in, not which tenant (read statically from migrations)", location: "20260708000002_rls.sql", match: ["invoices_select_authenticated"], expectedTier: "review", note: "create policy invoices_select_authenticated on public.invoices for select using (auth.role() = 'authenticated') — GROUND-TRUTH bug #2, previously invisible to the source tier. public.invoices declares tenant_id, so it reviews per-tenant: the policy references a caller-identity function but never the tenant key, so any authenticated user reads every tenant's invoices. Static counterpart of the connected-tier semantic pass (RLS-AUTH-ROLE)." },
  { id: "P-STORAGE-AUTH-NOT-OWNER-STATIC", kind: "positive", cls: "storage.objects read policy checks auth, not ownership (static)", location: "20260710000001_b15_storage_secdef_semantic.sql", match: ["user_files_select_authenticated"], expectedTier: "review", note: "create policy user_files_select_authenticated on storage.objects for select using (bucket_id = 'user-files' and auth.role() = 'authenticated') — every signed-in user reaches every tenant's files. storage.objects is never declared in the app's migrations, so it reviews per-user: the policy references the caller but binds no row value to auth.uid(). The b16 entry of the same name documents this as an LLM/vuln-scan class; #220 now also reaches it mechanically at review tier — both may fire, neither is free-count." },

  { id: "P-STORAGE-UPLOAD-CHECK-TRUE-STATIC", kind: "positive", cls: "storage.objects INSERT policy WITH CHECK (true) (static)", location: "20260710000001_b15_storage_secdef_semantic.sql", match: ["user_files_insert_open"], expectedTier: "review", note: "create policy user_files_insert_open on storage.objects for insert with check (true) — any caller writes any path in any bucket. The #256 tail of #220: every earlier rule keyed off USING, and an INSERT policy has none (Postgres REJECTS USING on INSERT: 'only WITH CHECK expression allowed'), so this fell through clean in both modes. Now caught by the shared reviewer, so the connected tier inherits it. The b16 entry of the same name documents the LLM/vuln-scan path and is no longer a static miss." },

  { id: "P-RLS-USING-TRUE-STATIC", kind: "positive", cls: "SELECT policy USING (true) publishes every row of a tenant-scoped table", location: "20260708000002_rls.sql", match: ["documents_select_all"], expectedTier: "review", note: "create policy documents_select_all on public.documents for select using (true) — GROUND-TRUTH row 1 (Critical), and until now uncaught by every mechanical rule: checkMigrationRlsStatic passes it because documents DOES enable RLS (the absence-check is correct), and checkTrueReview handled only the WRITE side (`WITH CHECK (true)`, #256), bailing on reads at its first line. usingTrueReview is the read-side mirror: public.documents declares tenant_id, so it reviews per-tenant, and a USING of `true` puts every tenant's rows in scope for anyone holding the anon key. Review tier, not free-count: `USING (true)` is unambiguous about its EFFECT but not its INTENT — see the N-RLS-PUBLIC-CATALOG negative for the shape that must stay cleared." },

  { id: "P-RLS-TAUTOLOGY-STATIC", kind: "positive", cls: "always-true RLS policy disguised as a (col IS NOT NULL OR col IS NULL) tautology (#616)", location: "20260719000001_rls_tautology.sql", match: ["articles_update_tautology"], expectedTier: "review", note: "#616: create policy articles_update_tautology on public.tautology_articles for update using (author_id is not null or author_id is null) — logically `true` (a column is always one or the other) but never textually `true`, so the pre-#616 CLAUSE_TRUE (/^\\s*\\(*\\s*true\\s*\\)*\\s*$/) never matched. rls-policy-review.ts now collapses the col-null tautology to `true`; tautology_articles declares tenant_id (per-tenant), so usingTrueReview fires — any caller can UPDATE any tenant's article. SupatestVibeDemo/VulnBlog F1/F2/F9-writes, moved back to the mechanical tier. Review tier (static shows shape, not behavior)." },
  { id: "N-RLS-SINGLE-NOTNULL", kind: "negative", cls: "genuine single IS NOT NULL predicate — not a tautology (#616 discriminator)", location: "20260719000001_rls_tautology.sql", match: ["articles_select_notnull"], note: "#616: create policy articles_select_notnull on public.tautology_articles for select using (author_id is not null) — a real predicate (a column CAN be null), not an always-true tautology. The collapse keys on the col-null PAIR (`X IS NOT NULL OR X IS NULL`), so a lone `IS NOT NULL` is left untouched and the policy stays dark. Paired with P-RLS-TAUTOLOGY-STATIC to prove the normalizer doesn't over-collapse. N-RLS-TAUTOLOGY-SCOPED (articles_select_scoped, tenant_id = current_tenant_id()) in the same file is the correctly-scoped control." },
  { id: "P-RLS-FK-TENANT-SCOPE", kind: "positive", cls: "bare (non-_id) tenant column named via its foreign key to a tenant table (#301)", location: "supabase/migrations/", match: ["widgets (declares site)"], expectedTier: "review", note: "create table public.widgets (… site uuid not null references public.tenants(id) …) with a per-user policy — `site` is off the tenant-key list and has no _id suffix, so the #258 scan never named it and the per-user misclassification was invisible (#301). The FK to public.tenants is the precision-preserving signal: unrecognisedScopeColumns now surfaces `site` in SB-RLS-TENANCY-MODEL's NOT RECOGNISED list. Review tier — a disclosure of the review's assumption, never a free-count defect. Paired with N-RLS-FK-NON-TENANT, the same shape whose FK points at a non-tenant table and must stay unnamed." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-RLS-FK-NON-TENANT", kind: "negative", cls: "bare FK column to a NON-tenant lookup table — an ordinary relation (#301 non-flood)", location: "supabase/migrations/", match: ["gadgets"], note: "create table public.gadgets (… city uuid not null references public.cities(id) …) — byte-for-byte the same shape as the widgets plant (a bare uuid FK column on a per-user table), but `city` foreign-keys to public.cities, a plain lookup table, not a tenancy root. Naming `city` would be the false-positive flood that kept #301 open — nearly any schema has FK columns, and only the tenant-shaped FK target separates a scope column from an ordinary relation. At the GATE level this entry pins only that no HIGH-tier finding fires on gadgets (SB-RLS-TENANCY-MODEL is review-tier, so it can never fail a negative here); the precise non-flood claim — that gadgets/city stays OFF the NOT RECOGNISED list while widgets/site lands ON it — is proven by the paired unit tests in supabase-static.test.ts (#301)." },
  { id: "N-RLS-PUBLIC-CATALOG-USING-TRUE", kind: "negative", cls: "USING (true) on an intentionally world-readable reference table", location: "20260715000001_rls_using_true_negatives.sql", match: ["plans_select_public"], note: "create policy plans_select_public on public.plans for select using (true) — byte-for-byte the same clause as the documents_select_all plant, and correct: a published price list the pricing page renders to logged-out visitors. The discriminator is the SCHEMA, not the policy text: public.plans declares no tenant column, so it reviews per-user and usingTrueReview does not fire; public.documents declares tenant_id, so `every row readable` contradicts the table's own declaration. This entry is the point of the rule's narrow scope — flagging every `USING (true)` would make the catalog and the leak indistinguishable and train users to ignore the class outright (docs/fp-rules.txt: a scanner that flags these wastes the client's trust)." },
  { id: "N-RLS-TENANT-SCOPED-READ", kind: "negative", cls: "correctly tenant-scoped SELECT policy on a tenant table", location: "20260715000001_rls_using_true_negatives.sql", match: ["reports_select_own_tenant"], note: "create policy reports_select_own_tenant on public.reports for select using (tenant_id = public.current_tenant_id()) — the correct shape a tenant-scoped READ takes: same table shape and same `for select` as the documents plant, but the USING constrains rows instead of admitting all of them. Pins that usingTrueReview keys off the CLAUSE, not the command — a rule matching `for select` on a tenant table would flag this and every correct read policy in the corpus." },
  { id: "N-RLS-TENANT-SCOPED-STATIC", kind: "negative", cls: "correctly tenant-scoped policy, both USING and WITH CHECK", location: "20260708000002_rls.sql", match: ["notes_rw_own_tenant"], note: "create policy notes_rw_own_tenant on public.notes for all using (tenant_id = public.current_tenant_id()) with check (tenant_id = public.current_tenant_id()) — both clauses constrain by the tenant key, so reviewPolicy clears it outright. This is the shape a CORRECT policy takes: flagging it would make every indicator noise, which is the failure mode #227 exists to prevent. Same for counters_rw_own_tenant in the same file." },
  { id: "N-STORAGE-OWNERSHIP-SCOPED-STATIC", kind: "negative", cls: "storage read/insert policies scoped to the caller's own folder", location: "20260710000001_b15_storage_secdef_semantic.sql", match: ["user_files_select_own", "user_files_insert_own"], note: "create policy user_files_select_own … using (bucket_id = 'user-files' and (storage.foldername(name))[1] = auth.uid()::text) — the standard Supabase one-folder-per-user ownership pattern, and its insert sibling. Cleared by per-table inference (storage.objects declares no tenant column → per-user mode) plus OWNER_BINDING now recognising an EXPRESSION bound to auth.uid(), not just a bare column. Both were false positives on the first #220 run against this target." },
  { id: "N-RLS-OWNROW-WITH-TENANTID", kind: "negative", cls: "own-row policy (id = auth.uid()) on a table that also declares tenant_id (the profiles shape)", location: "20260708000002_rls.sql", match: ["profiles_select_self"], note: "create policy profiles_select_self on public.profiles for select using (id = auth.uid()) — public.profiles DECLARES tenant_id, so inferTenancyModel reviews it per-tenant and the caller-identity rule fires (references auth.uid(), not tenant_id). This is the #257 residual FP: profiles is genuinely owner-scoped by its identity and only carries tenant_id for joins, but that is NOT statically separable from a tenant table wrongly keyed on the user — the #206 wrong-column bug the same rule must keep catching (rls-policy-review.test.ts pins auth.uid() = created_by on a tenant table SHOULD flag). PR #244 tried to narrow the rule and broke four #206 tests; the honest resolution is to keep the shape at REVIEW tier — surfaced and triaged out of the count, never a free-count FP. This entry pins exactly that: a review-tier hit is tolerated, a high-tier one is not." },
];
