// Static RLS-policy semantics (#220) — the source-tier path to the class the 2026-07-12 public
// sweep proved matters most. Both real Criticals in that sweep lived in `create policy` statements
// in committed migration .sql, findable with no DB connection, yet our semantic reviewer
// (rls-policy-review.ts) ran connected-tier only and the sole static check looked for a missing
// ENABLE RLS. checkMigrationPolicySemantics (src/scan/supabase-static.ts, wired into
// runMechanicalScan) closes that gap: parsePolicies (src/migration-sql-parse.ts) extracts the
// USING / WITH CHECK bodies and the EXISTING reviewer judges them — one rule set, two feeds
// (live pg_policies and migration text).
//
// Every entry is expectedTier "review" BY DESIGN, not as a hedge: static text shows a policy's
// SHAPE but never its behavior against real data, so these surface as free-tier INDICATORS (#227)
// — loud, located, never counted in the grade. The connected-tier entries for the same classes
// (base.entries.ts P-RLS-DISABLED, b16 P-STORAGE-*) are unaffected and still N/A statically.
//
// Tenancy is inferred PER TABLE (a table declaring tenant_id is per-tenant; one without it is
// per-user), because a real app mixes both shapes and judging all tables against one model
// reproduces the #206 FP — that inference is what clears the storage own-folder policies below.

import type { CorpusEntry } from "./types.js";

export const rlsStaticSemanticsEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-RLS-AUTH-ROLE-STATIC", kind: "positive", cls: "policy checks logged-in, not which tenant (read statically from migrations)", location: "20260708000002_rls.sql", match: ["invoices_select_authenticated"], expectedTier: "review", note: "create policy invoices_select_authenticated on public.invoices for select using (auth.role() = 'authenticated') — GROUND-TRUTH bug #2, previously invisible to the source tier. public.invoices declares tenant_id, so it reviews per-tenant: the policy references a caller-identity function but never the tenant key, so any authenticated user reads every tenant's invoices. Static counterpart of the connected-tier semantic pass (RLS-AUTH-ROLE)." },
  { id: "P-STORAGE-AUTH-NOT-OWNER-STATIC", kind: "positive", cls: "storage.objects read policy checks auth, not ownership (static)", location: "20260710000001_b15_storage_secdef_semantic.sql", match: ["user_files_select_authenticated"], expectedTier: "review", note: "create policy user_files_select_authenticated on storage.objects for select using (bucket_id = 'user-files' and auth.role() = 'authenticated') — every signed-in user reaches every tenant's files. storage.objects is never declared in the app's migrations, so it reviews per-user: the policy references the caller but binds no row value to auth.uid(). The b16 entry of the same name documents this as an LLM/vuln-scan class; #220 now also reaches it mechanically at review tier — both may fire, neither is free-count." },

  { id: "P-STORAGE-UPLOAD-CHECK-TRUE-STATIC", kind: "positive", cls: "storage.objects INSERT policy WITH CHECK (true) (static)", location: "20260710000001_b15_storage_secdef_semantic.sql", match: ["user_files_insert_open"], expectedTier: "review", note: "create policy user_files_insert_open on storage.objects for insert with check (true) — any caller writes any path in any bucket. The #256 tail of #220: every earlier rule keyed off USING, and an INSERT policy has none (Postgres REJECTS USING on INSERT: 'only WITH CHECK expression allowed'), so this fell through clean in both modes. Now caught by the shared reviewer, so the connected tier inherits it. The b16 entry of the same name documents the LLM/vuln-scan path and is no longer a static miss." },

  { id: "P-RLS-USING-TRUE-STATIC", kind: "positive", cls: "SELECT policy USING (true) publishes every row of a tenant-scoped table", location: "20260708000002_rls.sql", match: ["documents_select_all"], expectedTier: "review", note: "create policy documents_select_all on public.documents for select using (true) — GROUND-TRUTH row 1 (Critical), and until now uncaught by every mechanical rule: checkMigrationRlsStatic passes it because documents DOES enable RLS (the absence-check is correct), and checkTrueReview handled only the WRITE side (`WITH CHECK (true)`, #256), bailing on reads at its first line. usingTrueReview is the read-side mirror: public.documents declares tenant_id, so it reviews per-tenant, and a USING of `true` puts every tenant's rows in scope for anyone holding the anon key. Review tier, not free-count: `USING (true)` is unambiguous about its EFFECT but not its INTENT — see the N-RLS-PUBLIC-CATALOG negative for the shape that must stay cleared." },

  { id: "P-RLS-USING-TRUE-REGULATED", kind: "positive", cls: "SELECT policy USING (true) on a table holding regulated data — the M10 escalation control", location: "20260726000001_regulated_overbroad_policy.sql", match: ["patient_billing_select_all"], expectedTier: "review", note: "#1060: create policy patient_billing_select_all on public.patient_billing for select using (true) — detection-wise the same class as P-RLS-USING-TRUE-STATIC, and that is the point: what is NEW is the TABLE. public.patient_billing carries member_ssn (US_SSN/SENSITIVE_PII) + card_number (CARD/PCI) = data score 10 → Critical, so this is the corpus's first planted M1 finding that names a High/Critical M10 table. Before it, escalateFindingsByDataClass matched 7 findings on the committed dry-run artifacts and RAISED NONE — every table a finding named scored Low, so the product's headline path (a tenant-isolation gap on regulated data is priced higher) had no end-to-end control while every unit test stayed green. The escalation itself (High → Critical, dataClass.escalatedFrom) is asserted against the committed artifacts in src/data-class-escalation.test.ts; this entry is the detection half — if usingTrueReview stops firing here the escalation assertion has nothing to escalate." },

  { id: "P-RLS-TAUTOLOGY-STATIC", kind: "positive", cls: "always-true RLS policy disguised as a (col IS NOT NULL OR col IS NULL) tautology (#616)", location: "20260719000001_rls_tautology.sql", match: ["articles_update_tautology"], expectedTier: "review", note: "#616: create policy articles_update_tautology on public.tautology_articles for update using (author_id is not null or author_id is null) — logically `true` (a column is always one or the other) but never textually `true`, so the pre-#616 CLAUSE_TRUE (/^\\s*\\(*\\s*true\\s*\\)*\\s*$/) never matched. rls-policy-review.ts now collapses the col-null tautology to `true`; tautology_articles declares tenant_id (per-tenant), so usingTrueReview fires — any caller can UPDATE any tenant's article. SupatestVibeDemo/VulnBlog F1/F2/F9-writes, moved back to the mechanical tier. Review tier (static shows shape, not behavior)." },
  { id: "N-RLS-SINGLE-NOTNULL", kind: "negative", cls: "genuine single IS NOT NULL predicate — not a tautology (#616 discriminator)", location: "20260719000001_rls_tautology.sql", match: ["articles_select_notnull"], note: "#616: create policy articles_select_notnull on public.tautology_articles for select using (author_id is not null) — a real predicate (a column CAN be null), not an always-true tautology. The collapse keys on the col-null PAIR (`X IS NOT NULL OR X IS NULL`), so a lone `IS NOT NULL` is left untouched and the policy stays dark. Paired with P-RLS-TAUTOLOGY-STATIC to prove the normalizer doesn't over-collapse. N-RLS-TAUTOLOGY-SCOPED (articles_select_scoped, tenant_id = current_tenant_id()) in the same file is the correctly-scoped control." },
  { id: "P-RLS-FK-TENANT-SCOPE", kind: "positive", cls: "bare (non-_id) tenant column named via its foreign key to a tenant table (#301)", location: "supabase/migrations/", match: ["widgets (declares site)"], expectedTier: "review", note: "create table public.widgets (… site uuid not null references public.tenants(id) …) with a per-user policy — `site` is off the tenant-key list and has no _id suffix, so the #258 scan never named it and the per-user misclassification was invisible (#301). The FK to public.tenants is the precision-preserving signal: unrecognisedScopeColumns now surfaces `site` in SB-RLS-TENANCY-MODEL's NOT RECOGNISED list. Review tier — a disclosure of the review's assumption, never a free-count defect. Paired with N-RLS-FK-NON-TENANT, the same shape whose FK points at a non-tenant table and must stay unnamed." },

  { id: "P-RLS-USING-TRUE-PII-SPARED", kind: "positive", cls: "SPARED USING(true) SELECT upgraded to a finding because M10 classified the table as PII (#1183)", location: "20260727000002_using_true_pii.sql", match: ["m10-classified pii"], expectedTier: "review", expectedSeverity: "High", note: "#1183 (supatest F9): create policy newsletter_subscribers_select_all on public.newsletter_subscribers for select using (true), on a table with NO tenant column and an `email` column. Detection-wise this is the shape the reviewer deliberately SPARES — a table with no recognised tenant key gets only the SB-RLS-USING-TRUE-UNASSESSED disclosure, because a world-readable catalog and a per-user leak are the same text. What changes it is a SECOND module: M10 classifies the same migration SQL and returns EMAIL at high confidence, so the open question is already answered. The upgrade fires only on a column M10 is confident about or one in a regulated category (SENSITIVE_PII/PHI/PCI/SECRET) — see N-RLS-USING-TRUE-AMBIGUOUS-NAME for why 'the table is in the data map' would have been the wrong gate. An upgraded table is removed from the unassessed disclosure: it was assessed." },

  { id: "P-RLS-CMDGAP-WRITE-NO-READ", kind: "positive", cls: "RLS policy set grants the client a write command and no SELECT policy (#1370 permission matrix)", location: "20260731000001_rls_write_without_read.sql", match: ["no policy for select"], expectedTier: "review", note: "#1370: public.device_pings grants INSERT, UPDATE and DELETE to authenticated, each correctly scoped to tenant_id = public.current_tenant_id(), and NO select policy — so the client writes rows it has no policy to read back. The predicates are deliberately CORRECT: a plant with a leaky predicate would be caught by usingTrueReview and would prove nothing about this rule, which judges the SHAPE OF THE SET. Paired with N-RLS-CMDGAP-READONLY-SYNC, the mirror shape (read policed, writes server-side) that must stay silent — that pairing is the whole rule, because the first version of SB-RLS-CMDGAP (then a single rollup row) reported ANY empty cell and failed mvp-boilerplate's #227 don't-cry-wolf control on five sound tables (corpus-drift run 30634899914)." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-RLS-CMDGAP-READONLY-SYNC", kind: "negative", cls: "read policed, every write server-side — the Stripe-sync shape the first #1370 rule cried wolf on", location: "20260731000002_rls_stripe_sync_readonly.sql", reviewTierHits: ["auth_rls_initplan (static)"], note: "#1370: four tables re-expressing devtodollars/mvp-boilerplate@2aac5c2f's billing schema — billing_products/billing_prices (`for select using (true)`, a public catalogue), billing_subscriptions (own-row read), billing_profiles (own-row read AND update, insert by a signup trigger). Every one leaves INSERT/UPDATE/DELETE partly or wholly uncovered, and every one is CORRECT: an uncovered command is denied outright, so the client cannot write these tables, and the webhook that does write them holds the service-role key. MEASURED 2026-07-31 against a fresh clone of that pin, the pre-narrowing rule reported all five of its equivalents and turned mvp-boilerplate's `mustRaiseLoudIndicator: false` expectation red. The recorded review-tier hit is auth_rls_initplan, which is a genuine M7 observation about `auth.uid()` per row and is faithful to the upstream schema — no SB-RLS-CMDGAP-<table> row must appear here at any tier, and because a #1344 review-tier hit fails a negative unless it is listed, this entry fails the moment the rule widens back." },
  { id: "N-RLS-USING-TRUE-AMBIGUOUS-NAME", kind: "negative", cls: "USING (true) on a catalog whose only classifiable column is a low-confidence NAME? (#1183 precision boundary)", location: "20260727000002_using_true_pii.sql", match: ["support_categories"], note: "#1183: create policy support_categories_select_all on public.support_categories for select using (true) — same clause, same absent tenant key, and the table IS in M10's data map: `name` classifies NAME? at LOW confidence. That is exactly what a public catalog's product name looks like, and MEASURED 2026-07-27 against targets/calibration it is also what plans.name, cities.name, notes.body and documents.body look like — so an 'appears in the data map' gate would have upgraded the very case the spare exists to protect (N-RLS-PUBLIC-CATALOG-USING-TRUE). This entry pins the discriminator: high-confidence or regulated-category columns only. It must stay spared, appearing in SB-RLS-USING-TRUE-UNASSESSED and nowhere else." },
  { id: "N-RLS-FK-NON-TENANT", kind: "negative", cls: "bare FK column to a NON-tenant lookup table — an ordinary relation (#301 non-flood)", location: "supabase/migrations/", match: ["gadgets"], reviewTierHits: ["RLS enabled without FORCE \u2014 owner bypasses policies (static)", "M1 \u2014 Multi-tenant security"], note: "create table public.gadgets (… city uuid not null references public.cities(id) …) — byte-for-byte the same shape as the widgets plant (a bare uuid FK column on a per-user table), but `city` foreign-keys to public.cities, a plain lookup table, not a tenancy root. Naming `city` would be the false-positive flood that kept #301 open — nearly any schema has FK columns, and only the tenant-shaped FK target separates a scope column from an ordinary relation. At the GATE level this entry pins only that no HIGH-tier finding fires on gadgets (SB-RLS-TENANCY-MODEL is review-tier, so it can never fail a negative here); the precise non-flood claim — that gadgets/city stays OFF the NOT RECOGNISED list while widgets/site lands ON it — is proven by the paired unit tests in supabase-static.test.ts (#301)." },
  { id: "N-RLS-PUBLIC-CATALOG-USING-TRUE", kind: "negative", cls: "USING (true) on an intentionally world-readable reference table", location: "20260715000001_rls_using_true_negatives.sql", match: ["plans_select_public"], note: "create policy plans_select_public on public.plans for select using (true) — byte-for-byte the same clause as the documents_select_all plant, and correct: a published price list the pricing page renders to logged-out visitors. The discriminator is the SCHEMA, not the policy text: public.plans declares no tenant column, so it reviews per-user and usingTrueReview does not fire; public.documents declares tenant_id, so `every row readable` contradicts the table's own declaration. This entry is the point of the rule's narrow scope — flagging every `USING (true)` would make the catalog and the leak indistinguishable and train users to ignore the class outright (briefs/fp-rules.txt: a scanner that flags these wastes the client's trust)." },
  { id: "N-RLS-TENANT-SCOPED-READ", kind: "negative", cls: "correctly tenant-scoped SELECT policy on a tenant table", location: "20260715000001_rls_using_true_negatives.sql", match: ["reports_select_own_tenant"], note: "create policy reports_select_own_tenant on public.reports for select using (tenant_id = public.current_tenant_id()) — the correct shape a tenant-scoped READ takes: same table shape and same `for select` as the documents plant, but the USING constrains rows instead of admitting all of them. Pins that usingTrueReview keys off the CLAUSE, not the command — a rule matching `for select` on a tenant table would flag this and every correct read policy in the corpus." },
  { id: "N-RLS-TENANT-SCOPED-STATIC", kind: "negative", cls: "correctly tenant-scoped policy, both USING and WITH CHECK", location: "20260708000002_rls.sql", match: ["notes_rw_own_tenant"], note: "create policy notes_rw_own_tenant on public.notes for all using (tenant_id = public.current_tenant_id()) with check (tenant_id = public.current_tenant_id()) — both clauses constrain by the tenant key, so reviewPolicy clears it outright. This is the shape a CORRECT policy takes: flagging it would make every indicator noise, which is the failure mode #227 exists to prevent. Same for counters_rw_own_tenant in the same file." },
  { id: "N-STORAGE-OWNERSHIP-SCOPED-STATIC", kind: "negative", cls: "storage read/insert policies scoped to the caller's own folder", location: "20260710000001_b15_storage_secdef_semantic.sql", match: ["user_files_select_own", "user_files_insert_own"], reviewTierHits: ["auth_rls_initplan (static)"], note: "create policy user_files_select_own … using (bucket_id = 'user-files' and (storage.foldername(name))[1] = auth.uid()::text) — the standard Supabase one-folder-per-user ownership pattern, and its insert sibling. Cleared by per-table inference (storage.objects declares no tenant column → per-user mode) plus OWNER_BINDING now recognising an EXPRESSION bound to auth.uid(), not just a bare column. Both were false positives on the first #220 run against this target." },
  { id: "N-RLS-OWNROW-WITH-TENANTID", kind: "negative", cls: "own-row policy (id = auth.uid()) on a table that also declares tenant_id (the profiles shape)", location: "20260708000002_rls.sql", match: ["profiles_select_self"], reviewTierHits: ["M1 \u2014 Multi-tenant security", "auth_rls_initplan (static)"], note: "create policy profiles_select_self on public.profiles for select using (id = auth.uid()) — public.profiles DECLARES tenant_id, so inferTenancyModel reviews it per-tenant and the caller-identity rule fires (references auth.uid(), not tenant_id). This is the #257 residual FP: profiles is genuinely owner-scoped by its identity and only carries tenant_id for joins, but that is NOT statically separable from a tenant table wrongly keyed on the user — the #206 wrong-column bug the same rule must keep catching (rls-policy-review.test.ts pins auth.uid() = created_by on a tenant table SHOULD flag). PR #244 tried to narrow the rule and broke four #206 tests; the honest resolution is to keep the shape at REVIEW tier — surfaced and triaged out of the count, never a free-count FP. This entry pins exactly that: a review-tier hit is tolerated, a high-tier one is not." },
  { id: "N-RLS-DROP-POLICY-FIXED", kind: "negative", cls: "leaky USING(true) policy DROPPED and replaced by a later migration — the correctly-fixed schema (#937/#938)", location: "20260724000002_rls_drop_policy_fixed.sql", match: ["audit_events"], note: "#938: the corrected half of an original re-expression of the supabase-security-labs paired-lab shape (its own SQL is licence NONE and never distilled here — src/scan/external-corpus.ts). 20260724000001 creates public.audit_events (tenant_id) with a `using (true)` SELECT policy that publishes every tenant's rows; 20260724000002 DROPs it and replaces it with `using (tenant_id = public.current_tenant_id())`. Before #937 the static reviewer read migrations cumulatively with no drop-policy tracking, so the dropped audit_events_select_all was still reported against the FIXED final schema — broken and fixed produced byte-identical output (re-measured 2026-07-24). parseLivePolicies now judges the final live state, so the fix variant is clean. This entry pins that a correctly-fixed schema stays out of the FREE COUNT — the forward-looking guard: the moment `USING(true)` on a tenant table graduates from a review disclosure to a high-tier finding (the obvious next detector), a resurrected dropped policy here would fire and fail the gate. The BEHAVIORAL regression (dropped policy not reported even at review tier) is pinned by supabase-static.test.ts's `drop/replace lifecycle (#937)` block, which the gate's high-only negative check cannot express." },
];
