// Batch B1 — secrets & credential-exposure breadth (#71, spec §B1). Provider-key positives +
// benign-lookalike negatives scored against targets/calibration. Tiering follows the locked
// preamble: only ~100%-precision detections (decoded service_role claim, sb_secret_/private-key/
// connection-URI prefixes) are `high` (free count); provider patterns that only live TruffleHog
// verification would confirm land at `review` because the planted keys are FAKE and can't verify
// (same honest outcome as the existing P-HARDCODED-KEY). See GROUND-TRUTH.md §B1.

import type { CorpusEntry } from "./types.js";

export const secretsEntries: CorpusEntry[] = [
  // --- POSITIVES (must be caught) ---
  { id: "P-SRV-ROLE-JWT-SRC", kind: "positive", cls: "Hardcoded Supabase service_role JWT", location: "admin.js", match: ["service_role", "service-role"], expectedTier: "high", note: "service_role JWT literal in lib/admin.js (fake sig). gitleaks decodes the body (--max-decode-depth 2) and supabase-service-role-jwt fires on \"role\":\"service_role\" — full RLS bypass, high." },
  { id: "P-SB-SECRET-KEY", kind: "positive", cls: "Hardcoded sb_secret_ API key", location: "edge-config.js", match: ["sb_secret", "supabase-secret-key"], expectedTier: "high", note: "sb_secret_ literal in lib/edge-config.js. The sb_secret_ prefix is Supabase's dedicated secret namespace (never public) — gitleaks supabase-secret-key is high-precision, high." },
  { id: "P-PRIVATE-KEY", kind: "positive", cls: "Committed private key", location: "key.pem", match: ["private-key", "private key"], expectedTier: "high", note: "-----BEGIN PRIVATE KEY----- block in certs/key.pem (fake). gitleaks private-key rule; an unambiguous committed key, promoted to high." },
  { id: "P-SRV-ROLE-IN-BUNDLE", kind: "positive", cls: "service_role JWT in built client bundle", location: "prebuilt-bundle", match: ["service_role", "service-role"], expectedTier: "high", note: "service_role JWT embedded in a committed pre-built chunk (prebuilt-bundle/chunk.*.js) modelling what leaks into .next/static shipped to the browser. Same decoded-claim detection → high. (The harness doesn't run `next build`; the source scan reads the committed chunk. secrets.ts also supports a live bundleDir pass.)" },
  { id: "P-DB-URL-PASSWORD", kind: "positive", cls: "DB connection string with inline password", location: ".env.local", match: ["postgres", "harvey-db-uri", "connection uri"], expectedTier: "high", note: "DATABASE_URL=postgres://appuser:<pw>@db.calibrationref01.supabase.co in .env.local (fake pw). Custom gitleaks harvey-db-uri-credentials (scheme+user:password@host, loopback hosts allowlisted) → high." },
  { id: "P-OPENAI-KEY", kind: "positive", cls: "Hardcoded OpenAI API key", location: "llm.js", match: ["openai"], expectedTier: "review", note: "OPENAI_API_KEY literal in lib/llm.js. VALUE DEFANGED (real sk-...T3BlbkFJ... trips GitHub push protection); committed catch is gitleaks generic-api-key (high-entropy on a KEY-named var, provider word in the match), the openai-api-key pattern validated pre-commit. Unverifiable → review." },
  { id: "P-STRIPE-SECRET", kind: "positive", cls: "Hardcoded Stripe live secret key", location: "pay.js", match: ["stripe"], expectedTier: "review", note: "STRIPE_SECRET_KEY literal in lib/pay.js. VALUE DEFANGED (real sk_live_ trips push protection); committed catch is gitleaks generic-api-key, the stripe-access-token pattern validated pre-commit. Unverifiable → review." },
  { id: "P-AWS-KEY", kind: "positive", cls: "Hardcoded AWS access key + secret", location: "s3.js", match: ["aws"], expectedTier: "review", note: "AWS_ACCESS_KEY_ID + secret in lib/s3.js. VALUES DEFANGED (real AKIA... + 40-char secret trip push protection); committed catch is gitleaks generic-api-key on the secret, the aws-access-token pattern validated pre-commit. Unverifiable → review." },
  { id: "P-GH-TOKEN", kind: "positive", cls: "Hardcoded GitHub PAT", location: "deploy.js", match: ["github", "ghp_"], expectedTier: "review", note: "ghp_ token in scripts/deploy.js (fake, valid-shape; push protection did not block it). gitleaks github-pat pattern; unverifiable → review." },
  { id: "P-SENDGRID-KEY", kind: "positive", cls: "Hardcoded SendGrid API token", location: "email.js", match: ["sendgrid"], expectedTier: "review", note: "SENDGRID_API_KEY literal in lib/email.js. VALUE DEFANGED (real SG.xxx.xxx trips push protection); committed catch is gitleaks generic-api-key, the sendgrid-api-token pattern validated pre-commit. Unverifiable → review." },
  { id: "P-JWT-SIGNING-SECRET", kind: "positive", cls: "Hardcoded JWT/session signing secret", location: "auth.js", match: ["generic-api-key"], expectedTier: "review", note: "High-entropy signing secret literal fed to jwt.sign in lib/auth.js (fake). gitleaks generic-api-key (literal-secret heuristic) → review; a provider-agnostic app secret." },
  // #130: location uses ".env:" (trailing colon, gitleaks locations are "path:line") rather
  // than bare ".env", so the substring match can't also credit findings from .env.local or
  // .env.example (both have "." not ":" right after "env"). ".env:" alone would still
  // substring-match "supabase/docker.env:N" (P-SB-DEFAULT-JWT-SECRET / N-SB-JWT-ROTATED), but
  // that fixture's only findings are about a JWT SIGNING secret and never carry either match
  // keyword below, so the required keyword match still isolates this entry (verified live).
  { id: "P-ENV-COMMITTED", kind: "positive", cls: "Committed bare .env with multiple live-shaped secrets", location: ".env:", match: ["service_role", "harvey-db-uri-credentials"], expectedTier: "high", note: "A committed bare .env (not .env.local, and not gitignore-excluded — force-added like .env.local's B1 fixtures) carrying a decoded service_role JWT claim plus a second live-shaped DB URI in the same file. Distinct from P-DB-URL-PASSWORD (a single credential in .env.local): this proves the committed-.env-with-multiple-live-values shape. Its negative is N-ENV-EXAMPLE (.env.example, already in the base corpus) — reused rather than duplicated." },

  // --- NEGATIVES (must NOT be flagged in the free count) ---
  { id: "N-STRIPE-PK-PUBLISHABLE", kind: "negative", cls: "Stripe publishable key is public", location: ".env.local", match: ["publishable"], note: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_... is public by design (like the anon key). gitleaks allowlist (pk_(live|test)_ regexTarget=line) suppresses every rule on the line — cleared, not flagged." },
  { id: "N-STRIPE-TEST-KEY", kind: "negative", cls: "Stripe test-mode secret key", location: ".env.local", match: ["sk_test"], note: "sk_test_ is a test-mode key (no production risk). gitleaks stripe-access-token still pattern-matches it, so it lands at review only (triaged out), never high." },
  { id: "N-AWS-EXAMPLE-KEY", kind: "negative", cls: "AWS documented example key", location: "aws-setup.md", match: ["aws", "akia"], note: "AKIAIOSFODNN7EXAMPLE in docs/aws-setup.md is the AWS-docs placeholder. gitleaks stopword-allowlists the EXAMPLE marker — cleared, aws-access-token stays silent." },
  { id: "N-DB-URL-LOCAL", kind: "negative", cls: "Local-dev DB URI (loopback host)", location: "README.md", match: ["postgres", "database"], note: "postgres://postgres:postgres@127.0.0.1 in README.md is the standard local Supabase dev string, not a committed credential. harvey-db-uri-credentials allowlists loopback hosts — cleared." },
];
