import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { detectPackageManager, installAllCommand, installExtraCommand, withRestoredManifest } from "./package-manager.js";

const dirs: string[] = [];
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

function tmpDir(): string {
  const d = mkdtempSync(join(tmpdir(), "harvey-pm-"));
  dirs.push(d);
  return d;
}

describe("detectPackageManager (#1284/#1268)", () => {
  it("detects pnpm from pnpm-lock.yaml", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
    expect(detectPackageManager(dir)).toBe("pnpm");
  });

  it("detects yarn from yarn.lock", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "yarn.lock"), "# THIS IS AN AUTOGENERATED FILE\n");
    expect(detectPackageManager(dir)).toBe("yarn");
  });

  it("defaults to npm when neither pnpm-lock.yaml nor yarn.lock is present", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "package-lock.json"), "{}");
    expect(detectPackageManager(dir)).toBe("npm");
    expect(detectPackageManager(tmpDir())).toBe("npm"); // no lockfile at all
  });

  it("prefers pnpm over yarn when (unusually) both lockfiles are present", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
    writeFileSync(join(dir, "yarn.lock"), "# THIS IS AN AUTOGENERATED FILE\n");
    expect(detectPackageManager(dir)).toBe("pnpm");
  });
});

describe("installAllCommand / installExtraCommand (#1284/#1268)", () => {
  it("npm: install --no-audit --no-fund for a full install, --no-save -D <pkgs> for extras", () => {
    expect(installAllCommand("npm")).toEqual({ bin: "npm", args: ["install", "--no-audit", "--no-fund"] });
    expect(installExtraCommand("npm", ["@stryker-mutator/core"])).toEqual({
      bin: "npm",
      args: ["install", "--no-save", "--no-audit", "--no-fund", "-D", "@stryker-mutator/core"],
    });
  });

  it("pnpm: install for a full install (resolves EVERY workspace member, unlike npm), add -D <pkgs> for extras", () => {
    expect(installAllCommand("pnpm")).toEqual({ bin: "pnpm", args: ["install"] });
    expect(installExtraCommand("pnpm", ["@stryker-mutator/core", "@stryker-mutator/vitest-runner"])).toEqual({
      bin: "pnpm",
      args: ["add", "-D", "@stryker-mutator/core", "@stryker-mutator/vitest-runner"],
    });
  });

  it("yarn: install for a full install, add -D <pkgs> for extras", () => {
    expect(installAllCommand("yarn")).toEqual({ bin: "yarn", args: ["install"] });
    expect(installExtraCommand("yarn", ["@stryker-mutator/core"])).toEqual({ bin: "yarn", args: ["add", "-D", "@stryker-mutator/core"] });
  });

  it("installAllCommand forwards caller flags (e.g. --frozen-lockfile) unchanged", () => {
    expect(installAllCommand("pnpm", ["--frozen-lockfile"]).args).toEqual(["install", "--frozen-lockfile"]);
  });
});

describe("withRestoredManifest (#1284/#1268 — the pnpm/yarn equivalent of npm's --no-save)", () => {
  it("npm: runs fn as-is, no restore (nothing was ever written for --no-save to undo)", () => {
    const dir = tmpDir();
    let ran = false;
    const result = withRestoredManifest(dir, "npm", () => {
      ran = true;
      return 42;
    });
    expect(ran).toBe(true);
    expect(result).toBe(42);
  });

  it("pnpm: restores package.json AND pnpm-lock.yaml to their exact original bytes after fn runs", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "package.json"), '{"name":"fixture","devDependencies":{}}');
    writeFileSync(join(dir, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\npackages: {}\n");
    withRestoredManifest(dir, "pnpm", () => {
      // Simulates `pnpm add -D` actually installing something: it writes new bytes to both files.
      writeFileSync(join(dir, "package.json"), '{"name":"fixture","devDependencies":{"@stryker-mutator/core":"^9.0.0"}}');
      writeFileSync(join(dir, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\npackages:\n  '@stryker-mutator/core': {}\n");
    });
    expect(readFileSync(join(dir, "package.json"), "utf8")).toBe('{"name":"fixture","devDependencies":{}}');
    expect(readFileSync(join(dir, "pnpm-lock.yaml"), "utf8")).toBe("lockfileVersion: '9.0'\npackages: {}\n");
  });

  it("restores even when fn throws — the manifest is never left mid-install-mutated on a failed provision", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "package.json"), '{"name":"fixture"}');
    expect(() =>
      withRestoredManifest(dir, "pnpm", () => {
        writeFileSync(join(dir, "package.json"), '{"name":"fixture","devDependencies":{"x":"1"}}');
        throw new Error("install failed");
      }),
    ).toThrow("install failed");
    expect(readFileSync(join(dir, "package.json"), "utf8")).toBe('{"name":"fixture"}');
  });

  it("a lockfile that did not exist before stays absent after — never handed a phantom lockfile", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "package.json"), '{"name":"fixture"}');
    // No pnpm-lock.yaml before — fn "creates" one, as a real `pnpm add` on a lockfile-less target would.
    withRestoredManifest(dir, "pnpm", () => {
      writeFileSync(join(dir, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
    });
    expect(existsSync(join(dir, "pnpm-lock.yaml"))).toBe(false);
  });

  it("yarn: restores yarn.lock, not pnpm-lock.yaml", () => {
    const dir = tmpDir();
    writeFileSync(join(dir, "package.json"), '{"name":"fixture"}');
    writeFileSync(join(dir, "yarn.lock"), "# original\n");
    withRestoredManifest(dir, "yarn", () => {
      writeFileSync(join(dir, "yarn.lock"), "# mutated\n");
    });
    expect(readFileSync(join(dir, "yarn.lock"), "utf8")).toBe("# original\n");
  });
});
